// Generated by node scripts/build-pwa.mjs. Do not edit sw.js directly.
const PREFIX='super-rich-pwa-';
const CACHE=PREFIX+'00ed6ba56285f75a';
const BASE=new URL('./',self.location.href);
const ASSETS=["city/account-save.js","city/acquisitions.js","city/activity.js","city/app.js","city/art.css","city/art.js","city/asset-sale.js","city/audio.js","city/auth-ui.js","city/auth.js","city/broker.js","city/building-art.js","city/careers.js","city/city.css","city/cloud-save.js","city/cloud-ui.js","city/cloud.css","city/collection-photos.css","city/collection-photos.js","city/compound.css","city/compound.js","city/construction.js","city/developer.js","city/economy.js","city/empire.css","city/empire.js","city/engine.js","city/events.js","city/firebase-config.js","city/flex.css","city/flex.js","city/growth.js","city/i18n-ko.js","city/i18n.js","city/investment.js","city/journey-ui.js","city/journey.js","city/landmark-construction.js","city/landmark-presets.js","city/landmark-ui.js","city/landmarks.css","city/landmarks.js","city/landmarks/aurora-spire.svg","city/landmarks/crescent-bay-hotel.svg","city/landmarks/sky-garden-tower.svg","city/legacy.css","city/legacy.js","city/living-costs.js","city/luxury-models.css","city/luxury-models.js","city/mansion-art.js","city/mansion-preview.js","city/mansion.css","city/mansion.js","city/map-vehicles.js","city/market-report.js","city/market.js","city/motion.js","city/new-game.js","city/people-art.js","city/projects.js","city/property-art.js","city/pwa.css","city/pwa.js","city/release.css","city/release.js","city/render.js","city/reputation.js","city/reward-provider.js","city/rewards.js","city/rich-life.css","city/rich-life.js","city/rival.js","city/rng.js","city/scenery-art.js","city/shortcut.js","city/startups.js","city/stocks.js","city/supabase-config.js","city/vehicle-art.js","city/venture.js","city/world-life.js","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","icons/icon.svg","index.html","manifest.webmanifest"].map(file=>new URL(file,BASE).href);
const SHELL=new Set(ASSETS);
self.addEventListener('install',event=>{
 event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS.map(url=>new Request(url,{cache:'reload'})))));
 // The update waits for all old game windows to close, preserving an active run.
});
self.addEventListener('activate',event=>{
 event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',event=>{
 const req=event.request,url=new URL(req.url);
 if(req.method!=='GET'||url.origin!==BASE.origin)return;
 const home=url.pathname===BASE.pathname||url.pathname===new URL('index.html',BASE).pathname;
 const key=home?new URL('index.html',BASE).href:url.origin+url.pathname;
 // Never intercept cloud saves, live prices, unrelated routes or private endpoints.
 const image=url.pathname.startsWith(new URL('city/assets/',BASE).pathname)&&/\.(png|jpg|jpeg|webp)$/.test(url.pathname);
 if(!SHELL.has(key)&&!image)return;
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE),cached=await cache.match(key);
  if(cached)return cached;
  const response=await fetch(req);
  if(response.ok&&!response.redirected){try{await cache.put(key,response.clone());}catch{/* Storage pressure must not block online play. */}}
  return response;
 })());
});
