import {marketFactor,marketPrice} from './economy.js';
import {awardAssetFame} from './reputation.js';
export const SMALL_COMPANIES={shop:{name:'리틀마켓 커머스',cost:30000,description:'고정 고객을 확보한 작은 온라인 브랜드'},agency:{name:'픽셀 디자인 에이전시',cost:75000,description:'기업 고객과 정기 계약을 맺은 디자인 회사'},software:{name:'플로우 업무 도구',cost:150000,description:'구독 고객을 보유한 소형 소프트웨어 회사'}};
export const GROWTH_OUTCOMES=[{label:'가치 하락',chance:.15,min:.7,max:.95},{label:'안정 성장',chance:.75,min:1.1,max:1.8},{label:'고성장',chance:.08,min:2,max:3},{label:'대박',chance:.02,min:5,max:10}];
export function companyGrowth(roll){let start=0;for(const o of GROWTH_OUTCOMES){if(roll<start+o.chance)return{label:o.label,multiple:Math.round((o.min+(o.max-o.min)*(roll-start)/o.chance)*100)/100};start+=o.chance;}return{label:'대박',multiple:10};}
function rollFor(s,serial){let x=(s.seed^Math.imul(serial,0x9e3779b1)^0x51ed270b)>>>0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return((x^(x>>>16))>>>0)/4294967296;}
export function companyValue(s,p){return Math.round(SMALL_COMPANIES[p.type].cost*(s.month>=p.due?companyGrowth(p.roll).multiple:1)*(p.soldFactor??marketFactor(s)));}
export function acquisitionSummary(s){const a=s.acquisitions;return{active:a?.active||[],history:a?.history||[],assets:(a?.active||[]).reduce((n,p)=>n+companyValue(s,p),0)};}
export function buyCompany(s,type){if(!Object.hasOwn(SMALL_COMPANIES,type))return{ok:false,msg:'인수할 회사를 확인하세요.'};const d=SMALL_COMPANIES[type];if((s.acquisitions?.active.length||0)>=3)return{ok:false,msg:'동시 운영은 최대 3개 회사입니다.'};if(s.money<marketPrice(s,d.cost))return{ok:false,msg:'인수 자금이 부족합니다.'};const a=s.acquisitions??={serial:0,active:[],history:[]};const id=++a.serial;a.active.push({id,type,paid:marketPrice(s,d.cost),started:s.month,due:s.month+3,roll:rollFor(s,id)});s.money-=marketPrice(s,d.cost);s.log.unshift(`${d.name} 인수 · ${money(marketPrice(s,d.cost))} · 3개월 성장 시작`);s.log=s.log.slice(0,25);awardAssetFame(s,`company:${type}`,d.cost,d.name+' 인수',10);return{ok:true,msg:'인수 완료 · 3개월 뒤 성장 결과와 매각 가격이 공개됩니다.'};}
export function sellCompany(s,id){const a=s.acquisitions,p=a?.active.find(p=>p.id===id);if(!p)return{ok:false,msg:'보유 회사를 확인하세요.'};if(s.month<p.due)return{ok:false,msg:'3개월 성장 기간이 끝나야 매각할 수 있습니다.'};const value=companyValue(s,p),profit=value-(p.paid??SMALL_COMPANIES[p.type].cost);s.money+=value;a.active=a.active.filter(p=>p.id!==id);a.history.unshift({...p,soldMonth:s.month,soldFactor:marketFactor(s),value});a.history=a.history.slice(0,12);const msg=`${SMALL_COMPANIES[p.type].name} 매각 · ${money(value)} 회수 · 손익 ${money(profit)}`;s.log.unshift(msg);s.log=s.log.slice(0,25);return{ok:true,msg};}
export function validAcquisitions(s){const a=s.acquisitions;if(a===undefined)return true;if(!a||!Number.isSafeInteger(a.serial)||a.serial<0||!Array.isArray(a.active)||a.active.length>3||!Array.isArray(a.history)||a.history.length>12)return false;const ids=new Set();const valid=p=>{if(!p||(p.paid!==undefined&&(!Number.isFinite(p.paid)||p.paid<0))||(p.soldFactor!==undefined&&(!Number.isFinite(p.soldFactor)||p.soldFactor<.5||p.soldFactor>1))||!Number.isSafeInteger(p.id)||p.id<1||p.id>a.serial||ids.has(p.id)||!Object.hasOwn(SMALL_COMPANIES,p.type)||!Number.isSafeInteger(p.started)||p.started<0||p.started>s.month||p.due!==p.started+3||!Number.isFinite(p.roll)||p.roll<0||p.roll>=1)return false;ids.add(p.id);return true;};return a.active.every(p=>p.soldFactor===undefined&&valid(p))&&a.history.every(p=>valid(p)&&Number.isSafeInteger(p.soldMonth)&&p.soldMonth>=p.due&&p.soldMonth<=s.month&&p.value===companyValue({...s,economy:undefined},{...p,soldFactor:p.soldFactor??1}));}
const money=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
export function acquisitionsDialog(s){const a=acquisitionSummary(s);return`<span class="eyebrow">SMALL BUSINESS · BUY & GROW</span><h2>작은 회사를 키워, 더 큰 가격에.</h2><p>₲30,000부터 시작합니다. 전문 경영진이 3개월간 운영하면 성장 결과가 공개되고, 원하는 때 매각할 수 있습니다. 추가 운영비와 월 배당은 없습니다.</p><div class="owner-reputation"><h3>75%는 1.1–1.8배의 적당한 성장</h3><p>${GROWTH_OUTCOMES.map(o=>`${o.label} ${o.chance*100}% · ${o.min}–${o.max}배`).join('<br>')}</p><small>배수는 정상 시세 대비 성장 배수입니다. 구간 안의 배수도 무작위로 정해집니다. 3개월 이후 성장 배수는 고정되지만 경기 시세는 반영되며, 다시 불러와도 결과가 바뀌지 않습니다.</small></div><div class="empire-grid">${Object.entries(SMALL_COMPANIES).map(([id,d])=>`<section class="empire-card"><h3>${d.name}</h3><p>${d.description}</p><strong>${money(marketPrice(s,d.cost))}</strong><button data-company-buy="${id}" ${s.money<marketPrice(s,d.cost)||a.active.length>=3?'disabled':''}>${a.active.length>=3?'운영 한도 도달':'인수하기 · '+money(marketPrice(s,d.cost))}</button></section>`).join('')}</div><h3>운영 중인 회사 ${a.active.length}/3 · 평가액 ${money(a.assets)}</h3>${a.active.map(p=>{const ready=s.month>=p.due,g=companyGrowth(p.roll);return`<section class="empire-card"><h3>${SMALL_COMPANIES[p.type].name} · #${p.id}</h3><p>${ready?`${g.label} · ${g.multiple}배 · 평가손익 ${money(companyValue(s,p)-(p.paid??SMALL_COMPANIES[p.type].cost))}`:`성장 중 · 결과 공개까지 ${p.due-s.month}개월`}</p><button data-company-sell="${p.id}" ${ready?'':'disabled'}>${ready?'매각하기 · '+money(companyValue(s,p)):'경영진이 회사를 키우고 있습니다'}</button></section>`;}).join('')||'<p>아직 인수한 회사가 없습니다.</p>'}${a.history.length?`<details><summary>최근 매각 기록</summary>${a.history.map(p=>`<p>${SMALL_COMPANIES[p.type].name} · ${companyGrowth(p.roll).multiple}배 · 회수 ${money(p.value)} · 손익 ${money(p.value-(p.paid??SMALL_COMPANIES[p.type].cost))}</p>`).join('')}</details>`:''}<p>인수금은 회사 자산으로 전환됩니다. 성장에 따른 가치 변화는 순자산에, 매각 대금은 현금에 반영됩니다.</p>`;}
