import {L} from './i18n.js';
import {marketFactor,marketPrice} from './economy.js';
import {awardAssetFame} from './reputation.js';
export const SMALL_COMPANIES={shop:{name:L('Little Market Commerce'),cost:30000,description:L('A small online brand with loyal customers')},agency:{name:L('Pixel Design Agency'),cost:75000,description:L('A design firm with recurring corporate contracts')},software:{name:L('Flow Work Tools'),cost:150000,description:L('A small software company with subscribers')}};
export const GROWTH_OUTCOMES=[{label:L('Value drop'),chance:.15,min:.7,max:.95},{label:L('Steady growth'),chance:.75,min:1.1,max:1.8},{label:L('High growth'),chance:.08,min:2,max:3},{label:L('Jackpot'),chance:.02,min:5,max:10}];
export function companyGrowth(roll){let start=0;for(const o of GROWTH_OUTCOMES){if(roll<start+o.chance)return{label:o.label,multiple:Math.round((o.min+(o.max-o.min)*(roll-start)/o.chance)*100)/100};start+=o.chance;}return{label:L('Jackpot'),multiple:10};}
function rollFor(s,serial){let x=(s.seed^Math.imul(serial,0x9e3779b1)^0x51ed270b)>>>0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return((x^(x>>>16))>>>0)/4294967296;}
export function companyValue(s,p){return Math.round(SMALL_COMPANIES[p.type].cost*(s.month>=p.due?companyGrowth(p.roll).multiple:1)*(p.soldFactor??marketFactor(s)));}
export function acquisitionSummary(s){const a=s.acquisitions;return{active:a?.active||[],history:a?.history||[],assets:(a?.active||[]).reduce((n,p)=>n+companyValue(s,p),0)};}
export function buyCompany(s,type){if(!Object.hasOwn(SMALL_COMPANIES,type))return{ok:false,msg:L('Check the company to acquire.')};const d=SMALL_COMPANIES[type];if((s.acquisitions?.active.length||0)>=3)return{ok:false,msg:L('You can run at most 3 companies at once.')};if(s.money<marketPrice(s,d.cost))return{ok:false,msg:L('Not enough cash to acquire.')};const a=s.acquisitions??={serial:0,active:[],history:[]};const id=++a.serial;a.active.push({id,type,paid:marketPrice(s,d.cost),started:s.month,due:s.month+3,roll:rollFor(s,id)});s.money-=marketPrice(s,d.cost);s.log.unshift(L`${d.name} acquired · ${money(marketPrice(s,d.cost))} · 3-month growth begins`);s.log=s.log.slice(0,25);awardAssetFame(s,`company:${type}`,d.cost,d.name+L(' acquisition'),10);return{ok:true,msg:L('Acquired · Growth result and sale price revealed in 3 months.')};}
export function sellCompany(s,id){const a=s.acquisitions,p=a?.active.find(p=>p.id===id);if(!p)return{ok:false,msg:L('Check the company you own.')};if(s.month<p.due)return{ok:false,msg:L('You can sell after the 3-month growth period ends.')};const value=companyValue(s,p),profit=value-(p.paid??SMALL_COMPANIES[p.type].cost);s.money+=value;a.active=a.active.filter(p=>p.id!==id);a.history.unshift({...p,soldMonth:s.month,soldFactor:marketFactor(s),value});a.history=a.history.slice(0,12);const msg=L`${SMALL_COMPANIES[p.type].name} sold · ${money(value)} recovered · P&L ${money(profit)}`;s.log.unshift(msg);s.log=s.log.slice(0,25);return{ok:true,msg};}
export function validAcquisitions(s){const a=s.acquisitions;if(a===undefined)return true;if(!a||!Number.isSafeInteger(a.serial)||a.serial<0||!Array.isArray(a.active)||a.active.length>3||!Array.isArray(a.history)||a.history.length>12)return false;const ids=new Set();const valid=p=>{if(!p||(p.paid!==undefined&&(!Number.isFinite(p.paid)||p.paid<0))||(p.soldFactor!==undefined&&(!Number.isFinite(p.soldFactor)||p.soldFactor<.5||p.soldFactor>1))||!Number.isSafeInteger(p.id)||p.id<1||p.id>a.serial||ids.has(p.id)||!Object.hasOwn(SMALL_COMPANIES,p.type)||!Number.isSafeInteger(p.started)||p.started<0||p.started>s.month||p.due!==p.started+3||!Number.isFinite(p.roll)||p.roll<0||p.roll>=1)return false;ids.add(p.id);return true;};return a.active.every(p=>p.soldFactor===undefined&&valid(p))&&a.history.every(p=>valid(p)&&Number.isSafeInteger(p.soldMonth)&&p.soldMonth>=p.due&&p.soldMonth<=s.month&&p.value===companyValue({...s,economy:undefined},{...p,soldFactor:p.soldFactor??1}));}
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
export function acquisitionsDialog(s){const a=acquisitionSummary(s);return L`<span class="eyebrow">SMALL BUSINESS · BUY & GROW</span><h2>Grow a small company, sell for more.</h2><p>Starts from ₲30,000. Professional managers run it for 3 months, then the growth result is revealed and you can sell whenever you like. No extra operating costs or monthly dividends.</p><div class="owner-reputation"><h3>75% chance of moderate 1.1–1.8× growth</h3><p>${GROWTH_OUTCOMES.map(o=>L`${o.label} ${o.chance*100}% · ${o.min}–${o.max}×`).join('<br>')}</p><small>Multiples are growth versus normal market price. The exact multiple within a band is random. After 3 months the growth multiple is locked, though market conditions still apply, and reloading never changes the result.</small></div><div class="empire-grid">${Object.entries(SMALL_COMPANIES).map(([id,d])=>`<section class="empire-card"><h3>${d.name}</h3><p>${d.description}</p><strong>${money(marketPrice(s,d.cost))}</strong><button data-company-buy="${id}" ${s.money<marketPrice(s,d.cost)||a.active.length>=3?'disabled':''}>${a.active.length>=3?L('Operating limit reached'):L('Acquire · ')+money(marketPrice(s,d.cost))}</button></section>`).join('')}</div><h3>Companies running ${a.active.length}/3 · Valuation ${money(a.assets)}</h3>${a.active.map(p=>{const ready=s.month>=p.due,g=companyGrowth(p.roll);return`<section class="empire-card"><h3>${SMALL_COMPANIES[p.type].name} · #${p.id}</h3><p>${ready?L`${g.label} · ${g.multiple}× · Unrealized P&L ${money(companyValue(s,p)-(p.paid??SMALL_COMPANIES[p.type].cost))}`:L`Growing · Result in ${p.due-s.month} months`}</p><button data-company-sell="${p.id}" ${ready?'':'disabled'}>${ready?L('Sell · ')+money(companyValue(s,p)):L('Managers are growing the company')}</button></section>`;}).join('')||L('<p>No companies acquired yet.</p>')}${a.history.length?L`<details><summary>Recent Sales</summary>${a.history.map(p=>L`<p>${SMALL_COMPANIES[p.type].name} · ${companyGrowth(p.roll).multiple}× · Recovered ${money(p.value)} · P&L ${money(p.value-(p.paid??SMALL_COMPANIES[p.type].cost))}</p>`).join('')}</details>`:''}<p>The purchase price becomes company assets. Value changes from growth count toward net worth; sale proceeds go to cash.</p>`;}
