import {L} from './i18n.js';
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
const signed=n=>(n>=0?'+':'−')+money(Math.abs(n));
const percent=n=>n===null?L('N/A'):`${n>=0?'+':''}${n.toFixed(1)}%`;
export function saleDialog(r,done=false){
 if(!r)return L('<h2>No asset to sell.</h2>');
 const row=(label,value)=>`<div style="display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;padding:10px 0;border-bottom:1px solid #dce2d5;font-size:14px"><span>${label}</span><b>${value}</b></div>`;
 return L`<span class="eyebrow">ASSET RETURN</span><h2>${done?L('Sale complete'):L('Projected sale P&L')} · ${r.name}</h2>${r.protectedPrincipal?L('<p><b>Principal-protected sale</b> · You get back at least the total invested in land, construction and expansion. Existing rent income stays as is.</p>'):''}<div class="summary-card">${row(L('Initial investment')+(r.estimated?L(' (est.)'):''),money(r.initial))}${row(L('Total expansion spend'),money(r.upgrades))}${row(L('Total invested'),money(r.invested))}${row(done?L('Actual sale proceeds'):L('Projected sale proceeds'),money(r.value))}${row(L('Sale P&L vs. initial investment')+(r.estimated?L(' (est.)'):''),signed(r.gain)+' · '+percent(r.roi))}${row(L('Actual sale P&L incl. expansion'),signed(r.netGain))}${row(L`Net operating profit since month ${r.since}`,signed(r.operating))}${row(L('Total P&L incl. expansion & operations')+(r.estimated?L(' (partial record)'):''),signed(r.totalGain)+' · '+percent(r.totalRoi))}</div><p class="help">Building value rises ${((r.annualGrowth??.2)*100).toFixed(0)}% a year (compounded monthly) on a ${r.area||1}-tile basis, and land value rises separately. During recessions and recoveries the market decline is reflected in the valuation and in the principal-protection floor of rental buildings. The displayed return is against the initial investment (land + construction) and excludes expansion costs. Actual sale P&L and total P&L incl. operations include expansion costs. Net operating profit deducts this asset's operating costs and excludes personal living expenses and loan interest.${r.estimated?L('<br>This older save has no purchase-time record, so the initial investment is an estimate based on current land and construction prices. Past operating profit is not backfilled and appreciation counts only from when tracking began.'):''}<br>In Sandbox, free construction and expansion are still shown at normal prices as the investment basis.</p>${done?L('<p role="status">Sale proceeds have been added to your cash. The transaction is recorded in your activity log.</p>'):L('<p>This closes the business and clears the lot. Check the figures above before selling.</p><button data-action="confirm-sell" class="primary full">Sell at This Price</button>')}`;
}
