// One hundred chance cards. Monetary rates use the existing Tycoon spending cap.
import {L} from './i18n.js';
const money=n=>(n<0?'−':'')+'₲'+Math.abs(Math.round(n)).toLocaleString('en-US');
const signed=n=>(n>=0?'+':'−')+Math.abs(n);

function buildChoice(choice,wealth,title){
 const stake=rate=>Math.round(Math.max(0,Math.min(wealth,30000000))*rate);
 const {costRate=0,moneyRate=0,later,...effects}=choice;
 const o={...effects,cost:stake(costRate)},desc=[];
 if(costRate)desc.push(L`Spend ${money(o.cost)}`);
 if(moneyRate){o.money=stake(moneyRate);desc.push(L`Receive ${money(o.money)}`);}
 if(o.fame)desc.push(L`Reputation ${signed(o.fame)}`);
 if(o.stress)desc.push(L`Stress ${signed(o.stress)}`);
 if(o.memories)desc.push(L`Memories +${o.memories}`);
 if(o.multiplier)desc.push(L`Rental & hotel revenue ${signed(Math.round((o.multiplier-1)*100))}% for ${o.months} months`);
 if(later){
  o.later={...later,amount:stake(later.amount),fallback:stake(later.fallback||0),label:title};
  desc.push(later.chance===1?L`In ${later.months} months: ${money(o.later.amount)} guaranteed`:L`In ${later.months} months: ${Math.round(later.chance*100)}% chance of ${money(o.later.amount)}; otherwise ${money(o.later.fallback)}`);
 }
 o.desc=desc.length?desc.join(' · '):L('No change');
 return o;
}

const CHANCE_CARDS=[
 {id:"family_bakery",title:L("A cousin's neighborhood bakery"),text:L("Your cousin has recipes and regular customers, but needs money for a bigger oven. Will you share the risk?"),choices:[{label:L("Finance the oven"),"costRate":0.008,"fame":5,"later":{"months":6,"amount":0.012,"chance":0.65,"fallback":0.002}},{label:L("Help with the business plan"),"stress":5,"fame":3}]},
 {id:"family_tuition",title:L("A niece's overseas scholarship"),text:L("Your niece won a scholarship, but housing and travel are not covered. She asks you to bridge the gap."),choices:[{label:L("Cover the living costs"),"costRate":0.005,"stress":-8,"memories":1},{label:L("Find a local study program"),"stress":4}]},
 {id:"family_reunion",title:L("The long-delayed family reunion"),text:L("Relatives finally found a weekend everyone can attend. A catered reunion would make the day easier."),choices:[{label:L("Host the reunion"),"costRate":0.002,"memories":2,"stress":-12},{label:L("Arrange a simple picnic"),"memories":1,"stress":-5}]},
 {id:"family_medical",title:L("A relative's unexpected surgery"),text:L("A relative faces a treatment bill while an insurance claim is under review. They need help today."),choices:[{label:L("Advance the treatment bill"),"costRate":0.01,"stress":-5,"later":{"months":3,"amount":0.008,"chance":0.8,"fallback":0}},{label:L("Help arrange installments"),"stress":8}]},
 {id:"family_farm",title:L("The family farm's new harvest"),text:L("An uncle wants to trial greenhouse crops. A small test costs less, while a full season could pay more."),choices:[{label:L("Finance a full season"),"costRate":0.015,"later":{"months":9,"amount":0.022,"chance":0.6,"fallback":0.004}},{label:L("Pay for a small trial"),"costRate":0.003,"later":{"months":3,"amount":0.0035,"chance":0.85,"fallback":0.001}}]},
 {id:"family_wedding",title:L("A sibling's wedding surprise"),text:L("The couple plans a modest wedding. You could secretly upgrade the celebration or give a heartfelt speech."),choices:[{label:L("Give a celebration gift"),"costRate":0.004,"memories":2,"stress":-6},{label:L("Write the wedding speech"),"memories":1,"stress":3}]},
 {id:"family_debt",title:L("A parent asks for debt relief"),text:L("A parent admits that a small loan has grown burdensome. Paying it off would ease their worries."),choices:[{label:L("Clear the family loan"),"costRate":0.012,"stress":-15,"fame":4},{label:L("Make a repayment plan together"),"stress":6}]},
 {id:"family_film",title:L("A sibling's first short film"),text:L("Your sibling finished a script and asks for festival submission funding. Distribution income is uncertain."),choices:[{label:L("Back the festival release"),"costRate":0.006,"memories":1,"later":{"months":6,"amount":0.014,"chance":0.35,"fallback":0}},{label:L("Offer feedback only"),"fame":2,"stress":3}]},
 {id:"family_emergency",title:L("A family emergency fund"),text:L("Relatives propose a shared emergency fund. You can contribute without expecting a financial return."),choices:[{label:L("Contribute to the fund"),"costRate":0.008,"fame":8,"stress":-10},{label:L("Help set clear contribution rules"),"stress":4,"fame":2}]},
 {id:"family_recipe",title:L("Grandmother's recipe book"),text:L("The family found handwritten recipes. A printed keepsake would preserve them, while a digital copy costs nothing."),choices:[{label:L("Print a family keepsake"),"costRate":0.002,"memories":2,"stress":-5},{label:L("Share a digital copy"),"memories":1}]},
 {id:"refund_duplicate",title:L("A duplicate payment discovered"),text:L("An accountant finds a duplicate administrative payment. A formal refund request takes time; a settlement returns less today."),choices:[{label:L("Request the full refund"),"stress":3,"later":{"months":3,"amount":0.008,"chance":1}},{label:L("Accept an immediate settlement"),"moneyRate":0.005}]},
 {id:"legacy_letters",title:L("An old family estate settlement"),text:L("A distant estate administrator locates an unclaimed payment in your name. You can collect it or share it with a community archive."),choices:[{label:L("Collect the settlement"),"moneyRate":0.01},{label:L("Share it with the archive"),"fame":18,"memories":1}]},
 {id:"bank_error",title:L("The bank credited too much"),text:L("Your bank deposited a processing adjustment twice. Returning it promptly builds trust; waiting invites an uncomfortable call."),choices:[{label:L("Report the error today"),"fame":8,"stress":-3},{label:L("Wait for the bank to reconcile"),"stress":8}]},
 {id:"royalty_discovery",title:L("A forgotten licensing payment"),text:L("A publisher discovers your old licensed interview is due a payment. You can take cash or fund an expanded archive edition."),choices:[{label:L("Take the licensing payment"),"moneyRate":0.006},{label:L("Fund the archive edition"),"fame":12,"memories":1}]},
 {id:"class_settlement",title:L("A consumer settlement notice"),text:L("A past service provider offers compensation. Taking the standard payment is easy; contesting the amount has an uncertain outcome."),choices:[{label:L("Take the standard compensation"),"moneyRate":0.004},{label:L("Seek a larger settlement"),"costRate":0.002,"stress":6,"later":{"months":6,"amount":0.012,"chance":0.55,"fallback":0.004}}]},
 {id:"reward_lost_bag",title:L("A reward for a returned bag"),text:L("You return a bag containing important documents. Its owner offers a reward, or a thank-you at a public ceremony."),choices:[{label:L("Accept the reward privately"),"moneyRate":0.003,"stress":-3},{label:L("Accept the public thanks"),"fame":15,"memories":1}]},
 {id:"competition_prize",title:L("A city photography prize"),text:L("A photograph you submitted wins a prize. The organizer offers cash or a public exhibition of your work."),choices:[{label:L("Receive the cash prize"),"moneyRate":0.004,"memories":1},{label:L("Choose the public exhibition"),"fame":20,"memories":2}]},
 {id:"deposit_release",title:L("A forgotten travel deposit"),text:L("A travel agent locates an old refundable deposit. Collect it now or use it to join a small cultural excursion."),choices:[{label:L("Recover the deposit"),"moneyRate":0.003},{label:L("Join the cultural excursion"),"memories":2,"stress":-8}]},
 {id:"audit_rebate",title:L("An accounting fee rebate"),text:L("Your accounting firm overestimated its workload. It offers a rebate or an extra financial review at no additional cost."),choices:[{label:L("Take the fee rebate"),"moneyRate":0.002},{label:L("Request the financial review"),"stress":-12}]},
 {id:"unclaimed_bond",title:L("A matured bond in an old file"),text:L("A forgotten paper bond can be redeemed after verification. A broker will buy the claim immediately at a discount."),choices:[{label:L("Verify and redeem it"),"later":{"months":2,"amount":0.009,"chance":1}},{label:L("Sell the claim immediately"),"moneyRate":0.006}]},
 {id:"tenant_repair",title:L("Tenants report a leaking roof"),text:L("Tenants report water leaking during heavy rain. A thorough repair costs more; a temporary patch may mean another bill."),choices:[{label:L("Commission a full repair"),"costRate":0.01,"fame":10,"multiplier":1.05,"months":3},{label:L("Arrange a temporary patch"),"costRate":0.003,"stress":6,"later":{"months":3,"amount":-0.012,"chance":0.45,"fallback":0}}]},
 {id:"tenant_rooftop",title:L("A rooftop garden proposal"),text:L("Residents want a shared rooftop garden. It could attract visitors, but maintenance needs funding."),choices:[{label:L("Sponsor the garden"),"costRate":0.007,"fame":12,"multiplier":1.08,"months":4},{label:L("Let residents run a small pilot"),"fame":3,"stress":3}]},
 {id:"tenant_film_location",title:L("A film crew wants a location"),text:L("A film crew wants to rent one of your properties for a short shoot. Payment is attractive, but regular customers may be inconvenienced."),choices:[{label:L("Accept the filming contract"),"moneyRate":0.012,"stress":8,"multiplier":0.9,"months":1},{label:L("Protect the usual routine"),"fame":4,"stress":-3}]},
 {id:"tenant_pop_up",title:L("A weekend pop-up market"),text:L("Local makers ask to use your property for a weekend market. You can host a larger event or keep the schedule clear."),choices:[{label:L("Host the makers' market"),"costRate":0.004,"fame":8,"multiplier":1.12,"months":2},{label:L("Keep the existing schedule"),"stress":-4}]},
 {id:"tenant_energy",title:L("An energy efficiency upgrade"),text:L("A contractor proposes insulation upgrades. Upfront spending could improve operations after inspection."),choices:[{label:L("Approve the insulation work"),"costRate":0.009,"multiplier":1.1,"months":6,"stress":4},{label:L("Request an independent survey"),"costRate":0.002,"stress":-3}]},
 {id:"tenant_accessibility",title:L("An accessibility request"),text:L("Visitors ask for clearer access routes and ramps. You can make improvements or arrange personal assistance for now."),choices:[{label:L("Improve access facilities"),"costRate":0.008,"fame":18,"multiplier":1.05,"months":4},{label:L("Arrange staffed assistance"),"costRate":0.002,"fame":5}]},
 {id:"tenant_noise",title:L("A late-night noise dispute"),text:L("Residents complain about noise from a nearby venue. Soundproofing is expensive; mediation takes patience."),choices:[{label:L("Pay for soundproofing"),"costRate":0.007,"stress":-8,"fame":8},{label:L("Mediate a quieter schedule"),"stress":7,"fame":4}]},
 {id:"tenant_long_lease",title:L("A long-stay booking request"),text:L("A visiting team wants a long booking at a modest discount. Guaranteed occupancy competes with peak-season rates."),choices:[{label:L("Accept the discounted booking"),"moneyRate":0.008,"multiplier":0.95,"months":3,"stress":-5},{label:L("Hold out for peak-season guests"),"stress":5,"later":{"months":3,"amount":0.012,"chance":0.5,"fallback":0}}]},
 {id:"tenant_festival",title:L("A street festival at your door"),text:L("The city plans a street festival outside your properties. Promotion can boost sales; extra cleaning is the cheaper route."),choices:[{label:L("Run a festival promotion"),"costRate":0.005,"multiplier":1.2,"months":2,"fame":5},{label:L("Fund extra cleaning only"),"costRate":0.002,"fame":3}]},
 {id:"tenant_signage",title:L("A signage redesign offer"),text:L("A designer offers clearer signage for your buildings. A full redesign may bring attention, while a basic refresh is safer."),choices:[{label:L("Approve a full redesign"),"costRate":0.006,"multiplier":1.15,"months":3},{label:L("Refresh the existing signs"),"costRate":0.002,"multiplier":1.03,"months":2}]},
 {id:"business_coffee",title:L("A limited coffee shipment"),text:L("An importer offers a share of a specialty coffee shipment. Demand looks promising, but unsold stock would cut the payout."),choices:[{label:L("Back the shipment"),"costRate":0.012,"later":{"months":4,"amount":0.018,"chance":0.65,"fallback":0.006}},{label:L("Pass on the shipment"),"stress":-3}]},
 {id:"business_game",title:L("An indie game launch"),text:L("A small game studio seeks launch marketing funds. Strong reviews could repay the investment; a quiet release might return nothing."),choices:[{label:L("Fund the launch campaign"),"costRate":0.01,"stress":5,"later":{"months":6,"amount":0.028,"chance":0.35,"fallback":0}},{label:L("Try the demo and give feedback"),"memories":1,"stress":-3}]},
 {id:"business_food_truck",title:L("A food truck route expansion"),text:L("An operator with steady lunch sales wants another route. You can finance the launch or pay for a smaller demand test."),choices:[{label:L("Finance the new route"),"costRate":0.009,"later":{"months":5,"amount":0.014,"chance":0.7,"fallback":0.004}},{label:L("Fund a demand test"),"costRate":0.002,"fame":4}]},
 {id:"business_storage",title:L("A seasonal warehouse deal"),text:L("A logistics operator offers a short seasonal storage contract. Stock delays could reduce the final payment."),choices:[{label:L("Join the storage contract"),"costRate":0.015,"later":{"months":3,"amount":0.018,"chance":0.8,"fallback":0.01}},{label:L("Keep the cash liquid"),"stress":-4}]},
 {id:"business_music",title:L("A concert promoter's advance"),text:L("A promoter wants an advance for a small tour. Ticket sales decide whether your stake comes back with a premium."),choices:[{label:L("Advance the tour budget"),"costRate":0.008,"memories":1,"later":{"months":4,"amount":0.016,"chance":0.5,"fallback":0.002}},{label:L("Attend as a regular guest"),"costRate":0.001,"memories":1,"stress":-6}]},
 {id:"business_translation",title:L("A translation project contract"),text:L("A publisher needs money to translate a promising book. A signed distributor improves the odds, but sales remain uncertain."),choices:[{label:L("Finance the translated edition"),"costRate":0.006,"fame":5,"later":{"months":8,"amount":0.01,"chance":0.65,"fallback":0.002}},{label:L("Sponsor a sample chapter"),"costRate":0.001,"fame":4}]},
 {id:"business_recycling",title:L("A recycling pilot investment"),text:L("A local team is testing reusable packaging. A full pilot could pay off, while a donation helps without a return."),choices:[{label:L("Invest in the pilot"),"costRate":0.01,"fame":8,"later":{"months":9,"amount":0.017,"chance":0.55,"fallback":0.003}},{label:L("Donate testing supplies"),"costRate":0.002,"fame":10}]},
 {id:"business_catering",title:L("A catering expansion contract"),text:L("A caterer has booked several events but needs working capital. You can bridge the gap or decline the commitment."),choices:[{label:L("Provide working capital"),"costRate":0.012,"stress":4,"later":{"months":3,"amount":0.015,"chance":0.8,"fallback":0.006}},{label:L("Decline the commitment"),"stress":-4}]},
 {id:"business_documentary",title:L("A documentary distribution deal"),text:L("A finished documentary needs distribution funding. Its festival audience is enthusiastic, but commercial demand is untested."),choices:[{label:L("Back commercial distribution"),"costRate":0.007,"memories":1,"later":{"months":6,"amount":0.018,"chance":0.4,"fallback":0.001}},{label:L("Sponsor a public screening"),"costRate":0.002,"fame":12,"memories":1}]},
 {id:"business_furniture",title:L("A furniture maker's export order"),text:L("A furniture workshop won an export order. Customs delays are the main risk to its promised payment."),choices:[{label:L("Finance order production"),"costRate":0.014,"later":{"months":5,"amount":0.019,"chance":0.75,"fallback":0.008}},{label:L("Introduce another lender"),"fame":3,"stress":4}]},
 {id:"social_profile",title:L("A magazine cover interview"),text:L("A magazine wants a day-long profile. A public interview raises visibility, while privacy leaves you more time to rest."),choices:[{label:L("Give the cover interview"),"fame":20,"stress":10},{label:L("Keep a private schedule"),"stress":-8}]},
 {id:"social_award",title:L("An entrepreneurship award dinner"),text:L("You are invited to accept an award at a formal dinner. Preparing a speech takes effort, or you can send a short statement."),choices:[{label:L("Attend and give a speech"),"costRate":0.002,"fame":22,"memories":1,"stress":5},{label:L("Send a written acceptance"),"fame":6,"stress":-3}]},
 {id:"social_rumor",title:L("A misleading business rumor"),text:L("A rumor questions your financial stability. An independent statement can reassure people; silence lets speculation continue."),choices:[{label:L("Publish a verified clarification"),"costRate":0.004,"fame":8,"stress":-5},{label:L("Stay silent for now"),"fame":-12,"stress":10}]},
 {id:"social_mentor",title:L("A young founder asks for mentoring"),text:L("A founder asks for an afternoon of advice. You can mentor personally or support a wider workshop."),choices:[{label:L("Mentor the founder personally"),"fame":10,"stress":6},{label:L("Sponsor a practical workshop"),"costRate":0.003,"fame":16,"stress":-2}]},
 {id:"social_podcast",title:L("A podcast with difficult questions"),text:L("A popular host wants to discuss wealth and responsibility. An open conversation takes energy; a prepared statement is safer."),choices:[{label:L("Join the open conversation"),"fame":18,"stress":12},{label:L("Send a prepared statement"),"fame":4,"stress":2}]},
 {id:"social_sponsor",title:L("A celebrity sponsorship approach"),text:L("A celebrity proposes a joint charity campaign. A larger contribution attracts attention, while a modest donation stays quiet."),choices:[{label:L("Headline the campaign"),"costRate":0.01,"fame":28,"stress":6},{label:L("Make a quiet contribution"),"costRate":0.002,"fame":8,"stress":-4}]},
 {id:"social_apology",title:L("An assistant's public mistake"),text:L("An assistant sent an insensitive message under your name. Taking responsibility costs pride; blaming them can hurt your standing."),choices:[{label:L("Apologize and retrain the team"),"costRate":0.003,"fame":-4,"stress":5},{label:L("Blame the assistant publicly"),"fame":-20,"stress":12}]},
 {id:"social_alumni",title:L("An alumni scholarship appeal"),text:L("Your old school is building a scholarship pool. You can fund a place or visit students to share experience."),choices:[{label:L("Fund a scholarship place"),"costRate":0.006,"fame":20,"memories":1},{label:L("Visit for a career talk"),"fame":8,"stress":5}]},
 {id:"social_portrait",title:L("A photographer's portrait project"),text:L("A photographer wants to document city benefactors. You can commission a polished portrait or agree to a simple street photograph."),choices:[{label:L("Commission a formal portrait"),"costRate":0.003,"fame":12,"memories":1},{label:L("Join the street portrait series"),"fame":5,"memories":1,"stress":3}]},
 {id:"social_debate",title:L("A public debate invitation"),text:L("A forum invites you to discuss responsible investment. Personal participation boosts visibility; supporting the forum keeps your calendar free."),choices:[{label:L("Join the public debate"),"fame":16,"stress":10},{label:L("Support the forum's expenses"),"costRate":0.002,"fame":8,"stress":-3}]},
 {id:"travel_train",title:L("A last-minute sleeper train"),text:L("A cancellation opens a scenic train cabin. You could leave today or enjoy a quiet evening at home."),choices:[{label:L("Book the scenic journey"),"costRate":0.004,"memories":2,"stress":-15},{label:L("Enjoy an evening at home"),"stress":-7}]},
 {id:"travel_stranded",title:L("A storm interrupts a trip"),text:L("A storm cancels your return flight. An alternate route costs extra, while waiting turns the delay into an extended break."),choices:[{label:L("Buy an alternate route"),"costRate":0.006,"stress":-3},{label:L("Stay until the weather clears"),"costRate":0.002,"memories":1,"stress":8}]},
 {id:"travel_cooking",title:L("A chef's private cooking class"),text:L("A visiting chef offers a small cooking class. Joining costs money, while trying the recipe at home takes patience."),choices:[{label:L("Join the chef's class"),"costRate":0.003,"memories":2,"stress":-8},{label:L("Try the recipe at home"),"memories":1,"stress":2}]},
 {id:"travel_eclipse",title:L("A rare eclipse expedition"),text:L("A guide offers a trip to watch an eclipse. Clouds may spoil the view, but the journey itself would be memorable."),choices:[{label:L("Join the viewing expedition"),"costRate":0.005,"memories":2,"stress":-10},{label:L("Watch from the city park"),"memories":1,"stress":-3}]},
 {id:"travel_regatta",title:L("A regatta guest invitation"),text:L("A regatta organizer offers a guest package. You can pay for a guided day or watch from the public waterfront."),choices:[{label:L("Take the guided guest package"),"costRate":0.004,"fame":6,"memories":2,"stress":-6},{label:L("Watch from the waterfront"),"memories":1,"stress":-4}]},
 {id:"travel_retreat",title:L("A digital detox retreat"),text:L("A retreat asks guests to leave devices behind. Deep rest has a price; a phone-free weekend at home is simpler."),choices:[{label:L("Book the offline retreat"),"costRate":0.006,"stress":-25,"memories":1},{label:L("Switch off at home"),"stress":-12}]},
 {id:"travel_archaeology",title:L("An archaeology visitor program"),text:L("Researchers offer a guided visit to an excavation. A sponsored visit supports their work; a public lecture is free."),choices:[{label:L("Sponsor a field visit"),"costRate":0.004,"fame":8,"memories":2},{label:L("Attend the public lecture"),"memories":1,"stress":-4}]},
 {id:"travel_cancelled",title:L("A cancelled luxury booking"),text:L("Your hotel cancels a reservation and offers cash compensation or a more elaborate replacement stay."),choices:[{label:L("Take cash compensation"),"moneyRate":0.003,"stress":3},{label:L("Accept the replacement stay"),"memories":2,"stress":-10}]},
 {id:"travel_hiking",title:L("A mountain guide's open slot"),text:L("A trusted guide has space for a mountain walk. You can take the guided route or stay with an easy city stroll."),choices:[{label:L("Take the guided mountain walk"),"costRate":0.002,"memories":1,"stress":-14},{label:L("Take an easy city stroll"),"stress":-6}]},
 {id:"travel_jazz",title:L("A secret jazz performance"),text:L("A musician invites you to an intimate performance. Sponsoring the night helps the band, while buying a ticket keeps it simple."),choices:[{label:L("Sponsor the performance"),"costRate":0.004,"fame":10,"memories":2,"stress":-8},{label:L("Buy a regular ticket"),"costRate":0.001,"memories":1,"stress":-5}]},
 {id:"community_library",title:L("A library's missing books"),text:L("The neighborhood library needs updated books. A collection grant reaches many readers; volunteering takes only your time."),choices:[{label:L("Sponsor the new collection"),"costRate":0.004,"fame":16,"memories":1},{label:L("Volunteer for a reading session"),"fame":6,"stress":4,"memories":1}]},
 {id:"community_flood",title:L("Emergency shelter after flooding"),text:L("Heavy rain displaced local families. The shelter needs supplies, or volunteers to organize deliveries."),choices:[{label:L("Fund emergency supplies"),"costRate":0.008,"fame":24,"stress":-4},{label:L("Volunteer to organize deliveries"),"fame":10,"stress":10}]},
 {id:"community_playground",title:L("A safer playground appeal"),text:L("Parents ask for safer playground equipment. You can fund replacements or arrange a community repair day."),choices:[{label:L("Pay for safer equipment"),"costRate":0.006,"fame":18},{label:L("Organize a repair day"),"costRate":0.001,"fame":8,"stress":6}]},
 {id:"community_animals",title:L("An animal shelter food shortage"),text:L("An animal shelter is short of food this month. A supply grant helps immediately; a volunteer visit lifts the team's spirits."),choices:[{label:L("Cover the shelter's supplies"),"costRate":0.003,"fame":12,"stress":-5},{label:L("Visit as a volunteer"),"fame":5,"memories":1,"stress":2}]},
 {id:"community_trees",title:L("A street tree planting project"),text:L("Residents propose planting shade trees. A larger sponsorship funds more trees, while joining the planting day costs little."),choices:[{label:L("Sponsor a row of trees"),"costRate":0.005,"fame":15,"memories":1},{label:L("Join the planting day"),"costRate":0.001,"fame":6,"stress":-5}]},
 {id:"community_meals",title:L("A community kitchen appeal"),text:L("A community kitchen needs a month of ingredients. You can fund its pantry or help serve a busy meal."),choices:[{label:L("Stock the kitchen pantry"),"costRate":0.004,"fame":16,"stress":-3},{label:L("Help serve the meals"),"fame":7,"stress":5}]},
 {id:"community_science",title:L("A school science fair"),text:L("Students need equipment for a science fair. Sponsoring experiments could inspire a whole class; judging entries takes an afternoon."),choices:[{label:L("Sponsor experiment kits"),"costRate":0.003,"fame":14,"memories":1},{label:L("Judge the student projects"),"fame":6,"stress":4}]},
 {id:"community_history",title:L("A threatened local archive"),text:L("A local archive must digitize fragile records. You can fund preservation or help organize a volunteer scanning day."),choices:[{label:L("Fund digital preservation"),"costRate":0.005,"fame":18,"memories":1},{label:L("Organize volunteer scanning"),"fame":7,"stress":6}]},
 {id:"community_sports",title:L("A youth team's away tournament"),text:L("A youth sports team qualified for a tournament but cannot cover transport. A travel grant or fundraiser could help."),choices:[{label:L("Cover the team's transport"),"costRate":0.004,"fame":16,"memories":1},{label:L("Host a small fundraiser"),"costRate":0.001,"fame":8,"stress":5}]},
 {id:"community_water",title:L("A public drinking fountain"),text:L("Walkers ask for a drinking fountain in a busy park. You can finance installation or contribute to its planning."),choices:[{label:L("Finance the fountain"),"costRate":0.005,"fame":17,"stress":-2},{label:L("Join the planning committee"),"fame":5,"stress":5}]},
 {id:"incident_phishing",title:L("A suspicious payment request"),text:L("An email demands an urgent payment using a familiar company name. Independent verification costs time and expert help costs money."),choices:[{label:L("Hire a security specialist"),"costRate":0.002,"stress":-8},{label:L("Verify through known contacts"),"stress":6}]},
 {id:"incident_luggage",title:L("A suitcase lost in transit"),text:L("Your suitcase disappears between transfers. Insurance may reimburse replacements, or you can travel with the essentials."),choices:[{label:L("Replace the missing essentials"),"costRate":0.003,"stress":4,"later":{"months":2,"amount":0.002,"chance":0.85,"fallback":0}},{label:L("Make do with a light kit"),"stress":10,"memories":1}]},
 {id:"incident_lawsuit",title:L("A contract dispute escalates"),text:L("A service contract dispute reaches mediation. A fixed settlement ends it now, while legal review could reduce the cost or add a bill."),choices:[{label:L("Agree to a fixed settlement"),"costRate":0.008,"stress":-6},{label:L("Commission a legal review"),"costRate":0.003,"stress":10,"later":{"months":4,"amount":-0.015,"chance":0.35,"fallback":0}}]},
 {id:"incident_hail",title:L("Hail damages outdoor equipment"),text:L("A hailstorm damaged outdoor equipment. Durable replacements cost more; patching it is cheaper but less reliable."),choices:[{label:L("Replace with durable equipment"),"costRate":0.007,"stress":-5},{label:L("Patch the damaged equipment"),"costRate":0.002,"stress":5,"later":{"months":3,"amount":-0.008,"chance":0.4,"fallback":0}}]},
 {id:"incident_identity",title:L("An impersonator uses your name"),text:L("A fake account is promoting a questionable deal in your name. A quick public notice helps; a quiet report takes longer."),choices:[{label:L("Issue a public warning"),"costRate":0.002,"fame":6,"stress":4},{label:L("File a quiet platform report"),"fame":-6,"stress":10}]},
 {id:"incident_staff",title:L("A key assistant needs leave"),text:L("A key assistant needs sudden family leave. Temporary cover costs money; doing the coordination yourself adds pressure."),choices:[{label:L("Hire temporary cover"),"costRate":0.004,"fame":8,"stress":-3},{label:L("Coordinate the work yourself"),"stress":14,"fame":3}]},
 {id:"incident_power",title:L("A power outage disrupts bookings"),text:L("An outage disrupts visitors and bookings. Backup arrangements can soften the impact, while waiting is cheaper."),choices:[{label:L("Arrange backup services"),"costRate":0.005,"multiplier":0.95,"months":1,"fame":6},{label:L("Wait for the grid to recover"),"multiplier":0.8,"months":1,"stress":10}]},
 {id:"incident_data",title:L("A corrupted archive drive"),text:L("A personal archive drive failed. Professional recovery might restore it; rebuilding a smaller album would create new memories."),choices:[{label:L("Pay for professional recovery"),"costRate":0.003,"stress":-5},{label:L("Rebuild a family album"),"memories":1,"stress":6}]},
 {id:"incident_counterfeit",title:L("A counterfeit collectible offer"),text:L("A dealer offers a bargain collectible without clear provenance. Verification costs money; walking away protects your peace of mind."),choices:[{label:L("Commission independent authentication"),"costRate":0.002,"stress":3,"later":{"months":2,"amount":0.005,"chance":0.5,"fallback":0}},{label:L("Walk away from the offer"),"stress":-6}]},
 {id:"incident_event_cancel",title:L("A supplier cancels your gathering"),text:L("A supplier cancels just before your gathering. A replacement saves the occasion; postponing keeps the budget intact."),choices:[{label:L("Book an urgent replacement"),"costRate":0.004,"memories":1,"fame":5,"stress":6},{label:L("Postpone the gathering"),"fame":-4,"stress":8}]},
 {id:"rival_joint_bid",title:L("The rival suggests a joint bid"),text:L("Your rival proposes sharing a supply contract bid. A joint stake can pay off, but cooperation has no guarantee."),choices:[{label:L("Join the rival's bid"),"costRate":0.015,"stress":6,"later":{"months":6,"amount":0.024,"chance":0.6,"fallback":0.005}},{label:L("Maintain your independence"),"fame":6,"stress":-3}]},
 {id:"rival_truce",title:L("A rival's dinner truce"),text:L("The rival invites you to talk over dinner. You can host a generous meeting or send a courteous written reply."),choices:[{label:L("Host a conciliatory dinner"),"costRate":0.003,"fame":10,"stress":-10,"memories":1},{label:L("Send a courteous reply"),"fame":3,"stress":-2}]},
 {id:"rival_poaching",title:L("The rival approaches your team"),text:L("The rival is courting members of your service team. Retention support costs money; a conversation takes your attention."),choices:[{label:L("Fund a retention package"),"costRate":0.008,"fame":8,"multiplier":1.08,"months":3},{label:L("Discuss career goals personally"),"stress":10,"multiplier":0.95,"months":2}]},
 {id:"rival_charity_match",title:L("The rival offers matching donations"),text:L("The rival will match your contribution to a public relief drive. A joint pledge gains attention; staying private keeps the event smaller."),choices:[{label:L("Make a joint public pledge"),"costRate":0.007,"fame":26,"stress":4},{label:L("Make a separate small donation"),"costRate":0.002,"fame":9,"stress":-3}]},
 {id:"rival_tip",title:L("The rival offers market research"),text:L("The rival offers a share of a commissioned market study. Buying access may improve promotion; relying on public data is slower."),choices:[{label:L("Buy access to the study"),"costRate":0.004,"multiplier":1.1,"months":3},{label:L("Study public data yourself"),"stress":7,"multiplier":1.03,"months":2}]},
 {id:"rival_public_challenge",title:L("The rival issues a public challenge"),text:L("The rival challenges you to sponsor a city innovation contest. Joining shows confidence, while ignoring the spectacle protects your time."),choices:[{label:L("Sponsor the innovation contest"),"costRate":0.01,"fame":24,"stress":8},{label:L("Leave the spectacle to the rival"),"fame":-5,"stress":-8}]},
 {id:"rival_surplus",title:L("The rival sells surplus supplies"),text:L("The rival offers discounted surplus equipment through a broker. Reselling could earn a margin, but buyers are uncertain."),choices:[{label:L("Buy the resale lot"),"costRate":0.01,"later":{"months":3,"amount":0.016,"chance":0.6,"fallback":0.006}},{label:L("Decline the surplus lot"),"stress":-4}]},
 {id:"rival_speaking",title:L("A stage shared with the rival"),text:L("An organizer invites both of you to a public conversation. You can keep it constructive or turn it into a competitive spectacle."),choices:[{label:L("Discuss shared city goals"),"fame":14,"stress":4},{label:L("Make a flashy competitive appearance"),"costRate":0.005,"fame":20,"stress":14}]},
 {id:"rival_referral",title:L("A referral from your rival"),text:L("The rival refers an overflow visitor group to you. A welcome package can lift revenue, or you can decline the extra work."),choices:[{label:L("Prepare a welcome package"),"costRate":0.003,"multiplier":1.18,"months":2,"stress":5},{label:L("Decline the overflow visitors"),"stress":-6}]},
 {id:"rival_disputed_story",title:L("A disputed story about the rival"),text:L("A reporter asks you to comment on an unverified story about the rival. Restraint protects trust; speculation brings pressure."),choices:[{label:L("Ask for verified facts first"),"fame":8,"stress":-3},{label:L("Comment on the speculation"),"fame":-12,"stress":10}]},
 {id:"economy_convention",title:L("An unexpected business convention"),text:L("A business convention moves to the city at short notice. Promotion could capture demand, while ordinary operations still benefit."),choices:[{label:L("Launch convention packages"),"costRate":0.006,"multiplier":1.25,"months":3},{label:L("Keep ordinary operations"),"multiplier":1.08,"months":2}]},
 {id:"economy_heatwave",title:L("A prolonged summer heatwave"),text:L("Hot weather changes visitor habits. Cooling arrangements cost money; shorter service hours reduce both strain and revenue."),choices:[{label:L("Fund extra cooling arrangements"),"costRate":0.005,"multiplier":0.98,"months":2,"fame":6},{label:L("Shorten service hours"),"multiplier":0.85,"months":2,"stress":-6}]},
 {id:"economy_transport",title:L("A temporary transit closure"),text:L("Transit repairs make visits harder this month. Shuttle support preserves demand; waiting cuts spending."),choices:[{label:L("Arrange visitor shuttles"),"costRate":0.004,"multiplier":0.98,"months":2,"fame":5},{label:L("Wait for transit to reopen"),"multiplier":0.8,"months":2,"stress":5}]},
 {id:"economy_exchange",title:L("A currency exchange promotion"),text:L("A travel exchange service offers a short promotional deposit. A higher locked payout competes with an immediate cash reward."),choices:[{label:L("Use the promotional deposit"),"costRate":0.01,"later":{"months":3,"amount":0.0115,"chance":1}},{label:L("Take the small cash reward"),"moneyRate":0.001}]},
 {id:"economy_supply",title:L("A shortage of everyday supplies"),text:L("Suppliers warn of a temporary shortage. Securing inventory costs extra; waiting risks slower visitor service."),choices:[{label:L("Secure essential inventory"),"costRate":0.006,"multiplier":0.98,"months":3},{label:L("Wait for normal supply"),"multiplier":0.88,"months":3,"stress":7}]},
 {id:"economy_workcation",title:L("A wave of remote-work visitors"),text:L("Remote workers are choosing longer city stays. A targeted campaign could bring more bookings than a basic welcome."),choices:[{label:L("Promote extended-stay packages"),"costRate":0.005,"multiplier":1.2,"months":4},{label:L("Offer basic visitor information"),"multiplier":1.05,"months":2}]},
 {id:"economy_flight_return",title:L("An air route returns"),text:L("An airline restores a route to your city. Launch advertising could capture visitors, while organic demand grows more slowly."),choices:[{label:L("Advertise to returning visitors"),"costRate":0.004,"multiplier":1.18,"months":3},{label:L("Welcome the gradual recovery"),"multiplier":1.06,"months":2,"stress":-3}]},
 {id:"economy_rainy",title:L("An unusually rainy season"),text:L("Persistent rain is keeping visitors indoors. Indoor activities cost money, while a quieter season offers a chance to rest."),choices:[{label:L("Organize indoor activities"),"costRate":0.004,"multiplier":1.05,"months":2,"stress":4},{label:L("Accept a quieter season"),"multiplier":0.9,"months":2,"stress":-8}]},
 {id:"economy_city_guide",title:L("The city enters a travel guide"),text:L("A respected guide features the city. A coordinated welcome could amplify the attention; doing nothing still brings some visitors."),choices:[{label:L("Coordinate a city welcome"),"costRate":0.006,"fame":8,"multiplier":1.22,"months":3},{label:L("Enjoy the organic attention"),"multiplier":1.08,"months":2}]},
 {id:"economy_cancellation",title:L("A major festival is cancelled"),text:L("A cancelled festival leaves visitors unsure about their plans. Alternative packages can soften the revenue hit."),choices:[{label:L("Offer alternative packages"),"costRate":0.005,"multiplier":0.95,"months":2,"fame":5},{label:L("Accept the cancellations"),"multiplier":0.75,"months":2,"stress":8}]},
];

// Property stories need an owned rental or lodging building. Other cards need no new save fields.
export const CHANCE_EVENTS=CHANCE_CARDS.map(({choices,...card})=>({...card,
 ...(card.id.startsWith('tenant_')?{when:s=>s.tiles.some(t=>t.owner==='player'&&['condo','rental','office','hotel','resort'].includes(t.type))}:{}),
 build:(s,c)=>choices.map(choice=>buildChoice(choice,c.wealth,card.title))
}));
