import {TYPES,assetValue,assetSaleReport,developmentQuote,canBuild,assetLandValue,buildingArea,buildingAnnualGrowth,footprintCells,parcelQuote,coords,OFF_ROAD,BOULEVARD} from './engine.js';
import {propertyPartyPanel} from './reputation.js';
const money=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
export function assetSummary(s,i,report){
 const t=s.tiles[i],value=assetValue(s,i),land=t.tenure==='buy'?assetLandValue(s,i):t.deposit||0,rental=['rental','condo','office'].includes(t.type);
 const row=(label,value,cls='')=>`<div class="data-row"><span>${label}</span><b class="${cls}">${value}</b></div>`;
 return `<section class="asset-profit" aria-label="현재 가격과 월 수익">${row('도로 접근',report.loc.boulevard?'대로변 · 토지가 +50% · 임대료 +30%':report.loc.access?'도로변':'비도로변 · 매출 '+Math.round(OFF_ROAD.revenue*100)+'% 적용')}${row('부지 면적',buildingArea(t)+'칸')}${row('건물 가치 연 상승률',(buildingAnnualGrowth(t)*100).toFixed(0)+'%')}${row('현재 가격 · 매각 평가액',money(value))}${row(t.tenure==='buy'?'토지 평가액':'반환 보증금',money(land))}${row('건물·시설 평가액',money(Math.max(0,value-land)))}${row(rental?'예상 월 임대료 수입':'예상 월 매출',money(report.revenue))}${row('월 운영비 합계','−'+money(report.cost))}${['rental','condo'].includes(t.type)?row('예상 입주율',report.occupancy+'%'):''}${row('예상 월 순수익',money(report.profit),report.profit>=0?'positive':'negative')}</section><p class="help">현재 가격은 지금 매각할 때 받는 금액입니다. 월 수익은 현재 입지와 운영 설정 기준이며 개인 생활비·대출 이자는 제외합니다.</p>${t.tenure==='buy'&&t.type!=='atelier'?`<details><summary>부지를 합쳐 새 건물 짓기</summary><p>주변 부지와 최대 9칸으로 통합합니다. 포함된 내 시설은 철거되고 새 건물로 교체됩니다.</p><div class="button-row">${['hotel','office','resort','rental','condo','cafe'].map(type=>`<button data-redevelop="${type}">${TYPES[type].name}</button>`).join('')}</div></details>`:''}`;
}
export function constructionContract(s,i,type,footprint={width:1,height:1}){
 const d=TYPES[type],q=developmentQuote(s,i,type,1,footprint),reason=canBuild(s,i,type,'buy',footprint),cells=footprintCells(i,footprint);
 const acquisitions=cells.map(j=>({j,t:s.tiles[j],q:parcelQuote(s,j)})).filter(({t,q})=>t.type&&t.owner==='npc'&&q);
 const removed=cells.filter(j=>s.tiles[j].owner==='player'&&s.tiles[j].type!=='plot');
 const options=value=>[1,2,3].map(n=>`<option value="${n}" ${n===value?'selected':''}>${n}칸</option>`).join('');
 return `<span class="eyebrow">${q.label} · 유동인구 ${q.loc.footfall}/100</span><h2>${d.icon||''} ${d.name} 통합 건설</h2><p>${q.loc.boulevard?`대로변 · 토지가 +${Math.round((BOULEVARD.land-1)*100)}% · 주택·아파트·빌딩 임대료 +${Math.round((BOULEVARD.rent-1)*100)}%`:q.loc.access?'도로변 · 기본 건축비와 매출 적용':`비도로변 · 완공 시 빈 땅을 따라 도로가 무료로 자동 연결됩니다. 통로가 없으면 비도로변으로 운영됩니다. 연결 전 기준으로 도로변 대비 토지가 ${Math.round(OFF_ROAD.land*100)}%, 건축비 ${Math.round(OFF_ROAD.construction*100)}%, 예상 매출 ${Math.round(OFF_ROAD.revenue*100)}% 적용. 유지비는 동일하며 도로가 연결되면 매출이 회복됩니다.`}</p><div class="field-grid"><label>부지 가로<select data-footprint="width">${options(footprint.width)}</select></label><label>부지 세로<select data-footprint="height">${options(footprint.height)}</select></label></div><p>선택한 칸을 기준으로 오른쪽·아래 방향의 ${footprint.width}×${footprint.height}, 총 ${footprint.width*footprint.height}칸을 사용합니다.</p><div style="display:grid;grid-template-columns:repeat(${footprint.width},1fr);gap:6px">${cells.map(j=>{const t=s.tiles[j],p=coords(j);return `<div style="padding:8px;border:1px solid #bacbb5;border-radius:6px;font-size:12px">${p.x+1}, ${p.y+1}<br>${t.terrain==='water'?'강':t.type?TYPES[t.type].name:'빈 땅'}<br>${t.owner==='player'?'내 자산':t.type==='extension'?'통합 건물 일부':t.type?'기존 시설':'토지 매입 예정'}</div>`;}).join('')}</div>${acquisitions.length?`<h3>먼저 매입할 기존 건물</h3><div class="new-options">${acquisitions.map(({j,t,q})=>`<button data-acquire-parcel="${j}" ${s.mode!=='sandbox'&&s.money<q.total?'disabled':''}>${TYPES[t.type].name} · 토지 포함 ${money(q.total)} 매입</button>`).join('')}</div><p>건물 매입 후 아래 토지비와 총액이 갱신됩니다.</p>`:''}<div class="asset-profit"><p>건축비 <b>${money(q.construction)}</b></p><p>미소유 토지비 <b>${money(q.land)}</b></p><h3>건설 계약 ${money(q.total)}</h3><p>예상 월 매출 ${money(q.revenue)} − 운영비 ${money(q.cost)}</p><strong class="${q.profit>=0?'positive':'negative'}">예상 월 순수익 ${money(q.profit)}</strong></div><p class="help">같은 입지의 1칸 대비 건축비 ${Math.pow(q.area,1.05).toFixed(2)}배 · 매출 ${Math.pow(q.area,1.3).toFixed(2)}배 · 건물 평가액 연 ${(buildingAnnualGrowth({footprint})*100).toFixed(0)}% 상승.<br>현재 보유 현금 ${money(s.money)}. 초기 건물 평가는 건축비의 70% × 면적의 0.15제곱입니다.</p>${removed.length?`<p><b>재건축 시 내 기존 시설 ${removed.length}곳을 철거합니다.</b> 기존 매입·확장 투자금은 새 자산의 투자 기록에 합산되며 철거 보상금은 없습니다.</p>`:''}<button class="primary full" data-contract="buy" ${reason?'disabled':''}>${reason||`${q.area}칸에 ${removed.length?'철거 후 ':''}건설하기`}</button>${q.area===1&&d.group==='business'&&!s.tiles[i].type?`<button class="full" data-contract="lease" ${canBuild(s,i,type,'lease')?'disabled':''}>1칸 임차 창업 · ${money(q.construction+Math.round(q.land*.2))}</button>`:''}<p class="help">${s.mode==='sandbox'?'자유 실험: 매입·건설 비용 차감 없음.':'매입과 건설은 별도 계약입니다. 매입한 건물은 건설을 취소해도 내 자산으로 남습니다.'} 월 수익은 현재 입지 기준으로 변동됩니다.</p>`;
}
export function constructionDialog(s,i,report){const sale=assetSaleReport(s,i),gainLabel=sale.gain<0?'예상 매각 손실':sale.gain>0?'예상 매각 이익':'예상 매각 손익',gainSign=sale.gain<0?'−':'+',roi=sale.roi===null?'산정 불가':`${sale.roi>=0?'+':''}${sale.roi.toFixed(1)}%`;const t=s.tiles[i],d=TYPES[t.type],q=developmentQuote(s,i,t.type,t.level),cost=Math.round((t.constructionCost??d.cost)*.8*t.level);return `<span class="eyebrow">MY BUILDING · Lv.${t.level}</span><h2>${d.icon} 나의 ${d.name}</h2>${t.type==='office'?'<p><b>원금 보전 매각</b> · 총 투자금(토지·건설·확장) 이상으로 매각할 수 있어요.</p>':''}<p>${q.label} · 유동인구 ${q.loc.footfall}/100${q.waterfront?' · 강변':''}. 수익은 매달 자동 입금됩니다.</p>${assetSummary(s,i,report)}${propertyPartyPanel(s,i)}<section aria-label="지금 매각하면" style="margin:16px 0;padding:16px;border:1px solid ${sale.gain<0?'#dfb9a8':'#b8cdb7'};border-radius:10px;background:${sale.gain<0?'#fff3ed':'#eef4e8'}"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;font-size:14px"><b>지금 매각하면${sale.estimated?' · 추정':''}</b><span>받는 금액 <b>${money(sale.value)}</b></span></div><div style="display:flex;justify-content:space-between;gap:12px;align-items:baseline;flex-wrap:wrap;margin-top:12px;color:${sale.gain<0?'#a23f24':'#315f4f'}"><span style="font-size:14px">${gainLabel}</span><strong style="font-size:24px;overflow-wrap:anywhere">${gainSign}${money(Math.abs(sale.gain))} <span style="font-size:18px">(${roi})</span></strong></div><p style="font-size:13px;line-height:1.6;margin:10px 0 0">최초 투자금 ${money(sale.initial)} 대비 · 확장 비용 제외<br>확장비 포함 총 투자금 ${money(sale.invested)}<br>월 운영 수익은 제외한 매각 차익입니다.${sale.estimated?'<br>이전 저장의 매입 기록이 없어 투자금과 손익은 추정치입니다.':''}</p></section><div class="meter"><i style="width:${t.level/3*100}%"></i></div><p>${t.level<3?`확장하면 월 수익 +${money(report.profit/t.level)}!`:'최대 확장 완료! 다음 부지에 새 건물을 지어보세요.'}</p><div class="button-row"><button class="primary" data-action="upgrade" ${t.level>=3||s.mode!=='sandbox'&&s.money<cost?'disabled':''}>${t.level>=3?'Lv.3 완성':'확장하기 · '+money(cost)}</button><button data-action="sell">건물 매각</button></div><p class="help">보유 현금 ${money(s.money)} · 매각 가치 ${money(assetValue(s,i))}<br>수익으로 새 건물을 짓거나 ‘돈이 돈을 벌어요’에서 재투자하세요.</p>`;}
