import {marketPrice} from './economy.js';
import {validMansion,mansionDesign,mansionMaintenance} from './mansion.js';
import {photoGallery} from './collection-photos.js';
import {VEHICLES,ownedModels,validVehicles,vehicleMaintenance} from './luxury-models.js';
export const FLEX_ITEMS={
 sportscar:{name:'Sunset Sports Car',icon:'🏎',price:8000,unlock:20000,description:'Your character drives a gold sports car around the map.'},
 penthouse:{name:'Riverview Mansion',icon:'🏛',price:35000,unlock:100000,description:'A grand residence with a pool and garden. It appears in the showroom and on the southwest map.'},
 yacht:{name:'Riverside Yacht',icon:'🛥',price:90000,unlock:300000,description:'Your private yacht appears in the showroom and on the neighborhood river.'}
};
export const flexState=s=>s.flex??{owned:[],lastParty:-1};
export function validFlex(s){const f=s.flex;return f===undefined||!!(f&&Array.isArray(f.owned)&&validVehicles(s)&&f.owned.every(id=>Object.hasOwn(FLEX_ITEMS,id))&&new Set(f.owned).size===f.owned.length&&(f.mansion===undefined||(f.owned.includes('penthouse')&&validMansion(f.mansion)))&&Number.isInteger(f.lastParty)&&f.lastParty>=-1&&f.lastParty<=s.month);}
export function flexQuote(s,wealth,id){const item=FLEX_ITEMS[id];if(!item)return'No collection item selected.';if(flexState(s).owned.includes(id))return'You already own this collection item.';if(s.mode!=='sandbox'&&Math.max(s.highestWealth,wealth)<item.unlock)return`Unlocks at a peak net worth of ₲${item.unlock.toLocaleString('en-US')}`;if(s.money<marketPrice(s,item.price))return'Not enough cash to buy.';return null;}
export function buyFlex(s,wealth,id){const error=flexQuote(s,wealth,id);if(error)return{ok:false,msg:error};const item=FLEX_ITEMS[id];s.flex??={owned:[],lastParty:-1};s.highestWealth=Math.max(s.highestWealth,wealth);s.money-=marketPrice(s,item.price);s.flex.owned.push(id);if(s.concept==='rich-life')s.prestige=Math.max(0,(s.prestige||0)+10);s.log.unshift(`✦ ${item.name} purchased · added to my collection!${s.concept==='rich-life'?' · Reputation +10':''}`);s.log=s.log.slice(0,25);return{ok:true,msg:item.name+' · It is mine now!'};}
export function hostParty(s){if(!flexState(s).owned.length)return{ok:false,msg:'Get one collection item and you can host a party.'};if(flexState(s).lastParty===s.month)return{ok:false,msg:'You already hosted a party this month.'};if(s.money<500)return{ok:false,msg:'A party costs ₲500.'};s.money-=500;s.stress=Math.max(0,s.stress-20);s.flex.lastParty=s.month;if(s.concept==='rich-life')s.prestige=Math.max(0,(s.prestige||0)+3);s.log.unshift('🥂 Flex party with friends · Stress −20'+(s.concept==='rich-life'?' · Reputation +3':''));s.log=s.log.slice(0,25);return{ok:true,msg:'Drinks are on me! Stress −20'};}
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
export function flexScene(s){return photoGallery(s);}
export function flexDialog(s,a){
 const f=flexState(s),partyReason=!f.owned.length?'Unlocks after your first collection buy':f.lastParty===s.month?'Party done this month':s.money<500?'Needs ₲500 cash':'';
 const carCost=ownedModels(s,'sportscar').reduce((sum,id)=>sum+vehicleMaintenance(VEHICLES.sportscar.find(model=>model.id===id),'sportscar'),0);
 const yachtCost=ownedModels(s,'yacht').reduce((sum,id)=>sum+vehicleMaintenance(VEHICLES.yacht.find(model=>model.id===id),'yacht'),0);
 const homeCost=f.owned.includes('penthouse')?mansionMaintenance(mansionDesign(s)):0;
 return `<span class="eyebrow">THE GOOD LIFE</span><h2>You earned it. Now enjoy it.</h2><p>My car, my home, my yacht. Turn money saved up into a view of your own.</p><div class="button-row"><button data-action="cars">Compare 5 sports cars →</button><button data-action="yachts">Compare 5 yachts →</button></div>${flexScene(s)}<div class="flex-summary"><b>COLLECTION ${f.owned.length} / 3</b><span>Cash on hand ${money(s.money)}</span></div><div class="flex-grid">${Object.entries(FLEX_ITEMS).map(([id,d])=>{const owned=f.owned.includes(id);return `<section class="flex-item ${owned?'owned':''}"><span class="flex-icon">${d.icon}</span><small>${owned?'✦ MY COLLECTION':'Peak net worth '+money(d.unlock)}</small><h3>${d.name}</h3><p>${d.description}</p><strong>${id==='sportscar'?money(marketPrice(s,80000))+' and up':id==='yacht'?money(marketPrice(s,90000))+' and up':'Quoted by design'}</strong><button ${id==='sportscar'?'data-action="cars"':id==='yacht'?'data-action="yachts"':'data-action="mansion-design"'}>${id==='penthouse'?'Design Mansion':'Choose from 5 models'}</button></section>`;}).join('')}</div>${f.owned.includes('penthouse')?'<button data-action="flex-home" class="primary full">🏛 Visit my mansion →</button>':''}<button data-action="mansion-design" class="primary full">✎ Design my own mansion →</button><div class="flex-party"><div><h3>🥂 Drinks on me</h3><p>Once a month · ₲500 · Stress −20 (min 0)</p></div><button data-action="flex-party" ${partyReason?'disabled':''}>${partyReason||'Host Flex Party'}</button></div><p class="help">Monthly upkeep now: mansion ${money(homeCost)} · sports cars ${money(carCost)} · yachts ${money(yachtCost)}. Upkeep applies to every model you own, and purchases stay in your collection.</p>`;
}
