import {RICH_GOALS} from './rich-life.js';
import {compoundSummary} from './compound.js';
import {TYPES,MILESTONES,assetValue} from './engine.js';
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function growthModel(s,a){
 const stages=s.concept==='rich-life'?RICH_GOALS:MILESTONES;
 const baseline=s.startingWealth||12000,previous=s.history.length>1?s.history.at(-2).wealth:baseline;
 const points=[{month:0,wealth:baseline},...s.history.filter(h=>h.month<s.month),{month:s.month,wealth:a.wealth}];
 if(s.month===0)points.splice(0,points.length,{month:0,wealth:baseline},{month:0,wealth:a.wealth});
 const tier=stages.filter(m=>a.wealth>=m.wealth).length,next=stages[tier];
 const buckets=[{name:'Cash',value:Math.max(0,s.money),color:'#d9b359'},{name:'Property',value:a.assets,color:'#7ba58c'},{name:'Stocks',value:a.stocks,color:'#739fbd'},{name:'Inventory',value:a.inventory,color:'#b998bd'},{name:'Compound assets',value:compoundSummary(s).assets,color:'#438363'},{name:'Owner equity · art',value:(a.empire?.assets||0)+(a.art?.value||0),color:'#b39961'}];
 return{stages,baseline,delta:a.wealth-baseline,monthly:a.wealth-previous,tier,next,points,buckets,gross:buckets.reduce((n,b)=>n+b.value,0),label:[s.concept==='rich-life'?'Super Rich':'Building seed money',...stages.map(m=>m.name)][tier],royalties:(s.projects||[]).filter(p=>p.status==='earning').length};
}
function skyline(s,a){const owns=a.owned.filter(({t})=>t.type!=='plot').slice(0,9),width=640,base=164;let shapes='';
 const cashLevels=Math.min(12,Math.max(0,Math.floor(s.money/1000)));
 for(let n=0;n<cashLevels;n++){const x=34+(n%3)*23,y=base-Math.floor(n/3)*10;shapes+=`<ellipse cx="${x}" cy="${y}" rx="13" ry="5" fill="#b08b3f"/><ellipse cx="${x}" cy="${y-3}" rx="13" ry="5" fill="#edce78"/>`;}
 shapes+='<text x="56" y="193" text-anchor="middle">Cash</text>';
 if(!owns.length)shapes+='<path d="M129 160h270" stroke="#bcc9b6" stroke-dasharray="5 5"/><text x="267" y="145" text-anchor="middle" fill="#81917c">Where your first shop and workshop will stand</text>';
 owns.forEach(({t},n)=>{const x=120+n*32,w=27,h=27+t.level*22,col=TYPES[t.type].color;shapes+=`<g><rect x="${x}" y="${base-h}" width="${w}" height="${h}" rx="3" fill="${col}"/><path d="M${x+w} ${base-h}l8 7v${h-7}h-8z" fill="#456552"/><rect x="${x+4}" y="${base-h-5}" width="19" height="5" fill="#d9b76d"/>${Array.from({length:t.level+1},(_,k)=>`<path d="M${x+5} ${base-h+10+k*12}h5m7 0h5" stroke="#fff5c9" stroke-width="5"/>`).join('')}<title>${esc(TYPES[t.type].name)} · Level ${t.level}</title></g>`;});
 shapes+=`<text x="267" y="193" text-anchor="middle">My spaces ${a.owned.length}${a.owned.length>9?' · top 9':''}</text>`;
 const shares=Object.values(s.holdings).reduce((n,v)=>n+v,0),certs=shares?Math.min(5,1+Math.floor(shares/20)):0;
 for(let n=0;n<certs;n++)shapes+=`<rect x="${453+n*4}" y="${125-n*6}" width="45" height="35" rx="3" fill="#d7e6ed" stroke="#7599b0"/><path d="M${461+n*4} ${149-n*6}l8-6 8 2 12-12" fill="none" stroke="#52829d" stroke-width="2"/>`;
 shapes+=`<text x="478" y="193" text-anchor="middle">Stocks ${shares}</text>`;
 const books=(s.projects||[]).filter(p=>p.status==='earning').length;for(let n=0;n<Math.min(7,books);n++)shapes+=`<rect x="${548+n*7}" y="${130-n%3*7}" width="6" height="${34+n%3*7}" rx="1" fill="${['#b08ba6','#bda05b','#7fa795'][n%3]}"/>`;
 shapes+=`<text x="574" y="193" text-anchor="middle">Earning works ${books}</text>`;
 return `<svg class="wealth-scene" viewBox="0 0 ${width} 210" role="img" aria-label="Cash on hand ${money(s.money)}, ${a.owned.length} spaces, ${shares} shares, ${books} earning works"><defs><linearGradient id="wealthSky" x2="0" y2="1"><stop stop-color="#edf3e5"/><stop offset="1" stop-color="#f8f5e9"/></linearGradient></defs><rect width="640" height="210" rx="16" fill="url(#wealthSky)"/><circle cx="556" cy="42" r="20" fill="#eddaa0"/><path d="M0 166Q180 145 320 162T640 160V210H0" fill="#dce6cf"/><g font-family="sans-serif" font-size="11" fill="#4b6451">${shapes}</g></svg>`;
}
function chart(g){const p=g.points,values=p.map(p=>p.wealth),lo=Math.min(...values),hi=Math.max(...values),range=Math.max(100,hi-lo),coords=p.map((point,i)=>[18+(p.at(-1).month?point.month/p.at(-1).month:i/Math.max(1,p.length-1))*594,99-(point.wealth-lo)/range*75]),line=coords.map(p=>p.join(',')).join(' '),color=g.delta>=0?'#477f60':'#b96856';return `<svg class="wealth-chart" viewBox="0 0 630 135" role="img" aria-label="Starting net worth ${money(g.baseline)}, now ${money(p.at(-1).wealth)}. Month-end records and the current valuation trend"><path d="M18 99H612" stroke="#d4ddcc"/><polygon points="18,100 ${line} 612,100" fill="${color}15"/><polyline points="${line}" fill="none" stroke="${color}" stroke-width="3"/>${coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="3" fill="${color}"><title>Month ${p[i].month} · ${money(p[i].wealth)}</title></circle>`).join('')}<text x="18" y="124">Start ${money(g.baseline)}</text><text x="612" y="124" text-anchor="end">Now ${money(p.at(-1).wealth)}</text></svg>`;}
export function growthCard(s,a){const g=growthModel(s,a);return `<button class="wealth-card" data-action="growth"><span class="wealth-caption">MY GROWTH <b>${g.label}</b></span>${skyline(s,a)}<span class="wealth-caption"><b class="${g.delta>=0?'positive':'negative'}">vs. start ${g.delta>=0?'+':''}${money(g.delta)}</b><span>See my growth ↗</span></span></button>`;}
export function growthDialog(s,a){const g=growthModel(s,a);return `<span class="eyebrow">MY WEALTH, TAKING SHAPE</span><h2>My wealth becomes a landscape.</h2><p>Buy a shop and a building appears, collect stocks and certificates stack up, earn from a creative work and the shelf fills.</p>${skyline(s,a)}<div class="wealth-numbers"><div><small>Net worth now</small><strong>${money(a.wealth)}</strong></div><div><small>vs. start</small><strong class="${g.delta>=0?'positive':'negative'}">${g.delta>=0?'+':''}${money(g.delta)}</strong></div><div><small>${s.month?'vs. last month end':'vs. starting cash'}</small><strong class="${g.monthly>=0?'positive':'negative'}">${g.monthly>=0?'+':''}${money(g.monthly)}</strong></div></div>${chart(g)}<h3>What do you own right now?</h3><div class="wealth-composition">${g.buckets.filter(b=>b.value>0).map(b=>`<span style="flex:${b.value};background:${b.color}" title="${b.name} ${money(b.value)}"></span>`).join('')}</div><div class="wealth-legend">${g.buckets.map(b=>`<span><i style="background:${b.color}"></i>${b.name} <b>${money(b.value)}</b></span>`).join('')}<span>Debt <b>−${money(s.debt)}</b></span>${s.money<0?`<span>Cash short <b>${money(s.money)}</b></span>`:''}</div><p class="help">Net worth = cash + space sale value + stock value + inventory − debt. Borrowing raises cash but not net worth. The picture summarizes holdings and does not guarantee monthly profit.</p><div class="wealth-stages">${[{wealth:0,name:s.concept==='rich-life'?'Super Rich start':'First seed money'},...g.stages].map((m,i)=>`<div class="${i<=g.tier?'reached':''}"><span>${i<=g.tier?'✦':'◇'}</span><b>${m.name}</b><small>${i?money(m.wealth):'Start'}</small></div>`).join('')}</div><p>${g.next?'Next tier in '+money(Math.max(0,g.next.wealth-a.wealth))+' · '+g.next.name:'Super Rich reached! Keep growing your own mix of assets.'}</p><h3>Find my assets on the map</h3><div class="wealth-assets">${a.owned.map(({t,i})=>`<button data-growth-tile="${i}"><span>${TYPES[t.type].icon||'⌂'}</span><b>${TYPES[t.type].name} · Lv.${t.level}</b><small>Sale value ${money(assetValue(s,i))}</small></button>`).join('')||'<p class="help">No spaces yet. Your first workshop or shop will show up here.</p>'}</div><p class="help">The trend uses up to the last 36 month-end records plus the starting and current valuation. Trades this month land on the current point. Tiers follow current net worth and can fall if asset values drop.</p>`;}
