import {RICH_GOALS} from './rich-life.js';
import {compoundSummary} from './compound.js';
import {TYPES,MILESTONES,assetValue} from './engine.js';
const money=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function growthModel(s,a){
 const stages=s.concept==='rich-life'?RICH_GOALS:MILESTONES;
 const baseline=s.startingWealth||12000,previous=s.history.length>1?s.history.at(-2).wealth:baseline;
 const points=[{month:0,wealth:baseline},...s.history.filter(h=>h.month<s.month),{month:s.month,wealth:a.wealth}];
 if(s.month===0)points.splice(0,points.length,{month:0,wealth:baseline},{month:0,wealth:a.wealth});
 const tier=stages.filter(m=>a.wealth>=m.wealth).length,next=stages[tier];
 const buckets=[{name:'현금',value:Math.max(0,s.money),color:'#d9b359'},{name:'사업·공간',value:a.assets,color:'#7ba58c'},{name:'주식',value:a.stocks,color:'#739fbd'},{name:'재고',value:a.inventory,color:'#b998bd'},{name:'복리 자산',value:compoundSummary(s).assets,color:'#438363'},{name:'오너 지분·미술품',value:(a.empire?.assets||0)+(a.art?.value||0),color:'#b39961'}];
 return{stages,baseline,delta:a.wealth-baseline,monthly:a.wealth-previous,tier,next,points,buckets,gross:buckets.reduce((n,b)=>n+b.value,0),label:[s.concept==='rich-life'?'수퍼 리치':'종잣돈을 모으는 중',...stages.map(m=>m.name)][tier],royalties:(s.projects||[]).filter(p=>p.status==='earning').length};
}
function skyline(s,a){const owns=a.owned.filter(({t})=>t.type!=='plot').slice(0,9),width=640,base=164;let shapes='';
 const cashLevels=Math.min(12,Math.max(0,Math.floor(s.money/1000)));
 for(let n=0;n<cashLevels;n++){const x=34+(n%3)*23,y=base-Math.floor(n/3)*10;shapes+=`<ellipse cx="${x}" cy="${y}" rx="13" ry="5" fill="#b08b3f"/><ellipse cx="${x}" cy="${y-3}" rx="13" ry="5" fill="#edce78"/>`;}
 shapes+='<text x="56" y="193" text-anchor="middle">현금</text>';
 if(!owns.length)shapes+='<path d="M129 160h270" stroke="#bcc9b6" stroke-dasharray="5 5"/><text x="267" y="145" text-anchor="middle" fill="#81917c">첫 가게와 작업실이 들어설 자리</text>';
 owns.forEach(({t},n)=>{const x=120+n*32,w=27,h=27+t.level*22,col=TYPES[t.type].color;shapes+=`<g><rect x="${x}" y="${base-h}" width="${w}" height="${h}" rx="3" fill="${col}"/><path d="M${x+w} ${base-h}l8 7v${h-7}h-8z" fill="#456552"/><rect x="${x+4}" y="${base-h-5}" width="19" height="5" fill="#d9b76d"/>${Array.from({length:t.level+1},(_,k)=>`<path d="M${x+5} ${base-h+10+k*12}h5m7 0h5" stroke="#fff5c9" stroke-width="5"/>`).join('')}<title>${esc(TYPES[t.type].name)} · 레벨 ${t.level}</title></g>`;});
 shapes+=`<text x="267" y="193" text-anchor="middle">내 공간 ${a.owned.length}곳${a.owned.length>9?' · 대표 9곳':''}</text>`;
 const shares=Object.values(s.holdings).reduce((n,v)=>n+v,0),certs=shares?Math.min(5,1+Math.floor(shares/20)):0;
 for(let n=0;n<certs;n++)shapes+=`<rect x="${453+n*4}" y="${125-n*6}" width="45" height="35" rx="3" fill="#d7e6ed" stroke="#7599b0"/><path d="M${461+n*4} ${149-n*6}l8-6 8 2 12-12" fill="none" stroke="#52829d" stroke-width="2"/>`;
 shapes+=`<text x="478" y="193" text-anchor="middle">주식 ${shares}주</text>`;
 const books=(s.projects||[]).filter(p=>p.status==='earning').length;for(let n=0;n<Math.min(7,books);n++)shapes+=`<rect x="${548+n*7}" y="${130-n%3*7}" width="6" height="${34+n%3*7}" rx="1" fill="${['#b08ba6','#bda05b','#7fa795'][n%3]}"/>`;
 shapes+=`<text x="574" y="193" text-anchor="middle">수익 창작물 ${books}개</text>`;
 return `<svg class="wealth-scene" viewBox="0 0 ${width} 210" role="img" aria-label="현재 보유 현금 ${money(s.money)}, 내 공간 ${a.owned.length}곳, 주식 ${shares}주, 수익 창작물 ${books}개"><defs><linearGradient id="wealthSky" x2="0" y2="1"><stop stop-color="#edf3e5"/><stop offset="1" stop-color="#f8f5e9"/></linearGradient></defs><rect width="640" height="210" rx="16" fill="url(#wealthSky)"/><circle cx="556" cy="42" r="20" fill="#eddaa0"/><path d="M0 166Q180 145 320 162T640 160V210H0" fill="#dce6cf"/><g font-family="sans-serif" font-size="11" fill="#4b6451">${shapes}</g></svg>`;
}
function chart(g){const p=g.points,values=p.map(p=>p.wealth),lo=Math.min(...values),hi=Math.max(...values),range=Math.max(100,hi-lo),coords=p.map((point,i)=>[18+(p.at(-1).month?point.month/p.at(-1).month:i/Math.max(1,p.length-1))*594,99-(point.wealth-lo)/range*75]),line=coords.map(p=>p.join(',')).join(' '),color=g.delta>=0?'#477f60':'#b96856';return `<svg class="wealth-chart" viewBox="0 0 630 135" role="img" aria-label="시작 순자산 ${money(g.baseline)}, 현재 ${money(p.at(-1).wealth)}. 월말 기록과 현재 평가액 추이"><path d="M18 99H612" stroke="#d4ddcc"/><polygon points="18,100 ${line} 612,100" fill="${color}15"/><polyline points="${line}" fill="none" stroke="${color}" stroke-width="3"/>${coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="3" fill="${color}"><title>${p[i].month}개월 · ${money(p[i].wealth)}</title></circle>`).join('')}<text x="18" y="124">시작 ${money(g.baseline)}</text><text x="612" y="124" text-anchor="end">현재 ${money(p.at(-1).wealth)}</text></svg>`;}
export function growthCard(s,a){const g=growthModel(s,a);return `<button class="wealth-card" data-action="growth"><span class="wealth-caption">MY GROWTH <b>${g.label}</b></span>${skyline(s,a)}<span class="wealth-caption"><b class="${g.delta>=0?'positive':'negative'}">시작보다 ${g.delta>=0?'+':''}${money(g.delta)}</b><span>성장 펼쳐보기 ↗</span></span></button>`;}
export function growthDialog(s,a){const g=growthModel(s,a);return `<span class="eyebrow">MY WEALTH, TAKING SHAPE</span><h2>내 자산이 풍경이 되다.</h2><p>가게를 사면 건물이, 주식을 모으면 증서가, 수익을 내는 창작물이 생기면 책장이 채워집니다.</p>${skyline(s,a)}<div class="wealth-numbers"><div><small>현재 순자산</small><strong>${money(a.wealth)}</strong></div><div><small>처음보다</small><strong class="${g.delta>=0?'positive':'negative'}">${g.delta>=0?'+':''}${money(g.delta)}</strong></div><div><small>${s.month?'직전 월말보다':'시작 자금보다'}</small><strong class="${g.monthly>=0?'positive':'negative'}">${g.monthly>=0?'+':''}${money(g.monthly)}</strong></div></div>${chart(g)}<h3>지금 무엇을 가지고 있나요?</h3><div class="wealth-composition">${g.buckets.filter(b=>b.value>0).map(b=>`<span style="flex:${b.value};background:${b.color}" title="${b.name} ${money(b.value)}"></span>`).join('')}</div><div class="wealth-legend">${g.buckets.map(b=>`<span><i style="background:${b.color}"></i>${b.name} <b>${money(b.value)}</b></span>`).join('')}<span>대출 <b>−${money(s.debt)}</b></span>${s.money<0?`<span>현금 부족 <b>${money(s.money)}</b></span>`:''}</div><p class="help">순자산 = 현금 + 공간 매각 가치 + 주식 평가액 + 재고 − 대출. 대출로 현금이 늘어도 순자산은 늘지 않습니다. 그림은 보유량의 요약이며 월 수익을 보장하지 않습니다.</p><div class="wealth-stages">${[{wealth:0,name:s.concept==='rich-life'?'수퍼 리치 시작':'첫 종잣돈'},...g.stages].map((m,i)=>`<div class="${i<=g.tier?'reached':''}"><span>${i<=g.tier?'✦':'◇'}</span><b>${m.name}</b><small>${i?money(m.wealth):'시작'}</small></div>`).join('')}</div><p>${g.next?'다음 성장 단계까지 '+money(Math.max(0,g.next.wealth-a.wealth))+' · '+g.next.name:'슈퍼 리치 달성! 나만의 자산 구성을 계속 키워보세요.'}</p><h3>지도에서 내 자산 찾아가기</h3><div class="wealth-assets">${a.owned.map(({t,i})=>`<button data-growth-tile="${i}"><span>${TYPES[t.type].icon||'⌂'}</span><b>${TYPES[t.type].name} · Lv.${t.level}</b><small>매각 가치 ${money(assetValue(s,i))}</small></button>`).join('')||'<p class="help">아직 내 공간이 없습니다. 첫 작업실이나 가게를 마련하면 이곳에 등장합니다.</p>'}</div><p class="help">추이는 최대 최근 36개월 월말 기록과 시작·현재 평가액입니다. 당월 거래는 현재 지점에 반영됩니다. 단계는 현재 순자산 기준이며 자산 가치가 하락하면 내려갈 수 있습니다.</p>`;}
