import {marketPrice} from './economy.js';
import {FINDS,REPAIR_NAMES,BUYERS,journeyState,availableFinds,selectFind,inspectFind,purchaseFind,purchaseQuote,repairFind,repairQuote,offerFor,sellFind,leaveFind,chapterProgress,workspaceQuote,claimWorkspace} from './journey.js';
const cash=n=>'₲'+Math.round(n).toLocaleString('en-US');
function art(id,fixed=false){const shapes={bike:'<circle cx="65" cy="115" r="32"/><circle cx="185" cy="115" r="32"/><path d="M65 115l40-60 35 60H65l30-45h75l15 45M155 40h20l10 75M90 50h25"/>',lamp:'<path d="M90 35h70l25 65H65zM125 100v55M90 155h70"/><path d="M125 155h65v-30"/>',chair:'<path d="M85 35h85v70H85zM75 110h105v18H75zM85 128l-8 35M165 128l8 35M100 45v50M125 45v50M150 45v50"/>',keyboard:'<rect x="35" y="65" width="185" height="75" rx="8"/><path d="M60 90v50m25-50v50m25-50v50m25-50v50m25-50v50m25-50v50M35 88h185"/>'};return `<svg class="find-art ${fixed?'restored':''}" viewBox="0 0 250 190" role="img" aria-label="${fixed?'Restored':'Unrepaired'} ${FINDS.find(p=>p.id===id).name}"><ellipse cx="125" cy="166" rx="100" ry="10" fill="#253d3020" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round">${shapes[id]}</g>${fixed?'<text x="203" y="38" font-size="26" fill="#477b50">✦</text>':'<path d="M207 30l-9 17h13l-9 18" fill="none" stroke="#b46148" stroke-width="3"/>'}</svg>`;}
export function createJourneyUI({getState,openDialog,changed,toast,renderer,audio}){
 const button=(key,value,title,disabled=false)=>`<button data-journey="${key}" data-value="${value}" ${disabled?'disabled':''}>${title}</button>`;
 function show(){const s=getState(),j=journeyState(s),g=chapterProgress(s),d=j.deal;
 if(!d){openDialog('journey',`<span class="eyebrow">CHAPTER 01 · THE KEY TO MY FIRST WORKSHOP</span><h2>${g.done?'The next chance, built with my own hands.':'Value others missed becomes my first capital.'}</h2><p>From a neighbor garage to a workshop of your own. Read the clues, judge what to fix, and pick your buyer.</p><div class="journey-milestones"><span>${Math.min(g.wins,3)}/3 profitable deals</span><span>${cash(g.profit)} / ₲350 profit</span><span>${g.done?'✓ My workshop':'⌑ First workshop'}</span></div><div class="meter"><i style="width:${g.percent}%"></i></div>${g.ready&&!g.done?button('plots','','See first workshop terms →'):''}<div class="find-grid">${availableFinds(s).map(p=>`<button data-journey="find" data-value="${p.id}">${art(p.id)}<small>${p.seller}</small><b>${p.name}</b><span>Asking ${cash(marketPrice(s,p.ask))} · Inspect →</span></button>`).join('')}</div><p class="help">Reputation ${j.reputation} · up to ₲60 added to regular and collector offers. The calendar pauses while this screen is open. Work, stocks and business run alongside it anytime.</p>${j.sales.length?`<div class="journey-note">Last deal: ${FINDS.find(p=>p.id===j.sales.at(-1).item).name} · net profit ${cash(j.sales.at(-1).profit)}<br>${j.sales.at(-1).profit<0?'Next time, check the fault clues and the buyer requirements first.':'Leave a diagnosis record or build reputation - pick your next strategy.'}</div>`:''}`);return;}
 const p=FINDS.find(p=>p.id===d.item),fixed=d.repairs.includes(p.part);
 const head=`<span class="eyebrow">${d.stage==='inspect'?'01 FIND &amp; JUDGE':'02 REPAIR → 03 SELL'}</span><h2>${p.name}</h2><div class="find-scene">${art(p.id,fixed)}<div><small>${p.seller}</small><p>${p.story}</p><b>“${p.hint}”</b></div></div><div class="journey-note">${d.inspected?'Diagnosis record: '+p.fault:'Not diagnosed · judge from the clues alone, or check the condition for ₲15.'}</div>`;
 if(d.stage==='inspect'){openDialog('journey',head+`<p>The collector wants a <b>diagnosis made before purchase</b> plus working order. With a diagnosis you can negotiate ₲25 off the standard asking price.</p><div class="journey-choices">${button('inspect','','Diagnose · ₲15',d.inspected||s.money<15)}${button('buy','ask','Buy at asking · '+cash(marketPrice(s,p.ask)),s.money<purchaseQuote(s,'ask'))}${button('buy','negotiate','Negotiate with evidence · '+cash(purchaseQuote(s,'negotiate')),!d.inspected||s.money<purchaseQuote(s,'negotiate'))}${button('leave','','Let this deal go')}</div><p class="help">The diagnosis fee is not refunded. Repairs cost extra after the purchase.</p>`);return;}
 openDialog('journey',head+`<div class="journey-milestones"><span>Spent so far <b>${cash(d.spent)}</b></span><span>${fixed?'✓ Working':'⚠ Fault remains'}</span></div><h3>What will you fix?</h3><div class="journey-choices">${Object.entries(REPAIR_NAMES).map(([id,name])=>button('repair',id,name+' · '+(d.repairs.includes(id)?'Done':cash(repairQuote(s,id))),d.repairs.includes(id)||s.money<repairQuote(s,id))).join('')}</div><h3>Choose your buyer</h3><div class="buyer-grid">${Object.entries(BUYERS).map(([id,b])=>{const q=offerFor(s,id);return button('sell',id,`<b>${b.name}</b><small>${b.tag}</small><strong>${q.eligible?cash(q.amount):'Terms not met'}</strong><span>${q.eligible?'Est. net profit '+cash(q.amount-d.spent):q.reason}</span><small>${q.eligible?q.reason:b.quote}</small>`,!q.eligible);}).join('')}</div><p class="help">A finish restore adds ₲60 to the sale base. The wrong part leaves the fault unfixed and only adds cost. Repair again to recover, or disclose the condition and sell.</p>`);
 }
 function plots(){const s=getState();const ids=s.tiles.map((t,i)=>i).filter(i=>{const t=s.tiles[i],x=i%26,y=Math.floor(i/26);return !t.type&&t.terrain==='land'&&[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].some(([a,b])=>a>=0&&b>=0&&a<26&&b<26&&s.tiles[b*26+a].type==='road');}).sort((a,b)=>Math.hypot(a%26-10,Math.floor(a/26)-10)-Math.hypot(b%26-10,Math.floor(b/26)-10)).slice(0,3);openDialog('journey',`<span class="eyebrow">YOUR FIRST WORKSPACE</span><h2>Now, a workshop with my name on it.</h2><p>On-site repair costs −20% · Creative project progress +15% per hour. The workshop earns no revenue and charges monthly rent and upkeep.</p><div class="journey-choices">${ids.map(i=>{const q=workspaceQuote(s,i);return button('claim',i,`<b>Ave. ${i%26+1} · No. ${Math.floor(i/26)+1}</b><small>Contract ${cash(q.cost)} (deposit ${cash(q.deposit)} included)<br>Monthly rent and upkeep ${cash(q.rent)}</small>`,s.money<q.cost);}).join('')||'<p>No empty roadside lots. Clear a lot you own and come back.</p>'}</div><p class="help">Rent moves with land value. The contract cost comes out of your cash.</p>${button('open','','Trade more and come back')}`);}
 function handle(b){const action=b.dataset.journey;if(!action)return false;const s=getState(),v=b.dataset.value;if(action==='open'){show();return true;}if(action==='plots'){plots();return true;}const r=action==='find'?selectFind(s,v):action==='inspect'?inspectFind(s):action==='buy'?purchaseFind(s,v):action==='repair'?repairFind(s,v):action==='sell'?sellFind(s,v):action==='leave'?leaveFind(s):action==='claim'?claimWorkspace(s,Number(v)):null;if(!r)return false;toast(r.msg);if(!r.ok)return true;changed();audio.play(action==='sell'?'coin':action==='claim'?'win':'build');
 if(action==='sell'){const g=chapterProgress(s);openDialog('journey',`<div class="journey-result">${art(r.sale.item,r.sale.fixed)}<span class="eyebrow">DEAL COMPLETE · ${BUYERS[v].name}</span><h2>${r.profit>=0?'The reward for spotting value.':'What this deal taught me.'}</h2><strong class="${r.profit>=0?'positive':'negative'}">Net profit ${cash(r.profit)}</strong><p>Sale ${cash(r.sale.revenue)} − total cost ${cash(r.sale.spent)}</p><p>${r.msg}</p><div class="journey-note">${g.ready&&!g.done?'✦ You have met the terms for your first workshop!':'Profitable deals '+Math.min(g.wins,3)+'/3 · total profit '+cash(g.profit)+' / ₲350'}<br>Reputation +${r.sale.reputation}</div>${button(g.ready&&!g.done?'plots':'open','',g.ready&&!g.done?'Claim my workshop →':'Find the next item →')}</div>`);renderer.burst(-1,'Deal profit '+cash(r.profit),r.profit<0?'loss':'coin');}
 else if(action==='claim'){renderer.select(r.tile);renderer.visit(r.tile);renderer.burst(r.tile,'FIRST WORKSHOP OPEN!');openDialog('journey',`<div class="journey-result"><span class="key-reward">⚿</span><span class="eyebrow">CHAPTER 01 COMPLETE</span><h2>The key to my first workshop.</h2><p>Value found in a discarded object<br>became the space where I work.</p><div class="journey-note">On-site repair costs −20% · Creative output +15%<br>Find your workshop on the map.</div><button data-action="close" class="primary full">Back to my neighborhood →</button></div>`);}
 else show();return true;}
 return{show,handle};
}
