import {marketFactor,marketPrice} from './economy.js';
import {landPrice} from './engine.js';
// A playable first chapter: evidence → purchase → repair → buyer → first workspace.
// Offers and consequences are deterministic, displayed before committing money.
export const FINDS = [
 {id:'bike',name:'멈춰 선 클래식 자전거',icon:'◉',seller:'이사를 앞둔 지훈',ask:180,base:380,part:'drive',fault:'체인이 헛돌고 변속 케이블이 늘어져 있습니다.',hint:'페달을 돌리자 바퀴가 한 박자 늦게 따라옵니다.',story:'창고에서 몇 년을 보냈지만 프레임은 튼튼합니다. 광만 내면 될지, 안쪽까지 볼지 판단해 보세요.',repairs:{drive:70,electric:90,finish:35}},
 {id:'lamp',name:'불이 꺼진 빈티지 조명',icon:'☼',seller:'골목 서점의 은아',ask:120,base:310,part:'electric',fault:'전원선 접점이 끊어져 있습니다. 갓과 받침은 멀쩡합니다.',hint:'스위치를 켜면 잠깐 빛나다가 다시 꺼집니다.',story:'서점 한쪽을 밝히던 조명입니다. 주인은 고칠 시간이 없어 내놓았습니다.',repairs:{drive:65,electric:55,finish:30}},
 {id:'chair',name:'흔들리는 원목 의자',icon:'⌑',seller:'공방을 정리하는 도윤',ask:150,base:350,part:'drive',fault:'다리 연결부의 나사가 풀렸습니다. 목재 균열은 없습니다.',hint:'앉으면 삐걱거리지만 나뭇결에는 갈라짐이 보이지 않습니다.',story:'원목이라는 이유만으로 비싼 것은 아닙니다. 다시 편히 앉을 수 있게 만들면 가치가 달라집니다.',repairs:{drive:60,electric:80,finish:40}},
 {id:'keyboard',name:'소리가 끊기는 키보드',icon:'♫',seller:'밴드 멤버 유리',ask:260,base:500,part:'electric',fault:'오디오 출력 단자가 느슨합니다. 건반 센서는 정상입니다.',hint:'케이블을 움직이면 소리가 돌아옵니다.',story:'다음 공연 전 새 악기를 산다며 내놓았습니다. 급하게 팔겠다는 말이 좋은 거래를 보장하지는 않습니다.',repairs:{drive:95,electric:85,finish:45}},
];
export const REPAIR_NAMES={drive:'구동부·연결부 정비',electric:'전원·접점 수리',finish:'세척·외관 복원'};
export const BUYERS={quick:{name:'당일 매입상',tag:'즉시 거래 · 낮은 가격',quote:'손볼 곳이 있어도 가져갈게요. 대신 가격은 낮습니다.'},collector:{name:'전문 수집가 민서',tag:'높은 가격 · 진단·정상 작동 필수',quote:'제대로 고친 물건이라면 제값을 드릴게요.'},neighbor:{name:'동네 손님 하린',tag:'단골 관계 · 정상 작동 필수',quote:'오래 쓸 물건을 찾고 있어요. 마음에 들면 또 올게요.'}};
export function journeyState(s){return s.journey||{version:1,round:0,profit:0,reputation:0,sales:[],deal:null,workroom:null};}
function ensure(s){return s.journey||=(journeyState(s));}
export function availableFinds(s){const j=journeyState(s),offset=j.round%FINDS.length;return Array.from({length:3},(_,n)=>FINDS[(offset+n)%FINDS.length]);}
export function selectFind(s,id){const j=ensure(s);if(j.deal)return{ok:false,msg:'지금 살펴보는 물건부터 마무리하세요.'};if(!availableFinds(s).some(p=>p.id===id))return{ok:false,msg:'현재 골목에서 찾을 수 없는 물건입니다.'};j.deal={item:id,stage:'inspect',inspected:false,spent:0,repairs:[],purchase:0};return{ok:true,msg:'물건의 단서를 살펴보세요.'};}
export function inspectFind(s){const d=s.journey?.deal;if(!d||d.stage!=='inspect'||d.inspected)return{ok:false,msg:'이미 확인했거나 진단할 물건이 없습니다.'};if(s.money<15)return{ok:false,msg:'진단 비용 ₲15가 필요합니다. 비용 없이 단서만 보고 판단할 수도 있습니다.'};s.money-=15;d.spent+=15;d.inspected=true;return{ok:true,msg:FINDS.find(p=>p.id===d.item).fault};}
export function purchaseQuote(s,mode){const d=s.journey?.deal,p=FINDS.find(p=>p.id===d?.item);if(!p)return null;return marketPrice(s,mode==='negotiate'&&d.inspected?p.ask-25:p.ask);}
export function purchaseFind(s,mode){const d=s.journey?.deal;if(!d||d.stage!=='inspect'||!['ask','negotiate'].includes(mode))return{ok:false,msg:'매입 방식을 선택하세요.'};if(mode==='negotiate'&&!d.inspected)return{ok:false,msg:'가격을 낮출 근거가 필요합니다. 먼저 상태를 진단해 보세요.'};const price=purchaseQuote(s,mode);if(s.money<price)return{ok:false,msg:'매입할 자금이 부족합니다. 다른 소득으로 자본을 마련하거나 거래를 놓아주세요.'};s.money-=price;d.spent+=price;d.purchase=price;d.purchaseFactor=marketFactor(s);d.stage='repair';return{ok:true,msg:mode==='negotiate'?'진단을 근거로 시세에 맞춰 협상해 매입했습니다.':'매입 완료. 어떤 작업이 가치를 높일지 선택하세요.'};}
export function repairQuote(s,part){const d=s.journey?.deal,p=FINDS.find(p=>p.id===d?.item);if(!p||!Object.hasOwn(REPAIR_NAMES,part))return null;const own=s.journey?.workroom,discount=own!==null&&own!==undefined&&s.tiles[own]?.owner==='player'&&s.tiles[own]?.type==='atelier'?.8:1;return Math.round(p.repairs[part]*discount);}
export function repairFind(s,part){const d=s.journey?.deal;if(!d||!['repair','sell'].includes(d.stage)||!Object.hasOwn(REPAIR_NAMES,part))return{ok:false,msg:'진행할 수리를 골라주세요.'};if(d.repairs.includes(part))return{ok:false,msg:'이미 끝낸 작업입니다.'};const cost=repairQuote(s,part);if(s.money<cost)return{ok:false,msg:'수리 자금이 부족합니다. 현재 상태로 매입상에게 판매할 수 있습니다.'};s.money-=cost;d.spent+=cost;d.repairs.push(part);d.stage='sell';const p=FINDS.find(p=>p.id===d.item),fixed=d.repairs.includes(p.part);return{ok:true,fixed,msg:fixed?'정상 작동! 어떤 손님에게 팔지 정해보세요.':'작업은 끝났지만 작동 문제는 남아 있습니다. 단서를 다시 보고 다른 부위를 수리할 수 있습니다.'};}
export function offerFor(s,buyer){const j=journeyState(s),d=j.deal,p=FINDS.find(p=>p.id===d?.item);if(!p||!Object.hasOwn(BUYERS,buyer))return null;const fixed=d.repairs.includes(p.part),polished=d.repairs.includes('finish'),value=p.base+(polished?60:0),relationship=Math.min(30,j.reputation)*2;
 if(buyer==='quick')return{eligible:true,amount:marketPrice(s,fixed?value*.78:p.ask*.65),rep:0,reason:'상태를 공개한 즉시 매각'};
 if(!fixed)return{eligible:false,amount:0,rep:0,reason:'정상 작동하는 물건을 원합니다.'};
 if(buyer==='collector'&&!d.inspected)return{eligible:false,amount:0,rep:0,reason:'전문 수집가는 매입 전 진단 기록을 요구합니다.'};
 return{eligible:true,amount:marketPrice(s,value*(buyer==='collector'?1.23:1.02)+relationship),rep:buyer==='neighbor'?3:1,reason:buyer==='neighbor'?'동네 평판 +3 · 다음 거래 제안가 상승':'동네 평판 +1 · 높은 현금 이익'};
}
export function sellFind(s,buyer){const j=s.journey,d=j?.deal;if(!d||!['repair','sell'].includes(d.stage))return{ok:false,msg:'먼저 물건을 매입하세요.'};const offer=offerFor(s,buyer);if(!offer?.eligible)return{ok:false,msg:offer?.reason||'구매자를 선택하세요.'};s.money+=offer.amount;const p=FINDS.find(p=>p.id===d.item),profit=offer.amount-d.spent;const sale={round:j.round,item:d.item,buyer,spent:d.spent,revenue:offer.amount,profit,reputation:offer.rep,fixed:d.repairs.includes(p.part)};j.profit+=profit;j.reputation+=offer.rep;j.sales.push(sale);j.sales=j.sales.slice(-30);j.round++;j.deal=null;s.log.unshift(`${p.name} 거래 · ${profit>=0?'+':''}${profit}G · ${BUYERS[buyer].name}`);s.log=s.log.slice(0,25);return{ok:true,profit,sale,msg:profit>=0?'내 판단으로 가치를 만들었습니다.':'손실도 다음 거래의 정보입니다. 수리 전에 상태와 구매자 조건을 확인해 보세요.'};}
export function leaveFind(s){const j=s.journey;if(!j?.deal||j.deal.stage!=='inspect')return{ok:false,msg:'이미 매입한 물건은 판매해서 정리하세요.'};j.profit-=j.deal.spent;j.deal=null;j.round++;return{ok:true,msg:'이번 물건은 놓아줍니다. 다른 기회를 살펴보세요.'};}
export function chapterProgress(s){const j=journeyState(s),wins=j.sales.filter(x=>x.profit>0).length;return{wins,profit:j.profit,ready:wins>=3&&j.profit>=350,done:j.workroom!==null,percent:Math.round((Math.min(1,wins/3)+Math.max(0,Math.min(1,j.profit/350)))/2*100)};}
export function workspaceQuote(s,i){const land=landPrice(s,i);return{cost:1200+Math.round(land*.2),deposit:Math.round(land*.2),rent:Math.round(land*.035)+35};}
export function claimWorkspace(s,i){const j=ensure(s),t=s.tiles[i];if(!chapterProgress(s).ready||j.workroom!==null)return{ok:false,msg:'수익을 낸 거래 3건과 누적 거래 이익 ₲350이 필요합니다.'};if(!t||t.type||t.terrain!=='land')return{ok:false,msg:'빈 작업실 부지를 골라주세요.'};const x=i%26,y=Math.floor(i/26),adj=[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>a>=0&&a<26&&b>=0&&b<26).map(([a,b])=>b*26+a);if(!adj.some(n=>s.tiles[n].type==='road'))return{ok:false,msg:'도로 옆 부지가 필요합니다.'};const q=workspaceQuote(s,i);if(s.money<q.cost)return{ok:false,msg:'보증금과 작업실 준비금을 조금 더 모아주세요.'};s.money-=q.cost;Object.assign(t,{type:'atelier',owner:'player',tenure:'lease',deposit:q.deposit,constructionCost:1200,assetLedger:{initial:q.cost,upgrades:0,operating:0,since:s.month,estimated:false,buildingValue:840,valuationMonth:s.month},level:1,tree:false,price:100,quality:1,staff:0,marketing:false});j.workroom=i;s.log.unshift('✦ 첫 작업실의 열쇠를 받았습니다. 현장 수리비 20% 절감 · 창작 작업 효율 +15%');s.log=s.log.slice(0,25);return{ok:true,msg:'첫 작업실을 마련했습니다!',tile:i};}
export function validJourney(s){if(s.journey===undefined)return true;const j=s.journey;if(!j||j.version!==1||!Number.isInteger(j.round)||j.round<0||!Number.isFinite(j.profit)||!Number.isInteger(j.reputation)||j.reputation<0||!(j.workroom===null||Number.isInteger(j.workroom)&&j.workroom>=0&&j.workroom<676)||!Array.isArray(j.sales)||j.sales.length>30)return false;
 if(!j.sales.every(x=>x&&FINDS.some(p=>p.id===x.item)&&Object.hasOwn(BUYERS,x.buyer)&&['spent','revenue','profit','reputation','round'].every(k=>Number.isFinite(x[k]))&&typeof x.fixed==='boolean'))return false;
 const d=j.deal;if(!d)return true;return (d.purchaseFactor===undefined||(Number.isFinite(d.purchaseFactor)&&d.purchaseFactor>=.5&&d.purchaseFactor<=1))&&FINDS.some(p=>p.id===d.item)&&['inspect','repair','sell'].includes(d.stage)&&typeof d.inspected==='boolean'&&Number.isFinite(d.spent)&&d.spent>=0&&Number.isFinite(d.purchase)&&d.purchase>=0&&Array.isArray(d.repairs)&&d.repairs.length<=3&&new Set(d.repairs).size===d.repairs.length&&d.repairs.every(p=>Object.hasOwn(REPAIR_NAMES,p));
}

export function journeyInventoryValue(s){const d=s.journey?.deal;return d&&d.stage!=='inspect'?Math.round(Math.min(d.spent/(d.purchaseFactor??1),offerFor(s,'quick').amount/marketFactor(s))*marketFactor(s)):0;}
