import {marketFactor,marketPrice} from './economy.js';
import {landPrice} from './engine.js';
// A playable first chapter: evidence → purchase → repair → buyer → first workspace.
// Offers and consequences are deterministic, displayed before committing money.
export const FINDS = [
 {id:'bike',name:'Stalled Classic Bicycle',icon:'◉',seller:'Jihun, moving out soon',ask:180,base:380,part:'drive',fault:'The chain slips and the shifter cable is stretched.',hint:'Turn the pedals and the wheel follows a beat late.',story:'Years in a garage, but the frame is solid. Decide whether a polish is enough or the insides need work.',repairs:{drive:70,electric:90,finish:35}},
 {id:'lamp',name:'Dead Vintage Lamp',icon:'☼',seller:'Euna of the alley bookshop',ask:120,base:310,part:'electric',fault:'The power lead contact is broken. Shade and base are fine.',hint:'Flip the switch and it glows a moment, then dies.',story:'It used to light a corner of the bookshop. The owner had no time to fix it.',repairs:{drive:65,electric:55,finish:30}},
 {id:'chair',name:'Wobbly Solid Wood Chair',icon:'⌑',seller:'Doyun, closing his workshop',ask:150,base:350,part:'drive',fault:'The leg joint screws are loose. No cracks in the wood.',hint:'It creaks when you sit, but the grain shows no splits.',story:'Solid wood alone does not make it valuable. Make it comfortable again and the value changes.',repairs:{drive:60,electric:80,finish:40}},
 {id:'keyboard',name:'Cutting-Out Keyboard',icon:'♫',seller:'Yuri from the band',ask:260,base:500,part:'electric',fault:'The audio output jack is loose. The key sensors are fine.',hint:'Wiggle the cable and the sound comes back.',story:'Listed to fund a new instrument before the next show. A rushed sale is no guarantee of a good deal.',repairs:{drive:95,electric:85,finish:45}},
];
export const REPAIR_NAMES={drive:'Drivetrain and joint service',electric:'Power and contact repair',finish:'Clean and finish restore'};
export const BUYERS={quick:{name:'Same-day dealer',tag:'Instant deal · low price',quote:'I will take it even if it needs work. The price stays low, though.'},collector:{name:'Minseo, expert collector',tag:'High price · diagnosis and working order required',quote:'If it is properly fixed, I will pay what it is worth.'},neighbor:{name:'Harin, neighborhood buyer',tag:'Regular customer · working order required',quote:'I want something that lasts. If I like it, I will be back.'}};
export function journeyState(s){return s.journey||{version:1,round:0,profit:0,reputation:0,sales:[],deal:null,workroom:null};}
function ensure(s){return s.journey||=(journeyState(s));}
export function availableFinds(s){const j=journeyState(s),offset=j.round%FINDS.length;return Array.from({length:3},(_,n)=>FINDS[(offset+n)%FINDS.length]);}
export function selectFind(s,id){const j=ensure(s);if(j.deal)return{ok:false,msg:'Finish with the item you are inspecting first.'};if(!availableFinds(s).some(p=>p.id===id))return{ok:false,msg:'That item is not in the alley right now.'};j.deal={item:id,stage:'inspect',inspected:false,spent:0,repairs:[],purchase:0};return{ok:true,msg:'Look over the clues on this item.'};}
export function inspectFind(s){const d=s.journey?.deal;if(!d||d.stage!=='inspect'||d.inspected)return{ok:false,msg:'Already checked, or there is nothing to diagnose.'};if(s.money<15)return{ok:false,msg:'The ₲15 diagnosis fee is required. You can also judge from the clues for free.'};s.money-=15;d.spent+=15;d.inspected=true;return{ok:true,msg:FINDS.find(p=>p.id===d.item).fault};}
export function purchaseQuote(s,mode){const d=s.journey?.deal,p=FINDS.find(p=>p.id===d?.item);if(!p)return null;return marketPrice(s,mode==='negotiate'&&d.inspected?p.ask-25:p.ask);}
export function purchaseFind(s,mode){const d=s.journey?.deal;if(!d||d.stage!=='inspect'||!['ask','negotiate'].includes(mode))return{ok:false,msg:'Choose how to buy.'};if(mode==='negotiate'&&!d.inspected)return{ok:false,msg:'You need evidence to lower the price. Diagnose the condition first.'};const price=purchaseQuote(s,mode);if(s.money<price)return{ok:false,msg:'Not enough cash to buy. Raise capital from other income, or let the deal go.'};s.money-=price;d.spent+=price;d.purchase=price;d.purchaseFactor=marketFactor(s);d.stage='repair';return{ok:true,msg:mode==='negotiate'?'You used the diagnosis to negotiate down to market value and bought it.':'Purchase complete. Choose the work that adds the most value.'};}
export function repairQuote(s,part){const d=s.journey?.deal,p=FINDS.find(p=>p.id===d?.item);if(!p||!Object.hasOwn(REPAIR_NAMES,part))return null;const own=s.journey?.workroom,discount=own!==null&&own!==undefined&&s.tiles[own]?.owner==='player'&&s.tiles[own]?.type==='atelier'?.8:1;return Math.round(p.repairs[part]*discount);}
export function repairFind(s,part){const d=s.journey?.deal;if(!d||!['repair','sell'].includes(d.stage)||!Object.hasOwn(REPAIR_NAMES,part))return{ok:false,msg:'Pick a repair to carry out.'};if(d.repairs.includes(part))return{ok:false,msg:'That work is already done.'};const cost=repairQuote(s,part);if(s.money<cost)return{ok:false,msg:'Not enough cash to repair. You can still sell as-is to the dealer.'};s.money-=cost;d.spent+=cost;d.repairs.push(part);d.stage='sell';const p=FINDS.find(p=>p.id===d.item),fixed=d.repairs.includes(p.part);return{ok:true,fixed,msg:fixed?'Working order! Now decide which buyer to sell to.':'The work is done but the fault remains. Re-read the clues and repair another part.'};}
export function offerFor(s,buyer){const j=journeyState(s),d=j.deal,p=FINDS.find(p=>p.id===d?.item);if(!p||!Object.hasOwn(BUYERS,buyer))return null;const fixed=d.repairs.includes(p.part),polished=d.repairs.includes('finish'),value=p.base+(polished?60:0),relationship=Math.min(30,j.reputation)*2;
 if(buyer==='quick')return{eligible:true,amount:marketPrice(s,fixed?value*.78:p.ask*.65),rep:0,reason:'Immediate sale with the condition disclosed'};
 if(!fixed)return{eligible:false,amount:0,rep:0,reason:'They want an item in working order.'};
 if(buyer==='collector'&&!d.inspected)return{eligible:false,amount:0,rep:0,reason:'The expert collector requires a diagnosis record made before the purchase.'};
 return{eligible:true,amount:marketPrice(s,value*(buyer==='collector'?1.23:1.02)+relationship),rep:buyer==='neighbor'?3:1,reason:buyer==='neighbor'?'Neighborhood reputation +3 · higher offers next deal':'Neighborhood reputation +1 · high cash profit'};
}
export function sellFind(s,buyer){const j=s.journey,d=j?.deal;if(!d||!['repair','sell'].includes(d.stage))return{ok:false,msg:'Buy an item first.'};const offer=offerFor(s,buyer);if(!offer?.eligible)return{ok:false,msg:offer?.reason||'Choose a buyer.'};s.money+=offer.amount;const p=FINDS.find(p=>p.id===d.item),profit=offer.amount-d.spent;const sale={round:j.round,item:d.item,buyer,spent:d.spent,revenue:offer.amount,profit,reputation:offer.rep,fixed:d.repairs.includes(p.part)};j.profit+=profit;j.reputation+=offer.rep;j.sales.push(sale);j.sales=j.sales.slice(-30);j.round++;j.deal=null;s.log.unshift(`${p.name} deal · ${profit>=0?'+':''}${profit}G · ${BUYERS[buyer].name}`);s.log=s.log.slice(0,25);return{ok:true,profit,sale,msg:profit>=0?'Your own judgment created the value.':'A loss is information for the next deal. Check the condition and the buyer terms before repairing.'};}
export function leaveFind(s){const j=s.journey;if(!j?.deal||j.deal.stage!=='inspect')return{ok:false,msg:'An item you already bought has to be sold to close it out.'};j.profit-=j.deal.spent;j.deal=null;j.round++;return{ok:true,msg:'You let this one go. Look for another opportunity.'};}
export function chapterProgress(s){const j=journeyState(s),wins=j.sales.filter(x=>x.profit>0).length;return{wins,profit:j.profit,ready:wins>=3&&j.profit>=350,done:j.workroom!==null,percent:Math.round((Math.min(1,wins/3)+Math.max(0,Math.min(1,j.profit/350)))/2*100)};}
export function workspaceQuote(s,i){const land=landPrice(s,i);return{cost:1200+Math.round(land*.2),deposit:Math.round(land*.2),rent:Math.round(land*.035)+35};}
export function claimWorkspace(s,i){const j=ensure(s),t=s.tiles[i];if(!chapterProgress(s).ready||j.workroom!==null)return{ok:false,msg:'3 profitable deals and ₲350 of total deal profit are required.'};if(!t||t.type||t.terrain!=='land')return{ok:false,msg:'Pick an empty lot for the workshop.'};const x=i%26,y=Math.floor(i/26),adj=[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>a>=0&&a<26&&b>=0&&b<26).map(([a,b])=>b*26+a);if(!adj.some(n=>s.tiles[n].type==='road'))return{ok:false,msg:'A roadside lot is required.'};const q=workspaceQuote(s,i);if(s.money<q.cost)return{ok:false,msg:'Save a little more for the deposit and the workshop setup.'};s.money-=q.cost;Object.assign(t,{type:'atelier',owner:'player',tenure:'lease',deposit:q.deposit,constructionCost:1200,assetLedger:{initial:q.cost,upgrades:0,operating:0,since:s.month,estimated:false,buildingValue:840,valuationMonth:s.month},level:1,tree:false,price:100,quality:1,staff:0,marketing:false});j.workroom=i;s.log.unshift('✦ You received the key to your first workshop. On-site repair costs −20% · Creative output +15%');s.log=s.log.slice(0,25);return{ok:true,msg:'Your first workshop is open!',tile:i};}
export function validJourney(s){if(s.journey===undefined)return true;const j=s.journey;if(!j||j.version!==1||!Number.isInteger(j.round)||j.round<0||!Number.isFinite(j.profit)||!Number.isInteger(j.reputation)||j.reputation<0||!(j.workroom===null||Number.isInteger(j.workroom)&&j.workroom>=0&&j.workroom<676)||!Array.isArray(j.sales)||j.sales.length>30)return false;
 if(!j.sales.every(x=>x&&FINDS.some(p=>p.id===x.item)&&Object.hasOwn(BUYERS,x.buyer)&&['spent','revenue','profit','reputation','round'].every(k=>Number.isFinite(x[k]))&&typeof x.fixed==='boolean'))return false;
 const d=j.deal;if(!d)return true;return (d.purchaseFactor===undefined||(Number.isFinite(d.purchaseFactor)&&d.purchaseFactor>=.5&&d.purchaseFactor<=1))&&FINDS.some(p=>p.id===d.item)&&['inspect','repair','sell'].includes(d.stage)&&typeof d.inspected==='boolean'&&Number.isFinite(d.spent)&&d.spent>=0&&Number.isFinite(d.purchase)&&d.purchase>=0&&Array.isArray(d.repairs)&&d.repairs.length<=3&&new Set(d.repairs).size===d.repairs.length&&d.repairs.every(p=>Object.hasOwn(REPAIR_NAMES,p));
}

export function journeyInventoryValue(s){const d=s.journey?.deal;return d&&d.stage!=='inspect'?Math.round(Math.min(d.spent/(d.purchaseFactor??1),offerFor(s,'quick').amount/marketFactor(s))*marketFactor(s)):0;}
