import {marketPrice} from './economy.js';
import {FINDS,REPAIR_NAMES,BUYERS,journeyState,availableFinds,selectFind,inspectFind,purchaseFind,purchaseQuote,repairFind,repairQuote,offerFor,sellFind,leaveFind,chapterProgress,workspaceQuote,claimWorkspace} from './journey.js';
const cash=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
function art(id,fixed=false){const shapes={bike:'<circle cx="65" cy="115" r="32"/><circle cx="185" cy="115" r="32"/><path d="M65 115l40-60 35 60H65l30-45h75l15 45M155 40h20l10 75M90 50h25"/>',lamp:'<path d="M90 35h70l25 65H65zM125 100v55M90 155h70"/><path d="M125 155h65v-30"/>',chair:'<path d="M85 35h85v70H85zM75 110h105v18H75zM85 128l-8 35M165 128l8 35M100 45v50M125 45v50M150 45v50"/>',keyboard:'<rect x="35" y="65" width="185" height="75" rx="8"/><path d="M60 90v50m25-50v50m25-50v50m25-50v50m25-50v50m25-50v50M35 88h185"/>'};return `<svg class="find-art ${fixed?'restored':''}" viewBox="0 0 250 190" role="img" aria-label="${fixed?'수리된':'수리 전'} ${FINDS.find(p=>p.id===id).name}"><ellipse cx="125" cy="166" rx="100" ry="10" fill="#253d3020" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round">${shapes[id]}</g>${fixed?'<text x="203" y="38" font-size="26" fill="#477b50">✦</text>':'<path d="M207 30l-9 17h13l-9 18" fill="none" stroke="#b46148" stroke-width="3"/>'}</svg>`;}
export function createJourneyUI({getState,openDialog,changed,toast,renderer,audio}){
 const button=(key,value,title,disabled=false)=>`<button data-journey="${key}" data-value="${value}" ${disabled?'disabled':''}>${title}</button>`;
 function show(){const s=getState(),j=journeyState(s),g=chapterProgress(s),d=j.deal;
 if(!d){openDialog('journey',`<span class="eyebrow">CHAPTER 01 · 첫 작업실의 열쇠</span><h2>${g.done?'내 손으로 만든 다음 기회.':'남들이 놓친 가치, 나의 첫 자본.'}</h2><p>지훈의 창고에서 시작해 나만의 작업실까지. 단서를 읽고, 고칠 곳을 판단하고, 손님을 골라보세요.</p><div class="journey-milestones"><span>${Math.min(g.wins,3)}/3 수익 거래</span><span>${cash(g.profit)} / ₲350 이익</span><span>${g.done?'✓ 내 작업실':'⌑ 첫 작업실'}</span></div><div class="meter"><i style="width:${g.percent}%"></i></div>${g.ready&&!g.done?button('plots','','첫 작업실 계약 조건 보기 →'):''}<div class="find-grid">${availableFinds(s).map(p=>`<button data-journey="find" data-value="${p.id}">${art(p.id)}<small>${p.seller}</small><b>${p.name}</b><span>호가 ${cash(marketPrice(s,p.ask))} · 살펴보기 →</span></button>`).join('')}</div><p class="help">평판 ${j.reputation} · 단골·수집가 제안가에 최대 ₲60 반영. 거래 화면을 열어 두면 달력이 멈춥니다. 노동·주식·사업은 언제든 병행할 수 있습니다.</p>${j.sales.length?`<div class="journey-note">지난 거래: ${FINDS.find(p=>p.id===j.sales.at(-1).item).name} · 순이익 ${cash(j.sales.at(-1).profit)}<br>${j.sales.at(-1).profit<0?'다음에는 고장 단서와 손님의 구매 조건부터 확인해 보세요.':'진단 기록을 남길지, 평판을 쌓을지 다음 전략을 골라보세요.'}</div>`:''}`);return;}
 const p=FINDS.find(p=>p.id===d.item),fixed=d.repairs.includes(p.part);
 const head=`<span class="eyebrow">${d.stage==='inspect'?'01 발견 & 판단':'02 수리 → 03 판매'}</span><h2>${p.name}</h2><div class="find-scene">${art(p.id,fixed)}<div><small>${p.seller}</small><p>${p.story}</p><b>“${p.hint}”</b></div></div><div class="journey-note">${d.inspected?'진단 기록: '+p.fault:'진단 전 · 단서만으로 판단하거나 ₲15로 상태를 확인하세요.'}</div>`;
 if(d.stage==='inspect'){openDialog('journey',head+`<p>수집가는 <b>매입 전 진단 기록</b>과 정상 작동을 요구합니다. 진단하면 정상 호가 기준 ₲25에 해당하는 금액을 협상할 수 있습니다.</p><div class="journey-choices">${button('inspect','','상태 진단 · ₲15',d.inspected||s.money<15)}${button('buy','ask','호가로 매입 · '+cash(marketPrice(s,p.ask)),s.money<purchaseQuote(s,'ask'))}${button('buy','negotiate','근거로 협상 · '+cash(purchaseQuote(s,'negotiate')),!d.inspected||s.money<purchaseQuote(s,'negotiate'))}${button('leave','','이번 거래 놓아주기')}</div><p class="help">진단 비용은 돌려받지 않습니다. 매입 후 수리비가 추가로 필요합니다.</p>`);return;}
 openDialog('journey',head+`<div class="journey-milestones"><span>투입 비용 <b>${cash(d.spent)}</b></span><span>${fixed?'✓ 정상 작동':'⚠ 작동 문제 남음'}</span></div><h3>어디에 손을 댈까요?</h3><div class="journey-choices">${Object.entries(REPAIR_NAMES).map(([id,name])=>button('repair',id,name+' · '+(d.repairs.includes(id)?'완료':cash(repairQuote(s,id))),d.repairs.includes(id)||s.money<repairQuote(s,id))).join('')}</div><h3>손님을 고르세요</h3><div class="buyer-grid">${Object.entries(BUYERS).map(([id,b])=>{const q=offerFor(s,id);return button('sell',id,`<b>${b.name}</b><small>${b.tag}</small><strong>${q.eligible?cash(q.amount):'조건 미충족'}</strong><span>${q.eligible?'예상 순이익 '+cash(q.amount-d.spent):q.reason}</span><small>${q.eligible?q.reason:b.quote}</small>`,!q.eligible);}).join('')}</div><p class="help">외관 복원은 판매 기준가 +₲60. 잘못 고른 부위는 고장이 해결되지 않아 비용만 늘어납니다. 추가 수리로 만회하거나 상태를 공개하고 매각할 수 있습니다.</p>`);
 }
 function plots(){const s=getState();const ids=s.tiles.map((t,i)=>i).filter(i=>{const t=s.tiles[i],x=i%26,y=Math.floor(i/26);return !t.type&&t.terrain==='land'&&[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].some(([a,b])=>a>=0&&b>=0&&a<26&&b<26&&s.tiles[b*26+a].type==='road');}).sort((a,b)=>Math.hypot(a%26-10,Math.floor(a/26)-10)-Math.hypot(b%26-10,Math.floor(b/26)-10)).slice(0,3);openDialog('journey',`<span class="eyebrow">YOUR FIRST WORKSPACE</span><h2>이제, 내 이름이 붙은 작업실.</h2><p>수리비 20% 절감 · 창작 프로젝트의 시간당 진행량 +15%. 작업실은 별도 매출 없이 월 임대료·유지비가 나갑니다.</p><div class="journey-choices">${ids.map(i=>{const q=workspaceQuote(s,i);return button('claim',i,`<b>${i%26+1}번가 ${Math.floor(i/26)+1}번지</b><small>계약 ${cash(q.cost)} (보증금 ${cash(q.deposit)} 포함)<br>현재 월 임대·유지비 ${cash(q.rent)}</small>`,s.money<q.cost);}).join('')||'<p>빈 도로변 부지가 없습니다. 보유 부지를 정리한 뒤 다시 찾아주세요.</p>'}</div><p class="help">임대료는 토지가에 따라 변합니다. 계약 비용은 게임 자금에서 차감됩니다.</p>${button('open','','더 거래하고 돌아오기')}`);}
 function handle(b){const action=b.dataset.journey;if(!action)return false;const s=getState(),v=b.dataset.value;if(action==='open'){show();return true;}if(action==='plots'){plots();return true;}const r=action==='find'?selectFind(s,v):action==='inspect'?inspectFind(s):action==='buy'?purchaseFind(s,v):action==='repair'?repairFind(s,v):action==='sell'?sellFind(s,v):action==='leave'?leaveFind(s):action==='claim'?claimWorkspace(s,Number(v)):null;if(!r)return false;toast(r.msg);if(!r.ok)return true;changed();audio.play(action==='sell'?'coin':action==='claim'?'win':'build');
 if(action==='sell'){const g=chapterProgress(s);openDialog('journey',`<div class="journey-result">${art(r.sale.item,r.sale.fixed)}<span class="eyebrow">거래 완료 · ${BUYERS[v].name}</span><h2>${r.profit>=0?'가치를 알아본 대가.':'이번 거래에서 배운 것.'}</h2><strong class="${r.profit>=0?'positive':'negative'}">순이익 ${cash(r.profit)}</strong><p>판매 ${cash(r.sale.revenue)} − 총비용 ${cash(r.sale.spent)}</p><p>${r.msg}</p><div class="journey-note">${g.ready&&!g.done?'✦ 첫 작업실 계약 조건을 달성했습니다!':'수익 거래 '+Math.min(g.wins,3)+'/3 · 누적 이익 '+cash(g.profit)+' / ₲350'}<br>평판 +${r.sale.reputation}</div>${button(g.ready&&!g.done?'plots':'open','',g.ready&&!g.done?'내 작업실 마련하기 →':'다음 물건 찾아보기 →')}</div>`);renderer.burst(-1,'거래 이익 '+cash(r.profit),r.profit<0?'loss':'coin');}
 else if(action==='claim'){renderer.select(r.tile);renderer.visit(r.tile);renderer.burst(r.tile,'첫 작업실 OPEN!');openDialog('journey',`<div class="journey-result"><span class="key-reward">⚿</span><span class="eyebrow">CHAPTER 01 COMPLETE</span><h2>첫 작업실의 열쇠.</h2><p>버려진 물건에서 발견한 가치가<br>내가 일할 공간이 되었습니다.</p><div class="journey-note">현장 수리비 −20% · 창작 효율 +15%<br>지도에서 내 작업실을 찾아보세요.</div><button data-action="close" class="primary full">내 동네로 돌아가기 →</button></div>`);}
 else show();return true;}
 return{show,handle};
}
