import {constructionNotice} from './building-progress.js';
import {celebrationDialog} from './celebrations.js';
import {signatureGrowthPreview} from './signature-growth-ui.js';
import {landmarkAPI} from './landmark-api.js';
import {L} from './i18n.js';
import {coords,footprintCells,SIZE,expandMap} from './engine.js';
import {LANDMARK_LIMIT,ownedLandmarks,landmarkQuote,landmarkBuildError,buildLandmark,landmarkAnchor} from './landmark-construction.js';
import {validLandmark,landmarkPreview,landmarkURL} from './landmarks.js';
import {PRESET_LANDMARKS} from './landmark-presets.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
// With aiLandmarks off the studio is a catalogue of the built-in designs: no form, no design server.
export function createLandmarkUI({getState,openDialog,closeDialog,changed,toast,renderer,preparePlacement,features={},api=landmarkAPI}){
 const ai=!!features.aiLandmarks;
 let quota=null,quotaTimer;
 let designs=[],library=[],draft=null,pending=null,busy=false,signIn=false,lastForm={name:'',prompt:'',type:'office'},file=null,footprint={width:1,height:1};
 const current=()=>document.querySelector('#landmark-studio');
 const session=()=>{const s=getState();if(!s.landmarkStudio){s.landmarkStudio={id:crypto.randomUUID(),designs:[]};changed();}return s.landmarkStudio;};
 const gallery=()=>[...designs,...library.filter(d=>!designs.some(x=>x.id===d.id)),...PRESET_LANDMARKS].filter(d=>d.source!=='upload');
 const used=()=>quota&&Date.now()<quota.resetAt?quota.count:0;
 function updateQuota(value){
  if(!value||!Number.isInteger(value.count)||value.count<0||(value.count>3&&value.unlimited!==true)||!Number.isFinite(value.resetAt))return;
  quota=value;clearTimeout(quotaTimer);
  if(value.resetAt>Date.now()){quotaTimer=setTimeout(()=>{quota=null;if(current()){read();show();}},Math.min(value.resetAt-Date.now()+1,86400001));quotaTimer.unref?.();}
 }
 function remember(d){const work=session();if(!work.designs.some(x=>x.id===d.id))work.designs.push(d);work.selected=d.id;changed();}
 function restore(){const work=session();designs=work.designs;draft=gallery().find(d=>d.id===work.selected)||null;}
 function read(){const form=document.querySelector('#landmark-form');if(form){lastForm={name:form.elements.name.value,prompt:form.elements.prompt.value,type:form.elements.type.value};file=form.elements.image.files[0]||file;}}
 function form(){const markup=L`<form id="landmark-form"><label>Building name<input name="name" maxlength="40" required placeholder="e.g. Cloud Garden Tower" value="${esc(lastForm.name)}"></label><label>Operation<select name="type"><option value="office" ${lastForm.type==='office'?'selected':''}>Office Building</option><option value="hotel" ${lastForm.type==='hotel'?'selected':''}>Hotel</option></select></label><label>The building I want<textarea name="prompt" maxlength="1600" rows="4" placeholder="e.g. A futuristic hotel with a spiral glass facade, rooftop forest and golden entrance">${esc(lastForm.prompt)}</textarea></label><label>Reference image · PNG/JPEG/WebP, up to 5MB<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label>${file?L`<p class="help">Selected file: ${esc(file.name)}</p><button type="button" data-landmark="remove-image">Remove reference image</button>`:''}<p class="help">Both buttons use OpenAI and incur real API charges. Uploaded images are converted into game buildings. Each landmark allows 3 AI requests per day, resetting at midnight in Korea. Failed AI attempts count; requests rejected before reaching AI do not. The once-per-minute and 20-per-day account limits also apply. You must have the rights to any image you use.</p><p class="help">AI requests for this landmark today: ${used()} / 3 · Resets at 00:00 KST</p><div class="button-row"><button type="button" data-landmark="generate" class="primary" ${busy||(!quota?.unlimited&&used()>=3)||ownedLandmarks(getState())>=LANDMARK_LIMIT?'disabled':''}>${busy?L('AI is designing…'):L('Generate 1 AI Draft')}</button><button type="button" data-landmark="upload" ${busy||(!quota?.unlimited&&used()>=3)||ownedLandmarks(getState())>=LANDMARK_LIMIT?'disabled':''}>Create Building From Uploaded Image</button></div></form>`;return quota?.unlimited?markup.replace(L("Both buttons use OpenAI and incur real API charges. Uploaded images are converted into game buildings. Each landmark allows 3 AI requests per day, resetting at midnight in Korea. Failed AI attempts count; requests rejected before reaching AI do not. The once-per-minute and 20-per-day account limits also apply. You must have the rights to any image you use."),L("This account has unlimited AI image requests. Both buttons use OpenAI and incur real API charges. Uploaded images are converted into game buildings. You must have the rights to any image you use.")).replace(L`AI requests for this landmark today: ${used()} / 3 · Resets at 00:00 KST`,L`AI requests for this landmark today: ${used()} / Unlimited`):markup;}
 function show(message=''){openDialog('landmarks',`<div id="landmark-studio"><span class="eyebrow">MY LANDMARK STUDIO</span><h2>${ai?L('The building you imagine, in your city.'):L('A signature building for your city.')}</h2><p class="help">${L`Owned landmarks: ${ownedLandmarks(getState())} / ${LANDMARK_LIMIT}`}</p><p>${ai?L('Describe the look you want or upload a reference photo. Pick a design, then choose a lot on the map to build on.'):L('Pick one of the example designs below, set the lot size, then choose an empty lot on the map to build on.')}</p>${signatureGrowthPreview(getState())}${ai?form():''}<p role="status" id="landmark-status">${esc(message)}</p>${signIn?(api.remote?L('<p><button data-auth="google">Continue with Google</button></p>'):L('<p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT to use the studio</a></p>')):''}${draft&&!busy?landmarkPreview(draft)+L`<div class="field-grid">${['width','height'].map((key,n)=>L`<label>Lot ${n?L('height'):L('width')}<select data-landmark-size="${key}">${[1,2,3].map(v=>L`<option value="${v}" ${footprint[key]===v?'selected':''}>${v} ${v===1?'tile':'tiles'}</option>`).join('')}</select></label>`).join('')}</div><p class="help">Up to 3×3 tiles · Build cost ×100 · Rent/hotel revenue ×3 · Land purchase extra. Original image ratio is preserved.</p><button class="primary full" data-landmark="place" ${busy?'disabled':''}>Choose Build Site With This Design</button>`:''}${ai&&[...designs,...library].some(d=>d.source==='upload')?L('<p class="help">Previously uploaded originals are not AI buildings. Upload the image again to convert it before construction. Existing buildings are unchanged.</p>'):''}<h3>${ai?L('My Design Gallery'):L('Example Designs')}</h3><div class="landmark-library">${gallery().map(d=>`<button data-landmark-design="${d.id}" class="${draft?.id===d.id?'active':''}"><img src="${landmarkURL(d.id)}" alt="${esc(d.name)}" loading="lazy"><b>${esc(d.name)}</b><small>${d.type==='hotel'?L('Hotel'):L('Office Building')}</small></button>`).join('')}</div></div>`);}
 async function open(){const openedState=getState();if(!ai){show();return;}restore();show(L('Loading design gallery…'));try{const r=await api.call('/api/landmarks?constructionId='+encodeURIComponent(session().id));signIn=r.status===401;if(r.status===404)throw Error(L('AI designs require the connected landmark server. Example designs are still available.'));const j=await r.json();if(!r.ok)throw Error(j.error||L('Check your server connection.'));if(getState()!==openedState)return;updateQuota(j.quota);library=j.designs.filter(validLandmark);const work=session();for(const d of library.filter(d=>validLandmark(d)&&d.constructionId===work.id)){if(!work.designs.some(x=>x.id===d.id))work.designs.push(d);}changed();restore();if(current())show();}catch(e){signIn=e.status===401||signIn;if(current()&&getState()===openedState)show(L('Could not reach the design gallery: ')+e.message);}}
 async function submit(mode){if(busy||!ai)return;if(ownedLandmarks(getState())>=LANDMARK_LIMIT)return toast(L('You can own up to 5 landmarks. Sell or demolish one before building another.'));if((!quota?.unlimited&&used()>=3))return toast(L("This landmark has reached its daily limit of 3 AI requests. Try again after midnight in Korea."));read();if(!lastForm.name.trim())return toast(L('Enter a building name.'));if(mode==='generate'&&!lastForm.prompt.trim()&&!file)return toast(L('Add a description or a reference image.'));if(mode==='upload'&&!file)return toast(L('Select an image to use.'));if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024))return toast(L('Select a PNG/JPEG/WebP image up to 5MB.'));const work=session();busy=true;show(L('Creating a new design. This can take 1–2 minutes. Previous designs remain in your gallery.'));try{const data=new FormData();for(const [k,v]of Object.entries(lastForm))data.set(k,v);data.set('mode','generate');data.set('constructionId',work.id);if(file)data.set('image',file);const r=await api.call('/api/landmarks',{method:'POST',body:data});const j=await r.json();if(!r.ok)throw Object.assign(Error(j.error||L('Could not save the concept draft.')),{status:r.status,quota:j.quota});if(!validLandmark(j.design))throw Error(L('Could not verify the concept draft response.'));if(getState().landmarkStudio?.id!==work.id)throw Error(L('The active game changed. Reopen the studio.'));updateQuota(j.quota);draft=j.design;remember(draft);designs=work.designs;busy=false;if(current())show(L('Concept draft ready. Check the build cost after choosing a lot.'));else toast(L('Landmark concept draft done! Check it in the studio.'));}catch(e){if(getState().landmarkStudio?.id===work.id)updateQuota(e.quota);busy=false;signIn=e.status===401||signIn;if(current())show(e.message+L(' No game funds were deducted.'));else toast(e.message);}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-landmark],[data-landmark-design]');if(!b)return;e.preventDefault();if(b.dataset.landmarkDesign){read();draft=gallery().find(d=>d.id===b.dataset.landmarkDesign);if(ai){session().selected=draft?.id;changed();}show();return;}const action=b.dataset.landmark;if(action==='open'){read();open();}if(action==='remove-image'){read();file=null;show();}if(action==='generate'||action==='upload')submit(action);if(action==='place'&&draft&&!busy){pending={...draft};document.querySelectorAll('[data-landmark-size]').forEach(el=>footprint[el.dataset.landmarkSize]=Number(el.value));closeDialog();preparePlacement();renderer.setLandmarkPlacement(pending,footprint);toast(L('Click an empty lot next to a road. Press Esc to cancel.'));}if(action==='cancel'){pending=null;renderer.setLandmarkPlacement(null);closeDialog();}if(action==='confirm'&&pending){const s=getState();let i=Number(b.dataset.plot);if(!Number.isInteger(i)||s.tiles[i]?.type||s.tiles[i]?.owner)return toast(L('This lot is unavailable. Pick another empty lot.'));const result=buildLandmark(s,i,pending,footprint);if(!result.ok)return toast(result.msg);i=expandMap(s,i);delete s.landmarkStudio;quota=null;clearTimeout(quotaTimer);designs=[];draft=null;file=null;lastForm={name:'',prompt:'',type:'office'};pending=null;renderer.setLandmarkPlacement(null);changed();closeDialog();renderer.focus(i);openDialog('celebration',celebrationDialog('landmark',s.tiles[i].landmark.name,result.msg,landmarkPreview(s.tiles[i].landmark)));toast(result.msg+L(' · Monthly profit and value growth now apply.'));}});
 document.addEventListener('submit',e=>{if(e.target.id==='landmark-form')e.preventDefault();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){pending=null;renderer.setLandmarkPlacement(null);}});
 return{accountChanged(){quota=null;clearTimeout(quotaTimer);library=[];designs=[];draft=null;pending=null;file=null;lastForm={name:'',prompt:'',type:'office'};renderer.setLandmarkPlacement(null);if(current())closeDialog();},pick(clicked){if(!pending)return false;const s=getState(),t=s.tiles[clicked];if(!t||t.type||t.owner){toast(L('Build landmarks on an empty lot next to a road.'));return true;}const i=landmarkAnchor(s,clicked,pending,footprint)??clicked;if(!footprintCells(i,footprint).length){toast(L('The selected size runs off the map. Pick another lot.'));return true;}const reason=landmarkBuildError(s,i,pending,footprint);const q=landmarkQuote(s,i,pending.type,footprint),c=coords(i),far=coords(i+(footprint.height-1)*SIZE+footprint.width-1);openDialog('landmark-contract','<p>'+constructionNotice(60)+'</p>'+signatureGrowthPreview(s,q.construction)+L('<p class="help">Once built, this landmark design cannot be changed. Generate and choose your final design before confirming construction.</p>')+L`${landmarkPreview(pending)}<h3>Build on ${footprint.width}×${footprint.height} tiles?</h3>${reason?L`<p role="alert">${esc(reason)} The lot grows right and down from the tile you click, and nearby positions that still cover that tile were tried too.</p>`:''}<p>Location ${c.x+1}, ${c.y+1}${footprint.width*footprint.height>1?L` to ${far.x+1}, ${far.y+1}`:''} · ${q.label}</p><div class="asset-profit"><p>Landmark build cost (×100) ${money(q.construction)} + Land ${money(q.land)}</p><strong>Total ${money(q.total)}</strong><p><b>Completion bonus · Reputation +${q.fame.toLocaleString('en-US')}</b></p><p class="help">+500 to 1,300 points by area. On the same lot only the amount above the previous best bonus is paid.</p><p>Monthly revenue (×3) ${money(q.revenue)} − Upkeep ${money(q.cost)}</p><p>Expected monthly profit ${money(q.profit)}</p></div><p>Standard build, operation, expansion and sale rules for the chosen business apply. Generating a design alone deducts no game funds.</p><div class="button-row"><button class="primary" data-landmark="confirm" data-plot="${i}" ${reason?'disabled':''}>Confirm Landmark Build</button><button data-landmark="cancel">Cancel</button></div>`);return true;}};
}
