import {coords,footprintCells,SIZE} from './engine.js';
import {landmarkQuote,landmarkBuildError,buildLandmark,landmarkAnchor} from './landmark-construction.js';
import {validLandmark,landmarkPreview,landmarkURL} from './landmarks.js';
import {PRESET_LANDMARKS} from './landmark-presets.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
// With aiLandmarks off the studio is a catalogue of the built-in designs: no form, no design server.
export function createLandmarkUI({getState,openDialog,closeDialog,changed,toast,renderer,preparePlacement,features={}}){
 const ai=!!features.aiLandmarks;
 let designs=[],draft=null,pending=null,busy=false,lastForm={name:'',prompt:'',type:'office'},file=null,footprint={width:1,height:1};
 const current=()=>document.querySelector('#landmark-studio');
 const gallery=()=>[...designs,...PRESET_LANDMARKS];
 function read(){const form=document.querySelector('#landmark-form');if(form){lastForm={name:form.elements.name.value,prompt:form.elements.prompt.value,type:form.elements.type.value};file=form.elements.image.files[0]||file;}}
 function form(){return `<form id="landmark-form"><label>Building name<input name="name" maxlength="40" required placeholder="e.g. Cloud Garden Tower" value="${esc(lastForm.name)}"></label><label>Operation<select name="type"><option value="office" ${lastForm.type==='office'?'selected':''}>Office Building</option><option value="hotel" ${lastForm.type==='hotel'?'selected':''}>Hotel</option></select></label><label>The building I want<textarea name="prompt" maxlength="1600" rows="4" placeholder="e.g. A futuristic hotel with a spiral glass facade, rooftop forest and golden entrance">${esc(lastForm.prompt)}</textarea></label><label>Reference image · PNG/JPEG/WebP, up to 5MB<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label>${file?`<p class="help">Selected file: ${esc(file.name)}</p>`:''}<p class="help">AI generation sends your description and reference image to OpenAI and incurs real API charges. One image per request, once per minute, up to 20 per day. Direct uploads carry no AI fee. You must have the rights to any image you use.</p><div class="button-row"><button type="button" data-landmark="generate" class="primary" ${busy?'disabled':''}>${busy?'AI is designing…':'Generate 1 AI Draft'}</button><button type="button" data-landmark="upload" ${busy?'disabled':''}>Use Uploaded Image As Is</button></div></form>`;}
 function show(message=''){openDialog('landmarks',`<div id="landmark-studio"><span class="eyebrow">MY LANDMARK STUDIO</span><h2>${ai?'The building you imagine, in your city.':'A signature building for your city.'}</h2><p>${ai?'Describe the look you want or upload a reference photo. Pick a design, then choose a lot on the map to build on.':'Pick one of the example designs below, set the lot size, then choose an empty lot on the map to build on.'}</p>${ai?form():''}<p role="status" id="landmark-status">${esc(message)}</p>${message.includes('sign in')?'<p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT to use the studio</a></p>':''}${draft?landmarkPreview(draft)+`<div class="field-grid">${['width','height'].map((key,n)=>`<label>Lot ${n?'height':'width'}<select data-landmark-size="${key}">${[1,2,3].map(v=>`<option value="${v}" ${footprint[key]===v?'selected':''}>${v} ${v===1?'tile':'tiles'}</option>`).join('')}</select></label>`).join('')}</div><p class="help">Up to 3×3 tiles · Build cost ×100 · Rent/hotel revenue ×10 · Land purchase extra. Original image ratio is preserved.</p><button class="primary full" data-landmark="place">Choose Build Site With This Design</button>`:''}<h3>${ai?'My Design Gallery':'Example Designs'}</h3><div class="landmark-library">${gallery().map(d=>`<button data-landmark-design="${d.id}" class="${draft?.id===d.id?'active':''}"><img src="${landmarkURL(d.id)}" alt="${esc(d.name)}" loading="lazy"><b>${esc(d.name)}</b><small>${d.type==='hotel'?'Hotel':'Office Building'}</small></button>`).join('')}</div></div>`);}
 async function open(){if(!ai){show();return;}show('Loading design gallery…');try{const r=await fetch('/api/landmarks');const j=await r.json();if(!r.ok)throw Error(j.error||'Check your server connection.');designs=j.designs.filter(validLandmark);if(current())show();}catch(e){if(current())show('Could not reach the design gallery: '+e.message);}}
 async function submit(mode){if(busy||!ai)return;read();if(!lastForm.name.trim())return toast('Enter a building name.');if(mode==='generate'&&!lastForm.prompt.trim()&&!file)return toast('Add a description or a reference image.');if(mode==='upload'&&!file)return toast('Select an image to use.');if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024))return toast('Select a PNG/JPEG/WebP image up to 5MB.');busy=true;show(mode==='generate'?'Generating your concept draft. This can take 1–2 minutes.':'Saving your image.');try{const data=new FormData();for(const [k,v]of Object.entries(lastForm))data.set(k,v);data.set('mode',mode);if(file)data.set('image',file);const r=await fetch('/api/landmarks',{method:'POST',body:data});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not save the concept draft.');if(!validLandmark(j.design))throw Error('Could not verify the concept draft response.');draft=j.design;designs=[draft,...designs.filter(d=>d.id!==draft.id)];busy=false;if(current())show('Concept draft ready. Check the build cost after choosing a lot.');else toast('Landmark concept draft done! Check it in the studio.');}catch(e){busy=false;if(current())show(e.message+' No game funds were deducted.');else toast(e.message);}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-landmark],[data-landmark-design]');if(!b)return;e.preventDefault();if(b.dataset.landmarkDesign){read();draft=gallery().find(d=>d.id===b.dataset.landmarkDesign);show();return;}const action=b.dataset.landmark;if(action==='open')open();if(action==='generate'||action==='upload')submit(action);if(action==='place'&&draft){pending={...draft};document.querySelectorAll('[data-landmark-size]').forEach(el=>footprint[el.dataset.landmarkSize]=Number(el.value));closeDialog();preparePlacement();toast('Click an empty lot next to a road. Press Esc to cancel.');}if(action==='cancel'){pending=null;closeDialog();}if(action==='confirm'&&pending){const s=getState(),i=Number(b.dataset.plot);if(!Number.isInteger(i)||s.tiles[i]?.type||s.tiles[i]?.owner)return toast('This lot is unavailable. Pick another empty lot.');const result=buildLandmark(s,i,pending,footprint);if(!result.ok)return toast(result.msg);pending=null;changed();closeDialog();renderer.focus(i);toast(result.msg+' · Monthly profit and value growth now apply.');}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')pending=null;});
 return{pick(clicked){if(!pending)return false;const s=getState(),t=s.tiles[clicked];if(!t||t.type||t.owner){toast('Build landmarks on an empty lot next to a road.');return true;}const i=landmarkAnchor(s,clicked,pending,footprint)??clicked;if(!footprintCells(i,footprint).length){toast('The selected size runs off the map. Pick another lot.');return true;}const reason=landmarkBuildError(s,i,pending,footprint);const q=landmarkQuote(s,i,pending.type,footprint),c=coords(i),far=coords(i+(footprint.height-1)*SIZE+footprint.width-1);openDialog('landmark-contract',`${landmarkPreview(pending)}<h3>Build on ${footprint.width}×${footprint.height} tiles?</h3>${reason?`<p role="alert">${esc(reason)} The lot grows right and down from the tile you click, and nearby positions that still cover that tile were tried too.</p>`:''}<p>Location ${c.x+1}, ${c.y+1}${footprint.width*footprint.height>1?` to ${far.x+1}, ${far.y+1}`:''} · ${q.label}</p><div class="asset-profit"><p>Landmark build cost (×100) ${money(q.construction)} + Land ${money(q.land)}</p><strong>Total ${money(q.total)}</strong><p><b>Completion bonus · Reputation +${q.fame.toLocaleString('en-US')}</b></p><p class="help">+500 to 1,300 points by area. On the same lot only the amount above the previous best bonus is paid.</p><p>Monthly revenue (×10) ${money(q.revenue)} − Upkeep ${money(q.cost)}</p><p>Expected monthly profit ${money(q.profit)}</p></div><p>Standard build, operation, expansion and sale rules for the chosen business apply. Generating a design alone deducts no game funds.</p><div class="button-row"><button class="primary" data-landmark="confirm" data-plot="${i}" ${reason?'disabled':''}>Confirm Landmark Build</button><button data-landmark="cancel">Cancel</button></div>`);return true;}};
}
