import {coords,footprintCells} from './engine.js';
import {landmarkQuote,landmarkBuildError,buildLandmark} from './landmark-construction.js';
import {validLandmark,landmarkPreview} from './landmarks.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
export function createLandmarkUI({getState,openDialog,closeDialog,changed,toast,renderer,preparePlacement}){
 let designs=[],draft=null,pending=null,busy=false,lastForm={name:'',prompt:'',type:'office'},file=null,footprint={width:1,height:1};
 const current=()=>document.querySelector('#landmark-studio');
 function read(){const form=document.querySelector('#landmark-form');if(form){lastForm={name:form.elements.name.value,prompt:form.elements.prompt.value,type:form.elements.type.value};file=form.elements.image.files[0]||file;}}
 function show(message=''){openDialog('landmarks',`<div id="landmark-studio"><span class="eyebrow">MY LANDMARK STUDIO</span><h2>상상한 건물을, 나의 도시에.</h2><p>원하는 외관을 설명하거나 참고 사진을 올리세요. 디자인을 선택한 다음 지도에서 건설할 부지를 고릅니다.</p><form id="landmark-form"><label>건물 이름<input name="name" maxlength="40" required placeholder="예: 구름 정원 타워" value="${esc(lastForm.name)}"></label><label>운영 방식<select name="type"><option value="office" ${lastForm.type==='office'?'selected':''}>임대 빌딩</option><option value="hotel" ${lastForm.type==='hotel'?'selected':''}>호텔</option></select></label><label>내가 원하는 건물<textarea name="prompt" maxlength="1600" rows="4" placeholder="예: 나선형 유리 외벽, 옥상 숲, 금빛 입구가 있는 미래적인 호텔">${esc(lastForm.prompt)}</textarea></label><label>참고 이미지 · PNG/JPEG/WebP, 5MB 이하<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label>${file?`<p class="help">선택된 파일: ${esc(file.name)}</p>`:''}<p class="help">AI 생성은 설명·참고 이미지를 OpenAI로 전송하며 실제 API 이용료가 발생합니다. 한 번에 1장 생성하며, 분당 1회·하루 최대 20회입니다. 직접 업로드는 AI 이용료가 없습니다. 이미지에는 사용할 권리가 있어야 합니다.</p><div class="button-row"><button type="button" data-landmark="generate" class="primary" ${busy?'disabled':''}>${busy?'AI가 설계 중…':'AI 시안 1장 생성'}</button><button type="button" data-landmark="upload" ${busy?'disabled':''}>업로드 이미지를 그대로 사용</button></div></form><p role="status" id="landmark-status">${esc(message)}</p>${message.includes('로그인')?'<p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">ChatGPT로 로그인하고 설계실 사용하기</a></p>':''}${draft?landmarkPreview(draft)+`<div class="field-grid">${['width','height'].map((key,n)=>`<label>${n?'세로':'가로'} 부지<select data-landmark-size="${key}">${[1,2,3].map(v=>`<option value="${v}" ${footprint[key]===v?'selected':''}>${v}칸</option>`).join('')}</select></label>`).join('')}</div><p class="help">최대 3×3칸 · 건설비 100배 · 임대·호텔 매출 10배 · 토지 매입비 별도. 원본 이미지 비율은 유지됩니다.</p><button class="primary full" data-landmark="place">이 디자인으로 건설 위치 선택</button>`:''}<h3>나의 설계 보관함</h3><div class="landmark-library">${designs.map(d=>`<button data-landmark-design="${d.id}"><img src="/api/landmarks/${d.id}/image" alt="${esc(d.name)}" loading="lazy"><b>${esc(d.name)}</b></button>`).join('')||'<p>완성한 시안이 이곳에 보관됩니다.</p>'}</div></div>`);}
 async function open(){show('설계 보관함을 불러오는 중…');try{const r=await fetch('/api/landmarks');const j=await r.json();if(!r.ok)throw Error(j.error||'서버 연결을 확인해 주세요.');designs=j.designs.filter(validLandmark);if(current())show();}catch(e){if(current())show('설계 보관함 연결 실패: '+e.message);}}
 async function submit(mode){if(busy)return;read();if(!lastForm.name.trim())return toast('건물 이름을 입력하세요.');if(mode==='generate'&&!lastForm.prompt.trim()&&!file)return toast('설명 또는 참고 이미지를 넣어주세요.');if(mode==='upload'&&!file)return toast('사용할 이미지를 선택하세요.');if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024))return toast('PNG/JPEG/WebP 이미지 5MB 이하를 선택하세요.');busy=true;show(mode==='generate'?'시안을 만드는 중입니다. 1~2분 정도 걸릴 수 있습니다.':'이미지를 저장하는 중입니다.');try{const data=new FormData();for(const [k,v]of Object.entries(lastForm))data.set(k,v);data.set('mode',mode);if(file)data.set('image',file);const r=await fetch('/api/landmarks',{method:'POST',body:data});const j=await r.json();if(!r.ok)throw Error(j.error||'시안을 저장하지 못했습니다.');if(!validLandmark(j.design))throw Error('시안 응답을 확인할 수 없습니다.');draft=j.design;designs=[draft,...designs.filter(d=>d.id!==draft.id)];busy=false;if(current())show('시안이 준비되었습니다. 건설 비용은 부지를 고른 뒤 확인하세요.');else toast('랜드마크 시안 완성! 설계실에서 확인하세요.');}catch(e){busy=false;if(current())show(e.message+' 게임 자금은 차감되지 않았습니다.');else toast(e.message);}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-landmark],[data-landmark-design]');if(!b)return;e.preventDefault();if(b.dataset.landmarkDesign){read();draft=designs.find(d=>d.id===b.dataset.landmarkDesign);show();return;}const action=b.dataset.landmark;if(action==='open')open();if(action==='generate'||action==='upload')submit(action);if(action==='place'&&draft){pending={...draft};document.querySelectorAll('[data-landmark-size]').forEach(el=>footprint[el.dataset.landmarkSize]=Number(el.value));closeDialog();preparePlacement();toast('도로 옆 빈 부지를 클릭하세요. Esc로 취소할 수 있습니다.');}if(action==='cancel'){pending=null;closeDialog();}if(action==='confirm'&&pending){const s=getState(),i=Number(b.dataset.plot);if(!Number.isInteger(i)||s.tiles[i]?.type||s.tiles[i]?.owner)return toast('이 부지를 사용할 수 없습니다. 빈 부지를 다시 선택하세요.');const result=buildLandmark(s,i,pending,footprint);if(!result.ok)return toast(result.msg);pending=null;changed();closeDialog();renderer.focus(i);toast(result.msg+' · 월 수익과 가치 상승이 적용됩니다.');}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')pending=null;});
 return{pick(i){if(!pending)return false;const s=getState(),t=s.tiles[i];if(!t||t.type||t.owner){toast('랜드마크는 도로 옆 빈 부지에 건설하세요.');return true;}if(!footprintCells(i,footprint).length){toast('선택한 크기가 지도 밖으로 나갑니다. 다른 부지를 선택하세요.');return true;}const reason=landmarkBuildError(s,i,pending,footprint);const q=landmarkQuote(s,i,pending.type,footprint),c=coords(i);openDialog('landmark-contract',`${landmarkPreview(pending)}<h3>${footprint.width}×${footprint.height}칸에 건설할까요?</h3>${reason?`<p role="alert">${esc(reason)}</p>`:''}<p>위치 ${c.x+1}, ${c.y+1} · ${q.label}</p><div class="asset-profit"><p>랜드마크 건설비 (100배) ${money(q.construction)} + 토지 ${money(q.land)}</p><strong>총 ${money(q.total)}</strong><p><b>완공 보너스 · 명성 +${q.fame.toLocaleString('ko-KR')}</b></p><p class="help">면적에 따라 +500~1,300점. 같은 부지는 기존 최고 보너스를 넘는 차이만 지급합니다.</p><p>월 매출 (10배) ${money(q.revenue)} − 유지비 ${money(q.cost)}</p><p>예상 월 순수익 ${money(q.profit)}</p></div><p>선택한 업종의 일반 건설·운영·확장·매각 규칙을 따릅니다. 디자인 생성만으로 게임 자금은 차감되지 않습니다.</p><div class="button-row"><button class="primary" data-landmark="confirm" data-plot="${i}" ${reason?'disabled':''}>랜드마크 건설 확정</button><button data-landmark="cancel">취소</button></div>`);return true;}};
}
