import {L} from './i18n.js';
import {awardAssetFame} from './reputation.js';
export const MANSION_SIZES={1:{name:L('Compact'),area:120},2:{name:L('Grand'),area:200},3:{name:L('Estate'),area:320},4:{name:L('Palace'),area:800},5:{name:L('Private Kingdom'),area:2000}};
export const MANSION_STYLES={modern:L('Modern Villa'),classic:L('Classic Palace'),resort:L('Resort House')};
export const MANSION_COLORS={ivory:'#e9ddc5',white:'#edf1eb',charcoal:'#57656a',terracotta:'#c88970'};
export const MANSION_ROOFS={flat:L('Flat roof'),gable:L('Gable roof'),terrace:L('Rooftop terrace')};
export const DEFAULT_MANSION=Object.freeze({size:2,floors:2,rooms:6,style:'classic',color:'ivory',roof:'gable',pool:true,garden:true,cinema:false,golf:false,spa:false,helipad:false});
export const mansionDesign=s=>({...DEFAULT_MANSION,...s.flex?.mansion});
export const mansionArea=d=>d.area??MANSION_SIZES[d.size].area;
export const roomCapacity=d=>Math.min(120,Math.floor(mansionArea(d)/50)*d.floors);
export const MANSION_EXTRAS={cinema:{name:L('Private cinema'),price:250000},golf:{name:L('Private golf course'),price:1500000},spa:{name:L('Wellness spa'),price:400000},helipad:{name:L('Private helipad'),price:2500000}};
export const MANSION_MAINTENANCE_RATE=.004;
export function validMansion(d){return !!d&&Object.keys(d).every(k=>Object.hasOwn(DEFAULT_MANSION,k)||k==='area')&&Number.isInteger(d.size)&&Object.hasOwn(MANSION_SIZES,d.size)&&(d.area===undefined||Number.isInteger(d.area)&&d.area>=120&&d.area<=10000)&&Number.isInteger(d.floors)&&d.floors>=1&&d.floors<=10&&Number.isInteger(d.rooms)&&d.rooms>=2&&d.rooms<=roomCapacity(d)&&Object.hasOwn(MANSION_STYLES,d.style)&&Object.hasOwn(MANSION_COLORS,d.color)&&Object.hasOwn(MANSION_ROOFS,d.roof)&&typeof d.pool==='boolean'&&typeof d.garden==='boolean'&&Object.keys(MANSION_EXTRAS).every(k=>d[k]===undefined||typeof d[k]==='boolean');}
export function mansionBreakdown(d){const area=mansionArea(d),structure=17000+d.size*3000+d.floors*3000+d.rooms*500+Math.round(35*Math.max(0,area-200)**1.8)+Math.round(30000*Math.max(0,d.floors-2)**2.5)+Math.round(2500*Math.max(0,d.rooms-6)**2),finish=({modern:25000,classic:0,resort:75000}[d.style])+({ivory:0,white:12000,charcoal:30000,terracotta:22000}[d.color])+({flat:0,gable:0,terrace:90000}[d.roof]),facilities=(d.pool?2000:0)+(d.garden?1000:0)+Object.entries(MANSION_EXTRAS).reduce((sum,[k,v])=>sum+(d[k]?v.price:0),0),count=Object.keys(MANSION_EXTRAS).filter(k=>d[k]).length,multiplier=2.4**count;return{structure,finish,facilities,multiplier,total:Math.round((structure+finish+facilities)*multiplier)};}
export function designValue(d){return mansionBreakdown(d).total;}
export function mansionMaintenance(d){return Math.round(designValue(d)*MANSION_MAINTENANCE_RATE);}
const same=(a,b)=>Object.keys(DEFAULT_MANSION).every(k=>(a[k]??DEFAULT_MANSION[k])===(b[k]??DEFAULT_MANSION[k]))&&mansionArea(a)===mansionArea(b);
export function mansionQuote(s,d,wealth){
 if(!validMansion(d))return{cost:0,error:L('Check your design values.')};
 const owned=s.flex?.owned.includes('penthouse'),old=mansionDesign(s),cost=owned?(same(old,d)?0:1500+Math.max(0,designValue(d)-designValue(old))):designValue(d);
 const error=!owned&&s.mode!=='sandbox'&&Math.max(s.highestWealth,wealth)<100000?L('Reach a peak net worth of ₲100,000 to build'):owned&&same(old,d)?L('Same design as your current mansion.'):s.money<cost?L('Not enough cash to build.'):null;
 return{cost,error,owned};
}
export function buildMansion(s,d,wealth){const q=mansionQuote(s,d,wealth);if(q.error)return{ok:false,msg:q.error};s.flex??={owned:[],lastParty:-1};if(!q.owned)s.flex.owned.push('penthouse');s.flex.mansion={...DEFAULT_MANSION,...d};s.money-=q.cost;s.highestWealth=Math.max(s.highestWealth,wealth);s.log.unshift(L`🏛 Mansion ${q.owned?L('remodel'):L('build')} complete · ${MANSION_SIZES[d.size].name} · ${d.floors} floors · ${d.rooms} rooms · ₲${q.cost.toLocaleString('en-US')}`);s.log=s.log.slice(0,25);awardAssetFame(s,'mansion',designValue(d),L('Mansion completed'));return{ok:true,msg:L('Your mansion is complete! The design now shows on the map.')};}
export function mansionArt(d){const width=160+Math.min(5,d.size)*38,left=320-width/2,height=Math.min(150,d.floors*30),top=216-height,col=MANSION_COLORS[d.color],windows=Math.ceil(d.rooms/d.floors);let panes='';for(let floor=0;floor<d.floors;floor++){const count=Math.min(windows,d.rooms-floor*windows);for(let n=0;n<count;n++){const x=left+18+n*(width-36)/windows,y=top+5+floor*(height/d.floors);panes+=`<rect x="${x}" y="${y}" width="${Math.max(2,(width-48)/windows-3)}" height="${Math.max(4,height/d.floors-8)}" rx="${d.style==='classic'?8:1}" fill="${d.style==='modern'?'#81bac7':'#ecd295'}" stroke="#516770" stroke-width="2"/>`;}}
 const roof=d.roof==='gable'?`<path d="M${left-14} ${top}L320 ${top-39}L${left+width+14} ${top}Z" fill="${d.style==='resort'?'#b67e60':'#72858a'}"/>`:`<rect x="${left-9}" y="${top-8}" width="${width+18}" height="8" fill="#526b70"/>${d.roof==='terrace'?`<path d="M${left} ${top-9}V${top-25}H${left+width}V${top-9}" fill="none" stroke="#a9c5c3" stroke-width="3"/><rect x="${left+22}" y="${top-22}" width="36" height="14" rx="5" fill="#ccad76"/>`:''}`;
 return L`<svg viewBox="0 0 640 300" class="mansion-art" role="img" aria-label="${MANSION_STYLES[d.style]}, ${MANSION_SIZES[d.size].name}, ${d.floors} floors, ${d.rooms} rooms${d.pool?L(', pool'):''}${d.garden?L(', garden'):''}"><rect width="640" height="300" rx="16" fill="#dae7e4"/><circle cx="542" cy="51" r="26" fill="#f8e5b8"/><path d="M0 216Q180 188 320 216T640 205V300H0Z" fill="#b6c7a4"/><path d="M270 216H360L410 300H226Z" fill="#ded6c2"/><rect x="${left+14}" y="${top+10}" width="${width}" height="${height}" fill="#78908c"/><rect x="${left}" y="${top}" width="${width}" height="${height}" fill="${col}"/>${panes}${roof}${d.style==='classic'?[left+5,left+width-12].map(x=>`<rect x="${x}" y="${top+4}" width="7" height="${height-4}" fill="#fff0d1"/>`).join(''):''}${d.style==='resort'?`<path d="M${left-10} 186H${left+width+10}" stroke="#b1835a" stroke-width="9"/>`:''}<rect x="304" y="187" width="32" height="29" fill="#47656c"/><circle cx="329" cy="203" r="2" fill="#e9c57a"/>${d.pool?'<rect x="379" y="238" width="176" height="44" rx="15" fill="#eee2c9"/><rect x="386" y="244" width="162" height="31" rx="10" fill="#62b8ce"/><path d="M400 255H531M414 264H510" stroke="#ade2e9" stroke-width="2"/>':''}${d.garden?[80,123,584].map((x,i)=>`<path d="M${x} 252V218" stroke="#897258" stroke-width="5"/><circle cx="${x}" cy="213" r="${19+i*3}" fill="#638f6c"/><circle cx="${x-6}" cy="204" r="14" fill="#85ac7e"/>`).join(''):''}<text x="24" y="282" fill="#37595b" font-size="12">${mansionArea(d)*d.floors}㎡ · ${d.floors} floors · ${d.rooms} rooms</text></svg>`;
}
export function floorPlan(d){const counts=Array.from({length:d.floors},(_,i)=>Math.floor(d.rooms/d.floors)+(i<d.rooms%d.floors?1:0));return L`<div class="mansion-plans">${counts.map((count,i)=>L`<section><b>Floor ${i+1} · ${count} rooms</b><div class="mansion-rooms">${Array.from({length:count},(_,n)=>`<span>${i===0&&n===0?L('Living room'):i===0&&n===1?L('Kitchen'):n===0?L('Bedroom'):n===1?L('Study','room'):L('Multipurpose room')}</span>`).join('')||L('<span>Open lounge</span>')}</div></section>`).join('')}</div><p class="help">A concept floor plan splitting the rooms by floor. Rooms include the living room and kitchen; hallways, stairs and bathrooms are separate shared space.</p>`;}
const MANSION_MOODS={
 classic:{title:L('Time passes. Elegance stays.'),text:L('Warm stone and a balanced facade. A classic residence that makes every homecoming special.'),tag:'THE HERITAGE'},
 modern:{title:L('Open views, unhurried days.'),text:L('Light-filled glass and restrained lines. A modern residence where the space itself is the statement.'),tag:'THE MODERN'},
 resort:{title:L('Every day at home, like a holiday.'),text:L('Natural colors and soft materials. A resort residence where rest begins without going anywhere.'),tag:'THE RETREAT'}
};
const mansionMoney=n=>'₲'+Math.round(n).toLocaleString('en-US');
export function mansionPreview(s,d,wealth){
 const q=mansionQuote(s,d,wealth),cost=mansionBreakdown(d),mood=MANSION_MOODS[d.style],facilities=[...(d.pool?[L('Private pool')]:[]),...(d.garden?[L('Landscaped garden')]:[]),...Object.entries(MANSION_EXTRAS).filter(([k])=>d[k]).map(([,v])=>v.name)];
 return L`${mansionSitePreview(d,{area:mansionArea(d),color:MANSION_COLORS[d.color],styleName:MANSION_STYLES[d.style]})}<details class="estate-inspiration"><summary>Architectural style image <span>${MANSION_STYLES[d.style]} ＋</span></summary><figure class="estate-hero"><img src="./city/assets/luxury/mansion-${d.style}.png" width="1536" height="1024" alt="${MANSION_STYLES[d.style]} style reference image"><figcaption><span>${mood.tag} / PRIVATE RESIDENCE</span><h3>${mood.title}</h3><p>${mood.text}</p></figcaption><span class="estate-preview-tag">Architectural style reference</span></figure></details>
 <div class="estate-specs"><div><span>Total floor area</span><strong>${(mansionArea(d)*d.floors).toLocaleString('en-US')}<small> ㎡</small></strong></div><div><span>Floors</span><strong>${d.floors}<small> floors</small></strong></div><div><span>Private spaces</span><strong>${d.rooms}<small> rooms</small></strong></div><div><span>Exterior style</span><b>${MANSION_STYLES[d.style]}</b></div></div>
 <p class="estate-image-note">The rendering is a concept bird's-eye view reflecting your chosen facilities, finish and roof. Layout and proportions are illustrative. You can design freely even without the cash.</p>
 <section class="estate-quote" aria-label="Construction quote"><div class="estate-quote-head"><div><span>${q.owned?L('My mansion remodel'):L('My first private mansion')}</span><strong>${mansionMoney(q.cost)}</strong></div><span class="estate-quote-seal">DESIGNED<br>FOR YOU</span></div><div class="estate-quote-meta"><span>Monthly upkeep <b>${mansionMoney(mansionMaintenance(d))}</b></span><span>Cash after build <b>${mansionMoney(s.money-q.cost)}</b></span></div><button data-action="mansion-build" ${q.error?'disabled':''}>${q.error||L('Start life in this mansion →')}</button><p>${q.owned?L('A remodel costs a base ₲1,500 plus any increase in design value. No refund when downsizing.'):L('New builds unlock at a peak net worth of ₲100,000.')} Construction costs come out of cash and net worth; monthly upkeep is 0.4% of design value.</p></section>
 <details class="estate-detail"><summary>Design summary and layout <span>View plans ＋</span></summary><div class="estate-design-summary"><b>${MANSION_STYLES[d.style]} · ${MANSION_ROOFS[d.roof]}</b><span>Per floor ${mansionArea(d).toLocaleString('en-US')}㎡ · ${({ivory:L('Warm ivory'),white:L('Pure white'),charcoal:L('Charcoal gray'),terracotta:L('Terracotta')})[d.color]}</span><p>${facilities.length?facilities.join(' · '):L('No extra facilities — a space focused on pure architecture')}</p></div>${mansionArt(d)}${floorPlan(d)}</details>
 <details class="estate-detail"><summary>Construction cost breakdown <span>View quote ＋</span></summary><dl class="estate-costs"><div><dt>Structure</dt><dd>${mansionMoney(cost.structure)}</dd></div><div><dt>Finish · roof</dt><dd>${mansionMoney(cost.finish)}</dd></div><div><dt>Facilities</dt><dd>${mansionMoney(cost.facilities)}</dd></div><div><dt>Luxury facility multiplier</dt><dd>×${cost.multiplier.toFixed(2)}</dd></div><div><dt>New-build total</dt><dd>${mansionMoney(cost.total)}</dd></div></dl><p class="help">Each cinema, golf course, spa or helipad you add multiplies the whole quote by ×2.4. Structure costs also rise non-linearly with area, floors and room count.</p></details>`;
}
export function mansionDialog(s,d,wealth){
 const select=(key,title,values)=>`<label>${title}<select data-mansion="${key}">${Object.entries(values).map(([v,name])=>`<option value="${v}" ${String(d[key])===v?'selected':''}>${name}</option>`).join('')}</select></label>`;
 const amenities={pool:[L('Private pool'),L('Your own waterfront under the sun')],garden:[L('Landscaped garden'),L('Mornings that start with a stroll')],cinema:[L('Private cinema'),L('First in line for your favorite film')],golf:[L('Private golf course'),L('A round right outside your door')],spa:[L('Wellness spa'),L('Where the day slowly unwinds')],helipad:[L('Private helipad'),L('A home connected to anywhere')]};
 return L`<div class="mansion-studio"><header class="estate-header"><div><span class="eyebrow">THE PRIVATE RESIDENCE COLLECTION</span><h2>The home you dreamed of, and a life beyond it.</h2><p>Pick your taste, fill the space. Your own mansion takes shape.</p></div><span class="estate-edition">RESIDENCE<br>ATELIER <i>01 — 03</i></span></header><div class="estate-layout"><div id="mansion-preview" aria-live="polite">${mansionPreview(s,d,wealth)}</div><div class="estate-controls">
 <fieldset class="estate-section"><legend><span>01</span> Architectural taste</legend><p>Three styles to hold your life.</p><div class="estate-style-options">${Object.entries(MANSION_STYLES).map(([key,name])=>`<label class="estate-style"><input type="radio" name="mansion-style" data-mansion="style" value="${key}" ${d.style===key?'checked':''}><img src="./city/assets/luxury/mansion-${key}.png" alt="" width="1536" height="1024"><span>${name}</span></label>`).join('')}</div></fieldset>
 <fieldset class="estate-section"><legend><span>02</span> Spaces just for you</legend><div class="estate-amenities">${Object.entries(amenities).map(([key,[name,description]])=>`<label><input type="checkbox" data-mansion="${key}" ${d[key]?'checked':''}><span><b>${name}</b><small>${description}</small></span></label>`).join('')}</div><p class="estate-facility-note">Cinema, golf, spa and helipad each multiply the whole quote by ×2.4. The quote updates as you select.</p></fieldset>
 <fieldset class="estate-section"><legend><span>03</span> Room to breathe</legend><div class="estate-fields">${select('size',L('Mansion size'),Object.fromEntries(Object.entries(MANSION_SIZES).map(([k,v])=>[k,v.name+' · '+v.area+'㎡'])))}<label>Area per floor (㎡)<input data-mansion="area" type="number" min="120" max="10000" step="10" value="${mansionArea(d)}"></label>${select('floors',L('Floors'),Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,(i+1)+L('-story')])))}<label>Total rooms<input data-mansion="rooms" type="number" min="2" max="${roomCapacity(d)}" step="1" value="${d.rooms}"></label></div><small id="mansion-capacity">2–${roomCapacity(d)} at this size</small></fieldset>
 <fieldset class="estate-section"><legend><span>04</span> Finishing details</legend><span class="estate-field-title">Exterior color</span><div class="estate-swatches">${Object.entries({ivory:L('Warm ivory'),white:L('Pure white'),charcoal:L('Charcoal gray'),terracotta:L('Terracotta')}).map(([key,name])=>`<label title="${name}"><input type="radio" name="mansion-color" data-mansion="color" value="${key}" ${d.color===key?'checked':''}><i style="--swatch:${MANSION_COLORS[key]}"></i><span>${name}</span></label>`).join('')}</div>${select('roof',L('Roof design'),MANSION_ROOFS)}</fieldset>
 <footer class="estate-controls-footer"><button data-action="mansion-reset">Reset to default design</button><p>Closing discards unapplied changes.<br>Shrinking the size adjusts rooms to fit capacity.</p></footer></div></div></div>`;
}
import {mansionSitePreview} from './mansion-preview.js';
