import {awardAssetFame} from './reputation.js';
export const MANSION_SIZES={1:{name:'컴팩트',area:120},2:{name:'그랜드',area:200},3:{name:'에스테이트',area:320},4:{name:'팰리스',area:800},5:{name:'프라이빗 왕국',area:2000}};
export const MANSION_STYLES={modern:'모던 빌라',classic:'클래식 궁전',resort:'리조트 하우스'};
export const MANSION_COLORS={ivory:'#e9ddc5',white:'#edf1eb',charcoal:'#57656a',terracotta:'#c88970'};
export const MANSION_ROOFS={flat:'평지붕',gable:'박공지붕',terrace:'루프톱 테라스'};
export const DEFAULT_MANSION=Object.freeze({size:2,floors:2,rooms:6,style:'classic',color:'ivory',roof:'gable',pool:true,garden:true,cinema:false,golf:false,spa:false,helipad:false});
export const mansionDesign=s=>({...DEFAULT_MANSION,...s.flex?.mansion});
export const mansionArea=d=>d.area??MANSION_SIZES[d.size].area;
export const roomCapacity=d=>Math.min(120,Math.floor(mansionArea(d)/50)*d.floors);
export const MANSION_EXTRAS={cinema:{name:'프라이빗 영화관',price:250000},golf:{name:'전용 골프 코스',price:1500000},spa:{name:'웰니스 스파',price:400000},helipad:{name:'전용 헬리패드',price:2500000}};
export const MANSION_MAINTENANCE_RATE=.004;
export function validMansion(d){return !!d&&Object.keys(d).every(k=>Object.hasOwn(DEFAULT_MANSION,k)||k==='area')&&Number.isInteger(d.size)&&Object.hasOwn(MANSION_SIZES,d.size)&&(d.area===undefined||Number.isInteger(d.area)&&d.area>=120&&d.area<=10000)&&Number.isInteger(d.floors)&&d.floors>=1&&d.floors<=10&&Number.isInteger(d.rooms)&&d.rooms>=2&&d.rooms<=roomCapacity(d)&&Object.hasOwn(MANSION_STYLES,d.style)&&Object.hasOwn(MANSION_COLORS,d.color)&&Object.hasOwn(MANSION_ROOFS,d.roof)&&typeof d.pool==='boolean'&&typeof d.garden==='boolean'&&Object.keys(MANSION_EXTRAS).every(k=>d[k]===undefined||typeof d[k]==='boolean');}
export function mansionBreakdown(d){const area=mansionArea(d),structure=17000+d.size*3000+d.floors*3000+d.rooms*500+Math.round(35*Math.max(0,area-200)**1.8)+Math.round(30000*Math.max(0,d.floors-2)**2.5)+Math.round(2500*Math.max(0,d.rooms-6)**2),finish=({modern:25000,classic:0,resort:75000}[d.style])+({ivory:0,white:12000,charcoal:30000,terracotta:22000}[d.color])+({flat:0,gable:0,terrace:90000}[d.roof]),facilities=(d.pool?2000:0)+(d.garden?1000:0)+Object.entries(MANSION_EXTRAS).reduce((sum,[k,v])=>sum+(d[k]?v.price:0),0),count=Object.keys(MANSION_EXTRAS).filter(k=>d[k]).length,multiplier=2.4**count;return{structure,finish,facilities,multiplier,total:Math.round((structure+finish+facilities)*multiplier)};}
export function designValue(d){return mansionBreakdown(d).total;}
export function mansionMaintenance(d){return Math.round(designValue(d)*MANSION_MAINTENANCE_RATE);}
const same=(a,b)=>Object.keys(DEFAULT_MANSION).every(k=>(a[k]??DEFAULT_MANSION[k])===(b[k]??DEFAULT_MANSION[k]))&&mansionArea(a)===mansionArea(b);
export function mansionQuote(s,d,wealth){
 if(!validMansion(d))return{cost:0,error:'설계 값을 확인하세요.'};
 const owned=s.flex?.owned.includes('penthouse'),old=mansionDesign(s),cost=owned?(same(old,d)?0:1500+Math.max(0,designValue(d)-designValue(old))):designValue(d);
 const error=!owned&&s.mode!=='sandbox'&&Math.max(s.highestWealth,wealth)<100000?'최고 순자산 ₲100,000 달성 후 시공 가능':owned&&same(old,d)?'현재 저택과 같은 설계입니다.':s.money<cost?'공사할 현금이 부족합니다.':null;
 return{cost,error,owned};
}
export function buildMansion(s,d,wealth){const q=mansionQuote(s,d,wealth);if(q.error)return{ok:false,msg:q.error};s.flex??={owned:[],lastParty:-1};if(!q.owned)s.flex.owned.push('penthouse');s.flex.mansion={...DEFAULT_MANSION,...d};s.money-=q.cost;s.highestWealth=Math.max(s.highestWealth,wealth);s.log.unshift(`🏛 나만의 저택 ${q.owned?'리모델링':'완공'} · ${MANSION_SIZES[d.size].name} ${d.floors}층 ${d.rooms}개 방 · ₲${q.cost.toLocaleString('ko-KR')}`);s.log=s.log.slice(0,25);awardAssetFame(s,'mansion',designValue(d),'대저택 완공');return{ok:true,msg:'나만의 저택 완공! 지도에 설계를 반영했습니다.'};}
export function mansionArt(d){const width=160+Math.min(5,d.size)*38,left=320-width/2,height=Math.min(150,d.floors*30),top=216-height,col=MANSION_COLORS[d.color],windows=Math.ceil(d.rooms/d.floors);let panes='';for(let floor=0;floor<d.floors;floor++){const count=Math.min(windows,d.rooms-floor*windows);for(let n=0;n<count;n++){const x=left+18+n*(width-36)/windows,y=top+5+floor*(height/d.floors);panes+=`<rect x="${x}" y="${y}" width="${Math.max(2,(width-48)/windows-3)}" height="${Math.max(4,height/d.floors-8)}" rx="${d.style==='classic'?8:1}" fill="${d.style==='modern'?'#81bac7':'#ecd295'}" stroke="#516770" stroke-width="2"/>`;}}
 const roof=d.roof==='gable'?`<path d="M${left-14} ${top}L320 ${top-39}L${left+width+14} ${top}Z" fill="${d.style==='resort'?'#b67e60':'#72858a'}"/>`:`<rect x="${left-9}" y="${top-8}" width="${width+18}" height="8" fill="#526b70"/>${d.roof==='terrace'?`<path d="M${left} ${top-9}V${top-25}H${left+width}V${top-9}" fill="none" stroke="#a9c5c3" stroke-width="3"/><rect x="${left+22}" y="${top-22}" width="36" height="14" rx="5" fill="#ccad76"/>`:''}`;
 return `<svg viewBox="0 0 640 300" class="mansion-art" role="img" aria-label="${MANSION_STYLES[d.style]}, ${MANSION_SIZES[d.size].name}, ${d.floors}층, 방 ${d.rooms}개${d.pool?', 수영장':''}${d.garden?', 정원':''}"><rect width="640" height="300" rx="16" fill="#dae7e4"/><circle cx="542" cy="51" r="26" fill="#f8e5b8"/><path d="M0 216Q180 188 320 216T640 205V300H0Z" fill="#b6c7a4"/><path d="M270 216H360L410 300H226Z" fill="#ded6c2"/><rect x="${left+14}" y="${top+10}" width="${width}" height="${height}" fill="#78908c"/><rect x="${left}" y="${top}" width="${width}" height="${height}" fill="${col}"/>${panes}${roof}${d.style==='classic'?[left+5,left+width-12].map(x=>`<rect x="${x}" y="${top+4}" width="7" height="${height-4}" fill="#fff0d1"/>`).join(''):''}${d.style==='resort'?`<path d="M${left-10} 186H${left+width+10}" stroke="#b1835a" stroke-width="9"/>`:''}<rect x="304" y="187" width="32" height="29" fill="#47656c"/><circle cx="329" cy="203" r="2" fill="#e9c57a"/>${d.pool?'<rect x="379" y="238" width="176" height="44" rx="15" fill="#eee2c9"/><rect x="386" y="244" width="162" height="31" rx="10" fill="#62b8ce"/><path d="M400 255H531M414 264H510" stroke="#ade2e9" stroke-width="2"/>':''}${d.garden?[80,123,584].map((x,i)=>`<path d="M${x} 252V218" stroke="#897258" stroke-width="5"/><circle cx="${x}" cy="213" r="${19+i*3}" fill="#638f6c"/><circle cx="${x-6}" cy="204" r="14" fill="#85ac7e"/>`).join(''):''}<text x="24" y="282" fill="#37595b" font-size="12">${mansionArea(d)*d.floors}㎡ · ${d.floors}층 · 방 ${d.rooms}개</text></svg>`;
}
export function floorPlan(d){const counts=Array.from({length:d.floors},(_,i)=>Math.floor(d.rooms/d.floors)+(i<d.rooms%d.floors?1:0));return `<div class="mansion-plans">${counts.map((count,i)=>`<section><b>${i+1}층 · ${count}개 방</b><div class="mansion-rooms">${Array.from({length:count},(_,n)=>`<span>${i===0&&n===0?'거실':i===0&&n===1?'주방':n===0?'침실':n===1?'서재':'다목적실'}</span>`).join('')||'<span>오픈 라운지</span>'}</div></section>`).join('')}</div><p class="help">방 수를 층별로 나눈 개념 평면도입니다. 방에는 거실·주방도 포함되며, 복도·계단·욕실은 별도 공용 공간입니다.</p>`;}
const MANSION_MOODS={
 classic:{title:'시간이 흘러도, 품격은 남도록.',text:'따뜻한 석재와 균형 잡힌 외관. 매일의 귀가를 특별하게 만드는 클래식 레지던스.',tag:'THE HERITAGE'},
 modern:{title:'탁 트인 시선, 여유로운 일상.',text:'빛을 가득 들이는 유리와 절제된 선. 공간 그 자체가 취향이 되는 모던 레지던스.',tag:'THE MODERN'},
 resort:{title:'머무는 모든 날이, 휴가처럼.',text:'자연의 색과 포근한 소재. 멀리 떠나지 않아도 휴식이 시작되는 리조트 레지던스.',tag:'THE RETREAT'}
};
const mansionMoney=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
export function mansionPreview(s,d,wealth){
 const q=mansionQuote(s,d,wealth),cost=mansionBreakdown(d),mood=MANSION_MOODS[d.style],facilities=[...(d.pool?['프라이빗 수영장']:[]),...(d.garden?['조경 정원']:[]),...Object.entries(MANSION_EXTRAS).filter(([k])=>d[k]).map(([,v])=>v.name)];
 return `${mansionSitePreview(d,{area:mansionArea(d),color:MANSION_COLORS[d.color],styleName:MANSION_STYLES[d.style]})}<details class="estate-inspiration"><summary>건축 스타일 이미지 <span>${MANSION_STYLES[d.style]} ＋</span></summary><figure class="estate-hero"><img src="./city/assets/luxury/mansion-${d.style}.png" width="1536" height="1024" alt="${MANSION_STYLES[d.style]} 스타일 참고 이미지"><figcaption><span>${mood.tag} / PRIVATE RESIDENCE</span><h3>${mood.title}</h3><p>${mood.text}</p></figcaption><span class="estate-preview-tag">건축 스타일 참고 이미지</span></figure></details>
 <div class="estate-specs"><div><span>연면적</span><strong>${(mansionArea(d)*d.floors).toLocaleString('ko-KR')}<small> ㎡</small></strong></div><div><span>건물 층수</span><strong>${d.floors}<small> 층</small></strong></div><div><span>나만의 공간</span><strong>${d.rooms}<small> 개 방</small></strong></div><div><span>외관 스타일</span><b>${MANSION_STYLES[d.style]}</b></div></div>
 <p class="estate-image-note">예상도는 선택한 시설·외장·지붕을 반영한 개념 조감도입니다. 배치와 비율은 이해를 돕기 위한 표현입니다. 현금이 부족해도 자유롭게 설계할 수 있습니다.</p>
 <section class="estate-quote" aria-label="시공 견적"><div class="estate-quote-head"><div><span>${q.owned?'나의 저택 리모델링':'나의 첫 프라이빗 저택'}</span><strong>${mansionMoney(q.cost)}</strong></div><span class="estate-quote-seal">DESIGNED<br>FOR YOU</span></div><div class="estate-quote-meta"><span>월 관리비 <b>${mansionMoney(mansionMaintenance(d))}</b></span><span>시공 후 현금 <b>${mansionMoney(s.money-q.cost)}</b></span></div><button data-action="mansion-build" ${q.error?'disabled':''}>${q.error||'이 저택에서의 삶, 시작하기 →'}</button><p>${q.owned?'리모델링은 기본 ₲1,500 + 설계 가치 증가분입니다. 축소 시 환급은 없습니다.':'최고 순자산 ₲100,000부터 신축할 수 있습니다.'} 시공비는 현금과 순자산에서 차감되며, 월 관리비는 설계 가치의 0.4%입니다.</p></section>
 <details class="estate-detail"><summary>설계 요약과 공간 구성 <span>도면 보기 ＋</span></summary><div class="estate-design-summary"><b>${MANSION_STYLES[d.style]} · ${MANSION_ROOFS[d.roof]}</b><span>층당 ${mansionArea(d).toLocaleString('ko-KR')}㎡ · ${({ivory:'웜 아이보리',white:'퓨어 화이트',charcoal:'차콜 그레이',terracotta:'테라코타'})[d.color]}</span><p>${facilities.length?facilities.join(' · '):'추가 시설 없이 건축의 본질에 집중한 공간'}</p></div>${mansionArt(d)}${floorPlan(d)}</details>
 <details class="estate-detail"><summary>시공비 상세 내역 <span>견적 보기 ＋</span></summary><dl class="estate-costs"><div><dt>규모 공사비</dt><dd>${mansionMoney(cost.structure)}</dd></div><div><dt>외장·지붕</dt><dd>${mansionMoney(cost.finish)}</dd></div><div><dt>시설</dt><dd>${mansionMoney(cost.facilities)}</dd></div><div><dt>고급 시설 복합 시공</dt><dd>×${cost.multiplier.toFixed(2)}</dd></div><div><dt>신축 기준 총액</dt><dd>${mansionMoney(cost.total)}</dd></div></dl><p class="help">영화관·골프장·스파·헬리패드는 하나 추가할 때마다 전체 견적이 ×2.4가 됩니다. 면적·층수·방 수가 커질수록 규모 공사비도 비선형으로 증가합니다.</p></details>`;
}
export function mansionDialog(s,d,wealth){
 const select=(key,title,values)=>`<label>${title}<select data-mansion="${key}">${Object.entries(values).map(([v,name])=>`<option value="${v}" ${String(d[key])===v?'selected':''}>${name}</option>`).join('')}</select></label>`;
 const amenities={pool:['프라이빗 수영장','햇살 아래, 나만의 물가'],garden:['조경 정원','산책으로 시작하는 아침'],cinema:['프라이빗 영화관','좋아하는 영화의 첫 번째 관객'],golf:['전용 골프 코스','집 앞에서 즐기는 라운드'],spa:['웰니스 스파','하루를 천천히 내려놓는 곳'],helipad:['전용 헬리패드','어디로든 이어지는 나의 집']};
 return `<div class="mansion-studio"><header class="estate-header"><div><span class="eyebrow">THE PRIVATE RESIDENCE COLLECTION</span><h2>당신이 꿈꾸던 집, 그 이상의 일상.</h2><p>취향을 고르고, 공간을 채우세요. 당신만의 저택이 완성됩니다.</p></div><span class="estate-edition">RESIDENCE<br>ATELIER <i>01 — 03</i></span></header><div class="estate-layout"><div id="mansion-preview" aria-live="polite">${mansionPreview(s,d,wealth)}</div><div class="estate-controls">
 <fieldset class="estate-section"><legend><span>01</span> 건축의 취향</legend><p>당신의 삶을 담을 세 가지 스타일.</p><div class="estate-style-options">${Object.entries(MANSION_STYLES).map(([key,name])=>`<label class="estate-style"><input type="radio" name="mansion-style" data-mansion="style" value="${key}" ${d.style===key?'checked':''}><img src="./city/assets/luxury/mansion-${key}.png" alt="" width="1536" height="1024"><span>${name}</span></label>`).join('')}</div></fieldset>
 <fieldset class="estate-section"><legend><span>02</span> 나를 위한 특별한 공간</legend><div class="estate-amenities">${Object.entries(amenities).map(([key,[name,description]])=>`<label><input type="checkbox" data-mansion="${key}" ${d[key]?'checked':''}><span><b>${name}</b><small>${description}</small></span></label>`).join('')}</div><p class="estate-facility-note">영화관·골프·스파·헬리패드는 추가할 때마다 전체 견적 ×2.4. 선택 즉시 견적에 반영됩니다.</p></fieldset>
 <fieldset class="estate-section"><legend><span>03</span> 여유를 담는 규모</legend><div class="estate-fields">${select('size','저택 규모',Object.fromEntries(Object.entries(MANSION_SIZES).map(([k,v])=>[k,v.name+' · '+v.area+'㎡'])))}<label>층당 면적 (㎡)<input data-mansion="area" type="number" min="120" max="10000" step="10" value="${mansionArea(d)}"></label>${select('floors','층수',Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,(i+1)+'층'])))}<label>전체 방 개수<input data-mansion="rooms" type="number" min="2" max="${roomCapacity(d)}" step="1" value="${d.rooms}"></label></div><small id="mansion-capacity">현재 규모에서 2–${roomCapacity(d)}개</small></fieldset>
 <fieldset class="estate-section"><legend><span>04</span> 마감의 디테일</legend><span class="estate-field-title">외벽 색상</span><div class="estate-swatches">${Object.entries({ivory:'웜 아이보리',white:'퓨어 화이트',charcoal:'차콜 그레이',terracotta:'테라코타'}).map(([key,name])=>`<label title="${name}"><input type="radio" name="mansion-color" data-mansion="color" value="${key}" ${d.color===key?'checked':''}><i style="--swatch:${MANSION_COLORS[key]}"></i><span>${name}</span></label>`).join('')}</div>${select('roof','지붕 디자인',MANSION_ROOFS)}</fieldset>
 <footer class="estate-controls-footer"><button data-action="mansion-reset">기본 설계로 되돌리기</button><p>닫으면 미적용 설계는 취소됩니다.<br>규모를 줄이면 방 수는 수용 범위에 맞춰 조정됩니다.</p></footer></div></div></div>`;
}
import {mansionSitePreview} from './mansion-preview.js';
