import {propertyArt} from './property-art.js';
import {L} from './i18n.js';
import {missionProgress,missionStats,CONTRACT_IDS,contractQuote,contractProgress} from './missions.js';
import {canBuild,developmentQuote,coords,hasRoadAccess} from './engine.js';
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
export const missionNames=()=>({'first-build':L('My first new building'),'first-settlement':L('Collect my first building settlement'),'first-profit':L('Finish a profitable month'),district:L('Build a street with three new assets and a park'),reserve:L('Keep three months of operating reserves'),wealth:L('Reach ₲3,000,000 net worth'),landmark:L('Complete my first signature building'),tourism:L('Tourism development'),cashflow:L('Twelve months without a fire sale'),redevelopment:L('Neighborhood renewal'),skyline:L('A new skyline')});
export function starterSites(s,a){
 const currentReserve=missionStats(s,a).reserve,result=[];
 // Quote a small spread of roadside lots plus those near existing holdings.
 // A full-map quote scan blocks the first click on large cities.
 const vacant=s.tiles.map((t,i)=>({t,i})).filter(({t,i})=>t.terrain==='land'&&!t.type&&!t.owner&&hasRoadAccess(s,i)).map(({i})=>i);
 const origins=a.owned.map(({i})=>coords(i)),distance=i=>{const p=coords(i);return origins.length?Math.min(...origins.map(o=>Math.abs(o.x-p.x)+Math.abs(o.y-p.y))):i;};
 const nearby=[...vacant].sort((i,j)=>distance(i)-distance(j)).slice(0,24),spread=Array.from({length:Math.min(24,vacant.length)},(_,n)=>vacant[Math.floor(n*vacant.length/Math.min(24,vacant.length))]);
 const candidates=[...new Set([...nearby,...spread])];
 for(const type of ['hotel','housing']){
  let best=null;
  for(const i of candidates){if(canBuild(s,i,type,'buy',{width:1,height:1}))continue;
   const q=developmentQuote(s,i,type,1,{width:1,height:1}),reserve=currentReserve+Math.ceil(q.cost*3);if(q.profit<=0||s.money-q.total<reserve)continue;
   if(!best||q.profit/q.total>best.q.profit/best.q.total)best={i,type,q,reserve};
  }
  if(best)result.push(best);
 }
 return result;
}
export function firstMoveChoices(s,sites){
 const site=sites.find(x=>x.type==='hotel')||sites[0];if(!site)return '';
 const {i,type,q}=site;
 return `<h2 id="tutorial-title" tabindex="-1">${type==='hotel'?L('Open your first hotel'):L('Build your first homes')}</h2><p>${L('We picked a suitable spot. One click turns this empty lot into your place.')}</p><div class="first-move-option">${propertyArt(type,true).replace('loading="lazy"','loading="eager"')}<strong>${L`Projected monthly profit +${money(q.profit)}`}</strong><button class="primary" data-first-build="${i}" data-first-type="${type}" data-first-price="${q.total}">${type==='hotel'?L`Open this hotel · ${money(q.total)}`:L`Build these homes · ${money(q.total)}`}</button></div><p class="first-move-hint">${L('The displayed cost buys the land and building. Next, collect your first month.')}</p>`;
}
export function firstMoveOpening(s,a,i){
 const t=s.tiles[i],r=a.reports[i];if(t?.owner!=='player'||!r||!['hotel','housing'].includes(t.type))return '';
 return `<h2 id="tutorial-title" tabindex="-1">${L('The doors are open. This place is yours.')}</h2><div class="first-move-opening">${propertyArt(t.type,true)}<div><b>${t.type==='hotel'?L('My first hotel'):L('Homes for my neighborhood')}</b><strong>${L`Projected profit ${money(r.profit)} / month`}</strong></div></div><p>${L('Your place is ready. Press once to collect a real month of income.')}</p><button class="primary full" data-action="tutorial-next">${L('Collect my first month →')}</button><small>${L('This settles the whole city. Markets and costs can change the result.')}</small>`;
}
export function missionCard(s,a){
 const names=missionNames(),progress=missionProgress(s,a),next=progress.find(p=>!p.complete);
 const m=s.missions,c=m?.active,cp=contractProgress(s,a);
 return `<section class="mission-card"><span class="eyebrow">${L('MY NEXT ACHIEVEMENT')}</span><h3>${c?names[c.id]:next?names[next.id]:L('Your city is ready for a new challenge')}</h3>${c?`<p>${L`Current progress ${Math.round(cp.value).toLocaleString('en-US')} / ${Math.round(cp.target).toLocaleString('en-US')}`}</p><p>${L`Game months left: ${Math.max(0,c.deadline-s.month)} · Property investment ${money(c.spent)} / ${money(c.budget)}`}</p>`:next?`<div class="meter"><i style="width:${Math.max(0,Math.min(100,next.value/next.target*100))}%"></i></div><p>${L`Progress ${Math.min(next.value,next.target).toLocaleString('en-US')} / ${next.target.toLocaleString('en-US')}`}</p>`:''}<div class="button-row">${next?.id==='first-build'?`<button class="primary" data-action="mission-build">${L('Choose my first building')}</button>`:next?.id==='first-settlement'||next?.id==='first-profit'?`<button class="primary" data-action="mission-settle">${L('Settle a month and see the result')}</button>`:''}<button data-action="missions">${L('Missions and city projects')}</button></div><small>${L`Achievements ${m?.completed.length||0} / ${progress.length+CONTRACT_IDS.length}`}</small></section>`;
}
export function starterDialog(s,a){
 const sites=starterSites(s,a);
 return `<h2>${L('Choose the first place you will build')}</h2><p>${L('Both recommendations use real prices and leave three months of reserves. Nothing is spent until you confirm the contract.')}</p>${sites.map(({i,type,q,reserve})=>{const p=coords(i);return `<section class="mission-option"><h3>${type==='hotel'?L('My first hotel'):L('Homes for my neighborhood')}</h3><p>${L`Lot ${p.x+1}, ${p.y+1} · Total ${money(q.total)} · Projected profit ${money(q.profit)} / month`}</p><p>${L`Cash after building ${money(s.money-q.total)} · Reserve ${money(reserve)}`}</p><button class="primary" data-starter-site="${i}" data-starter-type="${type}">${L('Review this build contract')}</button></section>`;}).join('')||`<p>${L('No affordable positive-profit site meets the reserve rule right now. Review your holdings or settle a month before investing.')}</p>`}<button data-action="stocks">${L('Review stocks to release cash')}</button><button data-action="mission-settle">${L('Settle a month and see the result')}</button>`;
}
const descriptions=()=>({tourism:L('Grow tourism revenue by 20% or ₲5,000, whichever is higher, within twelve game months.'),cashflow:L('Keep every settlement non-negative for twelve game months. No forced asset sales.'),redevelopment:L('Lift average foot traffic at your properties by eight points, up to 100, within twelve game months.'),skyline:L('Raise your highest completed skyscraper by 10% or five floors, whichever is higher, within twelve game months.')});
export function missionsDialog(s,a){
 const names=missionNames(),progress=missionProgress(s,a),m=s.missions,desc=descriptions();
 return `<h2>${L('My city, my next achievement')}</h2><p>${L('Build, earn and shape your city. Completed achievements stay in this saved story.')}</p><div class="mission-list">${progress.map(p=>`<div><b>${p.complete?'✓':'○'} ${names[p.id]}</b><small>${p.complete?L('Achieved'):L`Progress ${Math.min(p.value,p.target).toLocaleString('en-US')} / ${p.target.toLocaleString('en-US')}`}</small></div>`).join('')}</div><h3>${L('Choose a twelve-month city project')}</h3><p>${L('Your city stays intact. Property purchases, construction and expansion count toward the stated investment budget. Exceeding it or a forced sale ends the project. No cash rewards or permanent income multipliers.')}</p>${m.active?`<section class="mission-option"><h3>${names[m.active.id]}</h3><p>${L`Current progress ${Math.round(contractProgress(s,a).value).toLocaleString('en-US')} / ${Math.round(m.active.target).toLocaleString('en-US')}`}</p><p>${desc[m.active.id]}</p><p>${L`Game months left: ${Math.max(0,m.active.deadline-s.month)} · Property investment ${money(m.active.spent)} / ${money(m.active.budget)}`}</p><p>${L`Target ${Math.round(m.active.target).toLocaleString('en-US')} · Baseline ${Math.round(m.active.baseline).toLocaleString('en-US')}`}</p><button data-action="mission-cancel">${L('End this project and keep my city')}</button></section>`:CONTRACT_IDS.map(id=>{const q=contractQuote(s,a,id);return `<section class="mission-option"><h3>${names[id]}</h3><p>${desc[id]}</p>${id==='skyline'&&q.baseline===0?`<p>${L('Complete a skyscraper before choosing this project.')}</p>`:''}<p>${L`Property investment budget ${money(q.budget)} · Target ${Math.round(q.target).toLocaleString('en-US')}`}</p><button data-mission-start="${id}" ${id==='redevelopment'&&q.baseline>=100||id==='skyline'&&q.baseline===0?'disabled':''}>${L('Start this city project')}</button></section>`;}).join('')}<section class="mission-option"><h3>${L('Twelve-month development challenge')}</h3><p>${L('Try the same starting city as other players for twelve months. Keep your main city and compare your best result.')}</p><button data-action="trial-start">${L('Start an equal-start challenge')}</button></section><h3>${L('City honors')}</h3><p>${L('A completed project earns its city title and a record. Scores reward unspent budget; comparisons are personal records from different cities, not an equal-start competition.')}</p>${m.history.length?m.history.slice().reverse().map(h=>`<p>${h.won?'🏅':'○'} ${names[h.id]} · ${L`Month ${h.month} · Score ${h.score}`} · ${h.won?L('Completed'):h.reason==='budget'?L('Investment budget exceeded'):h.reason==='fire-sale'?L('Forced asset sale'):h.reason==='cancelled'?L('Ended by player'):L('Target not reached')}</p>`).join(''):`<p>${L('Your first city honor is waiting.')}</p>`}`;
}
export function cashAdvice(s,a){const reserve=missionStats(s,a).reserve;if(s.money>=reserve&&a.net>=0)return'';return `<section class="mission-cash"><h3>${L('Protect cash for your next move')}</h3><p>${L`Cash ${money(s.money)} · Three-month reserve ${money(reserve)} · Projected monthly cash flow ${money(a.net)}`}</p><p>${L('Selling part of your stocks can release cash. Check rent, upkeep and management before expanding; property sales show their costs before confirmation.')}</p><div class="button-row"><button data-action="stocks">${L('Review stocks to release cash')}</button><button data-action="portfolio">${L('Review property operations')}</button></div></section>`;}
