import {L} from './i18n.js';
import {createGame,analyze,build,canBuild,hasRoadAccess,STOCKS,trade} from './engine.js';
import {DEFAULT_MANSION} from './mansion.js';
import {ensureVentures} from './venture.js';
import {SCENARIOS} from './legacy.js';
export const RICH_SAVE_KEY='super-rich-lifestyle-v1';
export const RICH_GOALS=[{wealth:3000000,name:L('Asset Builder')},{wealth:5000000,name:L('Private Investor')},{wealth:10000000,name:L('Asset Empire')},{wealth:20000000,name:L('Corporate Acquirer')},{wealth:30000000,name:L('Group Chairman')},{wealth:60000000,name:L('Media Owner')},{wealth:150000000,name:L('Team Owner')},{wealth:300000000,name:L('Legacy Maker')}];
// Three starting routes share one economy: the heir (default), the self-made founder and the windfall spender.
export function createRichGame(mode='standard',seed=42,scenario='heir'){const s=createGame(mode,seed);s.concept='rich-life';s.scenario=Object.hasOwn(SCENARIOS,scenario)?scenario:'heir';s.money=2000000;s.skill=70;s.stress=10;s.plan={work:0,manage:40,learn:20,create:0};s.career='engineer';s.highestWealth=2000000;s.name=L('Riverview Estate');s.flex={owned:['sportscar','penthouse'],lastParty:-1,mansion:{...DEFAULT_MANSION}};ensureVentures(s);s.artCollection={owned:[]};s.lifestyle={spent:0,memories:0,last:{}};s.prestige=0;
 if(s.scenario==='selfmade'){s.flex={owned:[],lastParty:-1};s.holdings={local:0,tech:0,estate:0};s.costBasis={local:0,tech:0,estate:0};s.money=500000;s.skill=85;s.stress=20;s.highestWealth=500000;s.startingWealth=500000;s.name=L('Riverside Start');s.log=[L('⚒ Cash ₲500,000, assets 0. The road to your first hotel is the longest one.'),L('Your rival is already working ₲450,000. Grab the good land first.')];return s;}
 if(s.scenario==='windfall'){s.flex={owned:['sportscar','penthouse','yacht'],lastParty:-1,mansion:{...DEFAULT_MANSION}};s.holdings={local:0,tech:0,estate:0};s.costBasis={local:0,tech:0,estate:0};s.money=3500000;s.skill=40;s.stress=45;s.highestWealth=3500000;s.startingWealth=3500000;s.name=L('Golden Harbor');s.log=[L('✦ Cash ₲3,500,000. Mansion, sports car and yacht are already bought, and living costs are 3× everyone else.'),L('Income is 0. Put the money to work before upkeep eats your cash every month.')];return s;}
 for(const type of ['condo','condo','rental']){const i=s.tiles.findIndex((t,i)=>hasRoadAccess(s,i)&&!canBuild(s,i,type,'buy'));if(i>=0)build(s,i,type,'buy');}
 s.holdings={local:2000,tech:2000,estate:3500};s.costBasis=Object.fromEntries(STOCKS.map(k=>[k.id,s.holdings[k.id]*s.prices[k.id]]));s.money=2000000-analyze(s).assets-analyze(s).stocks;s.startingWealth=2000000;s.log=[L('✦ You start with a net worth of ₲2,000,000. A mansion, a sports car, 3 rentals and a stock portfolio are ready.'),L('Grow the assets further, or enjoy today. Rent and dividends come in without a salary.')];return s;}
export const EXPERIENCES={travel:{name:L('Private Retreat Trip'),icon:'✈',cost:10000,stress:40,skill:0,description:L('Clear the calendar and get away · Stress −40')},patron:{name:L('Art Collector Salon'),icon:'◈',cost:15000,stress:25,skill:3,description:L('A private show with the artist · Expertise +3 · Stress −25')},cruise:{name:L('Sunset Yacht Cruise'),icon:'⛵',cost:5000,stress:30,skill:0,description:L('An evening aboard your own yacht · Yacht required · Stress −30')}};
Object.assign(EXPERIENCES,{
 party:{name:L('World Celebrity Private Party'),icon:'🥂',cost:25000,stress:60,skill:0,description:L('A night in Cannes with global film, music and sports stars'),image:'party',alt:L('A rooftop party with fictional figures standing in for global stars'),caption:L('Glittering night views and easy talk. Tonight you are the star of the party.')},
 overseas:{name:L('Santorini Getaway'),icon:'✈',cost:18000,stress:70,skill:0,description:L('A holiday among the blue sea and white villages of Greece'),image:'overseas',alt:L('Enjoying a holiday on a Santorini terrace looking out to sea'),caption:L('A slow morning facing the blue sea. Everyday fatigue drifts away.')},
 'cruise-tour':{name:L('Mediterranean Luxury Cruise'),icon:'🛳',cost:30000,stress:90,skill:0,description:L('A Mediterranean loop aboard a large cruise ship · No yacht required'),image:'cruise-tour',alt:L('A drink and the Mediterranean sunset from a cruise sun lounger'),caption:L('Sunset water and a soft breeze. On deck, nothing is in a hurry.')}
});
export function experienceScene(s,id,recovered){const d=EXPERIENCES[id];if(!d?.image)return lifestyleDialog(s);return L`<span class="eyebrow">LIVE WELL · TIME FOR MYSELF</span><h2>${d.name}</h2><figure class="experience-scene"><img src="./city/assets/experiences/${d.image}.png" alt="${d.alt}" width="1536" height="1024"><figcaption>${d.caption}</figcaption></figure><div class="flex-summary" role="status"><b>Stress −${Math.round(recovered)} · now ${Math.round(s.stress)}</b><span>Memories +1 · ${money(d.cost)} spent</span></div><button data-action="lifestyle" class="primary full">Choose another escape →</button>`;}
export function validRichLife(s){if(s.startingWealth!==undefined&&(!Number.isFinite(s.startingWealth)||s.startingWealth<=0))return false;if(s.concept!==undefined&&s.concept!=='rich-life')return false;const l=s.lifestyle;return l===undefined||!!(l&&Number.isFinite(l.spent)&&l.spent>=0&&Number.isInteger(l.memories)&&l.memories>=0&&l.last&&typeof l.last==='object'&&!Array.isArray(l.last)&&Object.entries(l.last).every(([k,v])=>Object.hasOwn(EXPERIENCES,k)&&Number.isInteger(v)&&v>=0&&v<=s.month));}
export function experienceReason(s,id){const d=EXPERIENCES[id];if(!d)return L('Choose an experience.');if(s.lifestyle?.last[id]===s.month)return L('Already enjoyed this month.');if(id==='cruise'&&!s.flex?.owned.includes('yacht'))return L('Add a yacht to your collection first.');if(s.money<d.cost)return L('Not enough cash.');return null;}
export function enjoyExperience(s,id){const error=experienceReason(s,id);if(error)return{ok:false,msg:error};const d=EXPERIENCES[id];s.lifestyle??={spent:0,memories:0,last:{}};s.money-=d.cost;s.stress=Math.max(0,s.stress-d.stress);s.skill=Math.min(100,s.skill+d.skill);s.lifestyle.spent+=d.cost;s.lifestyle.memories++;s.lifestyle.last[id]=s.month;const fame=id==='party'?6:3;s.prestige=Math.max(0,(s.prestige||0)+fame);s.log.unshift(L`${d.icon} ${d.name} · Unforgettable memory +1 · Reputation +${fame} · ₲${d.cost.toLocaleString('en-US')}`);s.log=s.log.slice(0,25);return{ok:true,msg:d.name+L(' · A day spent enjoying my wealth!')};}
export function investBasket(s){const orders=STOCKS.map(k=>({id:k.id,qty:Math.floor(100000/3/s.prices[k.id])})),cost=orders.reduce((n,o)=>n+s.prices[o.id]*o.qty*1.005,0);if(orders.some(o=>o.qty<1))return{ok:false,msg:L('At the current prices a basket order cannot be built.')};if(s.money<cost)return{ok:false,msg:L('Not enough cash for the diversified basket.')};for(const o of orders)trade(s,o.id,o.qty);s.log.unshift(L`↗ Diversified across 3 companies · ₲${Math.round(cost).toLocaleString('en-US')} (fees included)`);s.log=s.log.slice(0,25);return{ok:true,msg:L('Basket invested · Check holdings and dividends in Stocks.')};}
const money=n=>'₲'+Math.round(n).toLocaleString('en-US');
export function lifestyleDialog(s){return L`<span class="eyebrow">LIVE WELL</span><h2>A good life is an asset too.</h2><p>What you enjoyed counts as much as what you own. Recovery shows up as lower stress, and each experience is available once a month.</p><div class="flex-summary"><b>${s.lifestyle?.memories||0} memories collected</b><span>Spent on experiences ${money(s.lifestyle?.spent||0)}</span></div><div class="flex-grid">${Object.entries(EXPERIENCES).map(([id,d])=>`<section class="flex-item"><span class="flex-icon">${d.icon}</span><h3>${d.name}</h3><p>${d.description}${d.image?L` · Stress −${d.stress}`:''}</p><strong>${money(d.cost)}</strong><button data-experience="${id}" ${experienceReason(s,id)?'disabled':''}>${experienceReason(s,id)||L('Enjoy this')}</button></section>`).join('')}</div><p class="help">Experience costs come out of cash and net worth. Stress bottoms out at 0 and expertise caps at 100.</p><div class="button-row"><button data-action="art">Masterpiece Auction</button><button data-action="mansion-design">Mansion Design</button><button data-action="flex">Luxury Collection</button></div>`;}
