import {createGame,analyze,build,canBuild,hasRoadAccess,STOCKS,trade} from './engine.js';
import {DEFAULT_MANSION} from './mansion.js';
import {ensureVentures} from './venture.js';
import {SCENARIOS} from './legacy.js';
export const RICH_SAVE_KEY='super-rich-lifestyle-v1';
export const RICH_GOALS=[{wealth:3000000,name:'자산 확장가'},{wealth:5000000,name:'프라이빗 투자자'},{wealth:10000000,name:'자산 제국'},{wealth:20000000,name:'기업 인수자'},{wealth:30000000,name:'그룹 회장'},{wealth:60000000,name:'미디어 오너'},{wealth:150000000,name:'스포츠 구단주'},{wealth:300000000,name:'레거시 메이커'}];
// Three starting routes share one economy: the heir (default), the self-made founder and the windfall spender.
export function createRichGame(mode='standard',seed=42,scenario='heir'){const s=createGame(mode,seed);s.concept='rich-life';s.scenario=Object.hasOwn(SCENARIOS,scenario)?scenario:'heir';s.money=2000000;s.skill=70;s.stress=10;s.plan={work:0,manage:40,learn:20,create:0};s.career='engineer';s.highestWealth=2000000;s.name='리버뷰 에스테이트';s.flex={owned:['sportscar','penthouse'],lastParty:-1,mansion:{...DEFAULT_MANSION}};ensureVentures(s);s.artCollection={owned:[]};s.lifestyle={spent:0,memories:0,last:{}};s.prestige=0;
 if(s.scenario==='selfmade'){s.flex={owned:[],lastParty:-1};s.holdings={local:0,tech:0,estate:0};s.costBasis={local:0,tech:0,estate:0};s.money=500000;s.skill=85;s.stress=20;s.highestWealth=500000;s.startingWealth=500000;s.name='리버사이드 스타트';s.log=['⚒ 현금 ₲500,000, 자산 0. 첫 호텔까지가 가장 긴 길입니다.','라이벌은 이미 ₲450,000을 굴리고 있습니다. 좋은 땅부터 잡으세요.'];return s;}
 if(s.scenario==='windfall'){s.flex={owned:['sportscar','penthouse','yacht'],lastParty:-1,mansion:{...DEFAULT_MANSION}};s.holdings={local:0,tech:0,estate:0};s.costBasis={local:0,tech:0,estate:0};s.money=3500000;s.skill=40;s.stress=45;s.highestWealth=3500000;s.startingWealth=3500000;s.name='골든 하버';s.log=['✦ 현금 ₲3,500,000. 저택·스포츠카·요트를 이미 샀고, 생활비는 남들의 3배입니다.','수입은 0. 유지비가 매달 현금을 갉아먹기 전에 돈이 일하게 만드세요.'];return s;}
 for(const type of ['condo','condo','rental']){const i=s.tiles.findIndex((t,i)=>hasRoadAccess(s,i)&&!canBuild(s,i,type,'buy'));if(i>=0)build(s,i,type,'buy');}
 s.holdings={local:2000,tech:2000,estate:3500};s.costBasis=Object.fromEntries(STOCKS.map(k=>[k.id,s.holdings[k.id]*s.prices[k.id]]));s.money=2000000-analyze(s).assets-analyze(s).stocks;s.startingWealth=2000000;s.log=['✦ 순자산 ₲2,000,000으로 시작합니다. 저택과 스포츠카, 임대 부동산 3곳과 주식 포트폴리오가 준비되어 있습니다.','자산을 더 키우거나 오늘을 즐기세요. 월급 없이도 임대료와 배당금이 들어옵니다.'];return s;}
export const EXPERIENCES={travel:{name:'프라이빗 휴양 여행',icon:'✈',cost:10000,stress:40,skill:0,description:'일정을 비우고 떠나는 휴가 · 스트레스 −40'},patron:{name:'아트 컬렉터 살롱',icon:'◈',cost:15000,stress:25,skill:3,description:'작가와 함께하는 프라이빗 전시 · 전문성 +3 · 스트레스 −25'},cruise:{name:'선셋 요트 크루즈',icon:'⛵',cost:5000,stress:30,skill:0,description:'내 요트에서 즐기는 저녁 · 요트 소장 필요 · 스트레스 −30'}};
Object.assign(EXPERIENCES,{
 party:{name:'월드 셀럽 프라이빗 파티',icon:'🥂',cost:25000,stress:60,skill:0,description:'칸에서 세계적인 영화·음악·스포츠 스타들과 즐기는 밤',image:'party',alt:'세계적인 스타들을 표현한 가상 인물들과 루프톱 파티를 즐기는 모습',caption:'빛나는 야경, 유쾌한 대화. 오늘 밤은 당신도 파티의 주인공입니다.'},
 overseas:{name:'산토리니 해외 여행',icon:'✈',cost:18000,stress:70,skill:0,description:'그리스의 푸른 바다와 하얀 마을에서 보내는 휴가',image:'overseas',alt:'산토리니 테라스에서 바다를 바라보며 휴가를 만끽하는 모습',caption:'파란 바다를 바라보며 느긋한 아침을 즐깁니다. 일상의 피로가 멀어집니다.'},
 'cruise-tour':{name:'지중해 럭셔리 크루즈 투어',icon:'🛳',cost:30000,stress:90,skill:0,description:'대형 크루즈에서 즐기는 지중해 일주 · 요트 소장 불필요',image:'cruise-tour',alt:'대형 크루즈의 선베드에서 음료와 지중해 노을을 즐기는 모습',caption:'노을빛 바다와 부드러운 바람. 선상에서 아무것도 서두르지 않는 시간을 누립니다.'}
});
export function experienceScene(s,id,recovered){const d=EXPERIENCES[id];if(!d?.image)return lifestyleDialog(s);return `<span class="eyebrow">LIVE WELL · 나를 위한 휴식</span><h2>${d.name}</h2><figure class="experience-scene"><img src="./city/assets/experiences/${d.image}.png" alt="${d.alt}" width="1536" height="1024"><figcaption>${d.caption}</figcaption></figure><div class="flex-summary" role="status"><b>스트레스 −${Math.round(recovered)} · 현재 ${Math.round(s.stress)}</b><span>추억 +1 · ${money(d.cost)} 사용</span></div><button data-action="lifestyle" class="primary full">다른 휴식 고르기 →</button>`;}
export function validRichLife(s){if(s.startingWealth!==undefined&&(!Number.isFinite(s.startingWealth)||s.startingWealth<=0))return false;if(s.concept!==undefined&&s.concept!=='rich-life')return false;const l=s.lifestyle;return l===undefined||!!(l&&Number.isFinite(l.spent)&&l.spent>=0&&Number.isInteger(l.memories)&&l.memories>=0&&l.last&&typeof l.last==='object'&&!Array.isArray(l.last)&&Object.entries(l.last).every(([k,v])=>Object.hasOwn(EXPERIENCES,k)&&Number.isInteger(v)&&v>=0&&v<=s.month));}
export function experienceReason(s,id){const d=EXPERIENCES[id];if(!d)return'경험을 선택하세요.';if(s.lifestyle?.last[id]===s.month)return'이번 달에 이미 즐겼습니다.';if(id==='cruise'&&!s.flex?.owned.includes('yacht'))return'요트를 먼저 소장하세요.';if(s.money<d.cost)return'현금이 부족합니다.';return null;}
export function enjoyExperience(s,id){const error=experienceReason(s,id);if(error)return{ok:false,msg:error};const d=EXPERIENCES[id];s.lifestyle??={spent:0,memories:0,last:{}};s.money-=d.cost;s.stress=Math.max(0,s.stress-d.stress);s.skill=Math.min(100,s.skill+d.skill);s.lifestyle.spent+=d.cost;s.lifestyle.memories++;s.lifestyle.last[id]=s.month;const fame=id==='party'?6:3;s.prestige=Math.max(0,(s.prestige||0)+fame);s.log.unshift(`${d.icon} ${d.name} · 잊지 못할 추억 +1 · 명성 +${fame} · ₲${d.cost.toLocaleString('ko-KR')}`);s.log=s.log.slice(0,25);return{ok:true,msg:d.name+' · 나의 부를 즐기는 하루!'};}
export function investBasket(s){const orders=STOCKS.map(k=>({id:k.id,qty:Math.floor(100000/3/s.prices[k.id])})),cost=orders.reduce((n,o)=>n+s.prices[o.id]*o.qty*1.005,0);if(orders.some(o=>o.qty<1))return{ok:false,msg:'현재 주가에서는 묶음 주문을 구성할 수 없습니다.'};if(s.money<cost)return{ok:false,msg:'분산 투자에 필요한 현금이 부족합니다.'};for(const o of orders)trade(s,o.id,o.qty);s.log.unshift(`↗ 3개 기업 분산 투자 · ₲${Math.round(cost).toLocaleString('ko-KR')} (수수료 포함)`);s.log=s.log.slice(0,25);return{ok:true,msg:'분산 투자 완료 · 주식에서 보유량과 배당을 확인하세요.'};}
const money=n=>'₲'+Math.round(n).toLocaleString('ko-KR');
export function lifestyleDialog(s){return `<span class="eyebrow">LIVE WELL</span><h2>좋은 삶도, 나의 자산.</h2><p>얼마를 가졌는지에 더해, 무엇을 즐겼는지도 남깁니다. 피로 회복은 스트레스 감소로 반영되며, 경험마다 월 1회 이용할 수 있습니다.</p><div class="flex-summary"><b>쌓인 추억 ${s.lifestyle?.memories||0}개</b><span>누적 경험 지출 ${money(s.lifestyle?.spent||0)}</span></div><div class="flex-grid">${Object.entries(EXPERIENCES).map(([id,d])=>`<section class="flex-item"><span class="flex-icon">${d.icon}</span><h3>${d.name}</h3><p>${d.description}${d.image?` · 스트레스 −${d.stress}`:''}</p><strong>${money(d.cost)}</strong><button data-experience="${id}" ${experienceReason(s,id)?'disabled':''}>${experienceReason(s,id)||'이 경험 즐기기'}</button></section>`).join('')}</div><p class="help">경험 비용은 현금과 순자산에서 차감됩니다. 스트레스는 최소 0, 전문성은 최대 100입니다.</p><div class="button-row"><button data-action="art">세계 명작 경매</button><button data-action="mansion-design">저택 디자인</button><button data-action="flex">럭셔리 컬렉션</button></div>`;}
